### ISSUE TITLE
CDA: Common issue - CodeSystemNames are not standardized - Low priority  

### ISSUE THREAD

**Issue by AnanthaKrishnaV** [drajer-health/eCRNow#104]
code System names are not standardized in code, translation and value elements.
<code code="94500-6" codeSystem="2.16.840.1.113883.6.1" codeSystemName="loinc.org"/>
<value xsi:type="CD" code="77386006" codeSystem="2.16.840.1.113883.6.96" codeSystemName="sct" displayName="Patient currently pregnant (finding)"/>

**Comment by nbashyam** [comment]
The current baseline has this working properly, please reopen ticket if it is still an issue.
