### ISSUE TITLE
CDA: Common issue -displayName is missing - Low priority  

### ISSUE THREAD

**Issue by AnanthaKrishnaV** [drajer-health/eCRNow#105]
Display name is not populated in code, translation and value elements. Use coding.text if display is not present.
<code code="94500-6" codeSystem="2.16.840.1.113883.6.1" codeSystemName="loinc.org"/>
<value xsi:type="CD" code="1240581000000104" codeSystem="2.16.840.1.113883.6.96" codeSystemName="sct" sdtc:valueSet="2.16.840.1.114222.4.11.7508" sdtc:valueSetVersion="19/05/2016"/>
<translation code="82589-3" codeSystem="2.16.840.1.113883.6.1" codeSystemName="loinc.org"/>

**Comment by nbashyam** [comment]
Already fixed in previous baselines.
