### ISSUE TITLE
OWASP Dependency checker reports vulnerabilities

### ISSUE THREAD

**Issue by nmeachen** [drajer-health/eCRNow#109]
The Open Source OWASP Dependency checker reports the attached vulnerabilities. Some can be addressed by uplifting to Spring Boot 2.3.7.

[dependency-check-report.zip](https://github.com/drajer-health/eCRNow/files/5699854/dependency-check-report.zip)

**Comment by nmeachen** [comment]
2 high and 1 medium vulnerability can be resolved by upgrading to spring-boot-starter-parent:2.4.1 and applying

<spring-integration.version>5.4.2</spring-integration.version>
<spring-security.version>5.4.2</spring-security.version>

**Comment by nbashyam** [comment]
This has been updated and fixed in the latest baseline, please reopen issue if it still persists.
