### ISSUE TITLE
CDA: EncompassingEncounter – organization id extension doesn't match the root

### ISSUE THREAD

**Issue by AnanthaKrishnaV** [drajer-health/eCRNow#113]
EncompassingEncounter – organization id root is using assigning authority form client details, whereas r4 identifier system as the OID.
representedOrganization
id root="2.16.840.1.113883.1.1.1.1" extension="123456785"

R4Resource:
    "identifier": [
        {
            "use": "official",
            "system": "urn:oid:2.16.840.1.113883.4.4",
            "value": "123456785"
        }

**Comment by nbashyam** [comment]
Updates pushed to baseline.

**Comment by AnanthaKrishnaV** [comment]
Verified, working as expected.
![image](https://user-images.githubusercontent.com/28885907/104987163-08138780-5a3b-11eb-889d-3bf723b4e727.png)
