### ISSUE TITLE
CDA: EncompassingEncounter – Location code is nullflavor

### ISSUE THREAD

**Issue by AnanthaKrishnaV** [drajer-health/eCRNow#114]
EncompassingEncounter – Location code is nullflavor, but organization type is present in r4 resource with code system organization-type.
location
healthCareFacility
id root="2.16.840.1.113883.4.6" extension="Organization/675844/_history/29"
code nullFlavor="NI"
R4Resource:      
  {
            "coding": [
                {
                    "system": "https://fhir.cerner.com/ec2458f2-1e24-41c8-b71b-0e701af7583d/codeSet/278",
                    "code": "PLACEOFSVC",
                    "display": "Place of Service",
                    "userSelected": true
                },
                {
                    "system": "http://terminology.hl7.org/CodeSystem/organization-type",
                    "code": "prov",
                    "display": "Healthcare Provider"
                }
            ],
            "text": "Place of Service"
        }

**Comment by nbashyam** [comment]
Updates pushed to baseline.

**Comment by AnanthaKrishnaV** [comment]
Verified, working as expected.
![image](https://user-images.githubusercontent.com/28885907/104987066-ca166380-5a3a-11eb-84c7-5f7ef649d1c6.png)
