### ISSUE TITLE
CDA: EncompassingEncounter – Location id root and extension are out synch

### ISSUE THREAD

**Issue by AnanthaKrishnaV** [drajer-health/eCRNow#115]
EncompassingEncounter – Location id root is NPI OID but the extension is the id generated from EHR.

location
healthCareFacility
id root="2.16.840.1.113883.4.6" extension="Organization/675844/_history/29"/

**Comment by nbashyam** [comment]
Updates pushed to baseline.

**Comment by AnanthaKrishnaV** [comment]
Verified working as expected.
![image](https://user-images.githubusercontent.com/28885907/104987004-a18e6980-5a3a-11eb-8d1c-3815ffab6033.png)
