### ISSUE TITLE
CDA: common, extension should be populated wit only id part

### ISSUE THREAD

**Issue by AnanthaKrishnaV** [drajer-health/eCRNow#116]
for Extension extract only ID part

id root="2.16.840.1.113883.1.1.1.1" extension="Encounter/97953900/_history/1"/
id root="2.16.840.1.113883.1.1.1.1" extension="https://fhir-open.cerner.com/r4/ec2458f2-1e24-41c8-b71b-0e701af7583d/Condition/d2572357187/_history/2572357187"/
id root="2.16.840.1.113883.4.6" extension="Organization/675844/_history/29"/

**Comment by nbashyam** [comment]
This is now fixed as appropriate in the eICR. If any other locations need to be changed, please open a specific issue.
