### ISSUE TITLE
CDA: Plan of treatment section- datetime not working as expected.

### ISSUE THREAD

**Issue by AnanthaKrishnaV** [drajer-health/eCRNow#122]
Text –>datetime  and effectiveDtTm suppose to pull from Occurrence if present but pulling from AuthoredOn. Because CdaFhirUtilities->getStringForType & getActualDate doesn’t support type “timing”.

"occurrenceTiming": {
    "repeat": {
        "boundsPeriod": {
            "start": "2020-04-30T03:15:00.000-05:00",
            "end": "2020-04-30T15:29:23.000-05:00"
        }
    }

**Comment by nbashyam** [comment]
Updates pushed to baseline.

**Comment by AnanthaKrishnaV** [comment]
Verified, works as expected.
