### ISSUE TITLE
CDA: Medication section - Text and Manufactured material is empty.

### ISSUE THREAD

**Issue by AnanthaKrishnaV** [drajer-health/eCRNow#123]
Text- medication name is empty, when medicalCodebaleConcept is not present it should pick from ingredient.
Manufactured material code is empty . when medicalCodebaleConcept is not present it should pick from ingredient
MedicationRequest.codeableConcept.coding.display, 
MedicationRequest.contained.ingredient.itemCodeableConcept.coding.display

**Comment by nbashyam** [comment]
Updates pushed to baseline.

**Comment by AnanthaKrishnaV** [comment]
Verified, working as expected.
