### ISSUE TITLE
eCRNOW App: Periodic EICR is not generated.

### ISSUE THREAD

**Issue by AnanthaKrishnaV** [drajer-health/eCRNow#134]
Periodic EICR is not generated due to the condition[1]. Periodic EICR will not be generated if the either createEICR or closeOutEICR is already generated. Is this the expected behavior?

[1] - https://github.com/drajer-health/eCRNow/blob/master/src/main/java/com/drajer/eca/model/PeriodicUpdateEicrAction.java#L124

**Comment by nbashyam** [comment]
Will get generated when either no eICR is created initially or new trigger codes are added. Already committed as part of other PRs on 2/19/2021
