### ISSUE TITLE
RestAPI: Authorization url is same as RestApi url

### ISSUE THREAD

**Issue by AnanthaKrishnaV** [drajer-health/eCRNow#141]
Authorization URL[1] for the Direct RestApi is same as RestAPi Url. This will not affect Cerner as Cerner as it's owm AuthorizationServiceImpl, but will cause issue for others and testing the code.

[1] - https://github.com/drajer-health/eCRNow/blob/master/src/main/java/com/drajer/ecrapp/security/AuthorizationServiceImpl.java#L28

**Comment by nbashyam** [comment]
The class has been renamed and modified  (SampleAuthorizationServiceImpl) to generate a sample bearer token for validation purposes.
