### ISSUE TITLE
SonarQube reports Vulnerability issue in Encryption Algorithm

### ISSUE THREAD

**Issue by raghunathsandilya** [drajer-health/eCRNow#155]
Sonar Qube reported Security Vulnerability issue in Encryption Algorithm. 

![image](https://user-images.githubusercontent.com/6822730/107189750-e0975580-6a0f-11eb-9f4c-b0cf5511d94e.png)

**Comment by nbashyam** [comment]
Fixed vulnerabilities per Sonar scan.
