### ISSUE TITLE
sdtc:deceasedInd set to 'true' with sdtc:deceasedTime eq 'NI' for non-deceased patients.

### ISSUE THREAD

**Issue by ElizHough** [drajer-health/eCRNow#183]
Some non-deceased patients - sdtc:deceasedInd eq 'true' and sdtc:deceasedTime eq 'NI'.  Other non-deceased patients have "deceasedInd eq 'false' and sdtc:deceasedTime not present.
https://hl7.org/fhir/R4/patient-definitions.html#Patient.deceased_x_  (Cardinality 0..1) If there's no value in the instance, it means there is no statement on whether or not the individual is deceased. Most systems will interpret the absence of a value as a sign of the person being alive.
In r4. sometimes Patient."deceasedBoolean" is valued, and sometimes not present

**Comment by nviator** [comment]
@nbashyam - re: planning conversation on 1/9/2023, please indicate anticipate spring/release. Thank you! (Admin note: https://github.com/drajer-health/eCRNow/issues/183 https://github.com/drajer-health/eCRNow/issues/429 and https://github.com/drajer-health/eCRNow/issues/342 appear to be same issue.)

**Comment by nbashyam** [comment]
This has been fixed in the baseline for FhirR4 versions.
