### ISSUE TITLE
Handle when Encounter.identifier.type eq "AN" contains invalid system:"urn:oid"

### ISSUE THREAD

**Issue by ElizHough** [drajer-health/eCRNow#184]
For ClinicalDocument/componentOf/encompassingEncounter/id[2]/@root, when Encounter.identifier.type eq "AN", and an invalid "urn" exists in Encounter.identifier.system then suggesting logic similar to the handling of 'MR'. For example, if no valid "urn:oid:" in Patient.identifier.system where code eq "AN" then use the default OID from the client configuration in the app

**Comment by ElizHough** [comment]
Issue is seen in /ClinicalDocument/componentOf/encompassingEncounter/id[2] AND /ClinicalDocument/component/structuredBody/component[2]/section/entry/encounter/id[2]

**Comment by nbashyam** [comment]
This should have been fixed in the current baseline, please reopen if the issue persists.
