### ISSUE TITLE
Social History - code system for ONC Birth Sex

### ISSUE THREAD

**Issue by ElizHough** [drajer-health/eCRNow#186]
Social History contains incorrect codeSystem/codeSystemName for the ONC Birth Sex value. /ClinicalDocument/component/structuredBody/component[6]/section/entry[1]/observation/value/@codeSystem contains 2.16.840.1.113883.5.1 AdminGender but should contain 2.16.840.1.113762.1.4.1 ONC Birth Sex (us-core-birthsex) per IG.

**Comment by ElizHough** [comment]
Patient."extension": [
        {
            "valueCode": "F",
            "url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-birthsex"
Patient."gender": "male",

**Comment by nbashyam** [comment]
The code system is the one to be used which ends in 5.1 and is correct.
4.1 is the value set OID and it is not to be used in the actual XML for codeSystem, instead it could be used if as part of the sdtc.valueset attribute which we are not using currently as it is not required to have valuesets on coded elements unless they are trigger code elements.
