### ISSUE TITLE
Problems Section - sdtc:valueSet and sdtc:valueSetVersion missing

### ISSUE THREAD

**Issue by ElizHough** [drajer-health/eCRNow#187]
Problem Section: sdtc:valueSet and sdtc:valueSetVersion missing in /ClinicalDocument/component/structuredBody/component[1]/section/entry/act/entryRelationship[2]/observation/value 

[eICR273_enc97956991.zip](https://github.com/drajer-health/eCRNow/files/6053704/eICR273_enc97956991.zip)
"matchedCodes":[{"matchedCodes":["http://snomed.info/sct|186747009"],"matchedValues":null,"valueSet":"2.16.840.1.113762.1.4.1146.1123","valueSetVersion":"1","matchedPath":"Condition.code"}]

**Comment by ElizHough** [comment]
"encounterId":"97956991",
"patientId": "12748187"

**Comment by nbashyam** [comment]
Updates checked in on 3/3/2021
