### ISSUE TITLE
Encounter Section - Encounter Dx sdtc:valueSet and sdtc:valueSetVersion and SUBJ entryRelationship

### ISSUE THREAD

**Issue by ElizHough** [drajer-health/eCRNow#188]
Encounter Section - Triggering Encounter Dx is missing sdtc:valueSet and sdtc:valueSetVersion

/ClinicalDocument/component/structuredBody/component[2]/section/entry/encounter/entryRelationship/act/entryRelationship/observation/entryRelationship/observation/value

"triggerMatchStatus":true,"matchedCodes":[{"matchedCodes":["http://hl7.org/fhir/sid/icd-10-cm|B34.2"],"

[eicr276_enc97957388.zip](https://github.com/drajer-health/eCRNow/files/6053719/eicr276_enc97957388.zip)

**Comment by ElizHough** [comment]
Seems to be missing the entryRelationship with typecode eq SUBJ

**Comment by ElizHough** [comment]
"encounterId":"97957388",
"patientId": "12748874"

**Comment by nbashyam** [comment]
Fixed and checked in change along with 187 .
