### ISSUE TITLE
eicr's generated every 3 minutes for specific patient

### ISSUE THREAD

**Issue by akinny** [drajer-health/eCRNow#189]
eicr's generated every 3 minutes when we use the latest ersd.json from aims. Also, noticed the status column keeps appending, for every eicr created. 

Note: We are the latest ersd.json from aims

**Comment by ElizHough** [comment]
Pt example: in non-prod c1941, pt id 12750149, enc id 97959172 with Launch_id 281.
Why were 24 periodic eicrs created for pt. Seems that 22 periodics created an eicr when no new activity. Expected 2 periodics and 1 closeout.
Scenario was that registered pt launched with no triggers (reg date 2/26). The create timer ran, with no triggers/no create eicr generated (ok). Then order entered, a periodic should have ran with serviceRequest.code as the trigger, anticipated a create periodic eicr (ok). Then lab resulted, and would be expected to create another periodic eicr (ok). Pt discharged at 2021-02-27 5:59, subsequently the closeOut ran and created a closeOUt eicr, anticipated (ok). 
Periodic updates are running, producing an eicr when there are no new or changed. Why are periodic eicrs being created when no new triggers?

**Comment by nbashyam** [comment]
Is this reproduceable ? any patient I can use to see how it is happening in the DEV domain

**Comment by nbashyam** [comment]
This has been taken care of with the 3/23/2021 baseline push.
