### ISSUE TITLE
eCRApp Timing Issue: convertDurationToInstant method day, week, month and year doesn't work.

### ISSUE THREAD

**Issue by AnanthaKrishnaV** [drajer-health/eCRNow#190]
In the method convertDurationToInstant[1] day, week, month and year loop doesn't work. The call to LocalDate.now().* method inside each loop is giving error[2]. Days and week can be fixed with below code but Month and year still doesn't work. 

t = new Date().toInstant().plus(Period.ofDays(d.getValue().intValue());
t = new Date().toInstant().plus(Period.ofWeeks(d.getValue().intValue());

[1] - https://github.com/drajer-health/eCRNow/blob/master/src/main/java/com/drajer/ecrapp/util/ApplicationUtils.java#L311
[2] - java.time.DateTimeException: Unable to obtain Instant from TemporalAccessor

**Comment by nbashyam** [comment]
Fixed issue and checked in on 3/3/2021
