### ISSUE TITLE
Problems Section: Conditions (problem-list-item) with ver-status eq "entered-in-error" should be excluded from eICR

### ISSUE THREAD

**Issue by ElizHough** [drajer-health/eCRNow#192]
Need examples from dev environment, but found during prod domain testing.
Problems that are erroneous should be excluded from Problems Section, narrative and structured.

Conditions where category = problem-list-item when
"verificationStatus": {
                    "coding": [
                        {
                            "system": "http://terminology.hl7.org/CodeSystem/condition-ver-status",
                            "code": "entered-in-error",
 
are appearing in the Narrative with status "Resolved". In the Structured area, the entry/act/statusCodes shows as "completed". These should be excluded.
re: Fix for problem triggers and removal of abated problems, as well as effective dates. Need to revisit IG: This section lists and describes all relevant clinical problems at the time the document is generated. At a minimum, all pertinent current and historical problems should be listed.

**Comment by ElizHough** [comment]
dev domain, patientID=12742540

**Comment by nbashyam** [comment]
Fixed issue and checked in on 3/3/2021
