### ISSUE TITLE
Results Section: Narrative "labTestResultValue#" displays "system" for UOM, instead of space char.

### ISSUE THREAD

**Issue by ElizHough** [drajer-health/eCRNow#193]
For Lab results with a unit of measure,  "labTestResultValue#" contains the text "http://unitsofmeasure.org" from the "system".
   "valueQuantity": {
                    "value": 6,
                    "unit": "mg/dL",
                    "system": "http://unitsofmeasure.org",
                    "code": "mg/dL"
                },

dev domain, Pt12742540 Enc97953897

**Comment by nbashyam** [comment]
This is working properly as I can see..here is the sample for the above patient.

<content ID="labTestName1">Triglycerides</content>
</td>
<td>
<content ID="labTestResultValue1">160|http://unitsofmeasure.org|mg/dL</content>
</td>
<td>
<content ID="labTestResultValueDate1">2020-09-09T17:35:00.000Z</content>
</td>
</tr>
<tr>
<td>
<content ID="labTestName2">Chol/HDL</content>
</td>
<td>
<content ID="labTestResultValue2">6|http://unitsofmeasure.org|mg/dL</content>
</td>
<td>
<content ID="labTestResultValueDate2">2020-09-09T17:35:00.000Z</content>
</td>
</tr>
<tr>
<td>
<content ID="labTestName3">HDL</content>
</td>
<td>
<content ID="labTestResultValue3">39|http://unitsofmeasure.org|mg/dL</content>
</td>
<td>
<content ID="labTestResultValueDate3">2020-09-09T17:35:00.000Z</content>
</td>
</tr>
<tr>
<td>
<content ID="labTestName4">LDL</content>
</td>
<td>
<content ID="labTestResultValue4">106|http://unitsofmeasure.org|mg/dL</content>
</td>
<td>
<content ID="labTestResultValueDate4">2020-09-09T17:35:00.000Z</content>

**Comment by ElizHough** [comment]
It's the text narrative that isn't readable: /ClinicalDocument/component/structuredBody/component[3]/section/text/table/tbody/tr[1]/td[2] that displays "http://unitsofmeasure.org" 
<content ID="labTestResultValue1">160|http://unitsofmeasure.org|mg/dL</content>
