### ISSUE TITLE
When evaluating matchedCodes, matchedPath may need to be considered

### ISSUE THREAD

**Issue by ElizHough** [drajer-health/eCRNow#202]
When a patient is registered, and an order is placed for Covid Test. An eicr is created with {"matchedCodes":["http://loinc.org|94500-6"],"matchedValues":null,"valueSet":"2.16.840.1.113762.1.4.1146.1123","valueSetVersion":"1","matchedPath":"ServiceRequest.code"}. A subsequent RR is received from local system with response_type RRVS4 (no rule met)

Later, the order is resulted with Covid 'detected' and a new eicr should be created with {"matchedCodes":["http://loinc.org|94500-6"],"matchedValues":null,"valueSet":"2.16.840.1.113762.1.4.1146.1123","valueSetVersion":"1","matchedPath":"Observation.code"}. A subsequent RR would be received from local system with response_type RRVS1 (reportable).

An additional eicr for the matchedCode is not generating when the observation.code trigger is identical to the serviceRequest.code trigger.

Since the ServiceRequest no longer qualifies for Plan of Treatment section, and is no longer a triggering code, I would expect that the matchedCode 94500-6 with "matchedPath":"ServiceRequest.code" would be replaced by matchedCode 94500-6 with "matchedPath":"Observation.code".

Per engineer: A matchedCode is not comparing whether the Path has changed. The questionable function may be
EcaUtils.hasNewTriggerCodeMatches. As the matching code is currently working it constructs a single list containing both code and values for the original state and the new status and sees if they are the same. Even if the paths were added to that same single list, if you already had something for a given path and the matching codes were just replicated in another path, it would not see that as a difference.

**Comment by ElizHough** [comment]
in dev domain c1941, ptID: 12750995 encID: 97958454

**Comment by nbashyam** [comment]
This has now been fixed as part of the 3/26/2021 baseline.
