### ISSUE TITLE
Replace Special Characters in xml text with escape sequence format 

### ISSUE THREAD

**Issue by ElizHough** [drajer-health/eCRNow#203]
All special characters should be escaped in the eicr XML.
There was invalid XML in the eicr document due to Special Character 'ampersand' not being escaped for the History of Present Illness section narrative. Ampersand is in the json for Condition.code.text
/ClinicalDocument/component/structuredBody/component[8]/section/text/table/tbody/tr[4]/td/content/text()

<content ID="historyOfPresentIllness4">Open fracture of right distal radius. s/p I&D, closed reduction and splinting</content>

Attaching json and xml snippet.
[Escape_SpecChar.zip](https://github.com/drajer-health/eCRNow/files/6197711/Escape_SpecChar.zip)

**Comment by nbashyam** [comment]
This has now been fixed as part of the 3/26/2021 baseline.
