### ISSUE TITLE
FHIR queries do not fetch all the patient data if the subject patient has significant history

### ISSUE THREAD

**Issue by nmeachen** [drajer-health/eCRNow#205]
If the result set for FHIR queries is too large, the response is broken up into multiple chunks, each chunk being retrieved by using the URL specified in the "next" link. As a result eCR is not processing all the patient data and thus not giving the expected results. The queries may need to be refined to limit the scope of the results returned, but eCR should still be prepared to process all data in the searchset chain. This applies to more than just the Observation example below.

{
    "resourceType": "Bundle",
    "id": "03662fa6-6afe-48e5-ad1e-28a1ff3190f0c",
    "type": "searchset",
    "link": [
        {
            "relation": "self",
            "url": "https://fhir-ehr.somewhere.com/r4/something/Observation?patient=123456&category=laboratory"
        },
        {
            "relation": "next",
            "url": "https://fhir-ehr.somewhere.com/r4/something/Observation?patient=123456&category=laboratory&-pageContext=T3BlblBsYXRmb3JtRmhpckNvbnRleHQ9dHJ1ZSZwYWdlQ29udGV4dD04YTliYTIxNC1kY2I4LTRlY2YtOGE4Zi02ZmU5MjMwYWQzNjUmY29uY2VwdD1jaGFydGVkX29ic2VydmF0aW9u&-pageDirection=NEXT"
        }
    ],

**Comment by nbashyam** [comment]
Updated for pagination and the fixes delivered as part of the fixes prior to 4/7/2021.
