### ISSUE TITLE
SvcRequest matchedCode with no Trigger Code Template in POT

### ISSUE THREAD

**Issue by ElizHough** [drajer-health/eCRNow#218]
Duplicated issue for a test patient in c1941.
"encounterId":"97958761", "patientId": "12752275"
Register a patient and enter a Covid Screening order.
CREATE eICR generates for the Covid order
{"patientId":"12752275","encounterId":"97958761","matchTriggerStatus":{"actionId":"match-trigger","jobStatus":"COMPLETED","triggerMatchStatus":true,"matchedCodes":[
{"matchedCodes":["http://loinc.org|94500-6"],"matchedValues":null,"valueSet":"2.16.840.1.113762.1.4.1146.1123","valueSetVersion":"1","matchedPath":"ServiceRequest.code"} ]},"createEicrStatus":{"actionId":"create-eicr","jobStatus":"COMPLETED","eicrCreated":true,"eICRId":"1109"},"

After CREATE runs, cancel the Covid Screening order. In FHIR, serviceRequest.Status = “revoked”
Discharge the patient.
CLOSEOUT generates an eICR without a Trigger Code template and the POT section is nullFlavor=”NI”
{"patientId":"12752275","encounterId":"97958761","matchTriggerStatus":\{"actionId":"match-trigger","jobStatus":"COMPLETED","triggerMatchStatus":true,"matchedCodes":[{"matchedCodes":["http://loinc.org\|94500-6"],"matchedValues":null,"valueSet":"2.16.840.1.113762.1.4.1146.1123","valueSetVersion":"1","matchedPath":"ServiceRequest.code"}]}
,"createEicrStatus":{"actionId":"create-eicr","jobStatus":"COMPLETED","eicrCreated":true,"eICRId":"1109"},"periodicUpdateStatus":[],"periodicUpdateJobStatus":"SCHEDULED","closeOutEicrStatus":{"actionId":"close-out-eicr","jobStatus":"COMPLETED","eicrClosed":true,"eICRId":"1110"},
[eicr1110_ptID12752275_encID97958761.zip](https://github.com/drajer-health/eCRNow/files/6320189/eicr1110_ptID12752275_encID97958761.zip)

**Comment by ElizHough** [comment]
If a Condition, Observation or Service Request, that has previously been logged as a MatchedTrigger code, and is now revoked (or entered-in-error), the code should no longer appear as a matched trigger in the "status" field."

Currently, match trigger  looks for only the triggers codes in the Condition, Observation and ServiceRequest irrespective of their status.

**Comment by nbashyam** [comment]
This should already be fixed in the current baseline, please reopen if the issue exists.
