### ISSUE TITLE
Cancel all scheduled tasks when 404 received on Encounter resource.

### ISSUE THREAD

**Issue by AnanthaKrishnaV** [drajer-health/eCRNow#228]
For Encounters that are cancelled, FHIR will return 404 error. The cancellation scenario is a permanent condition so it does not matter how many times you make that FHIR call, you will always get a 404. Our proposal is to abort all the timers for a patient that gets a ca.uhn.fhir.rest.server.exceptions.ResourceNotFoundException when fetching the Encounter and delete the Launch_details. This should only be for exceptions for Encounters.

**Comment by ElizHough** [comment]
One of the scenarios in which we see the 404 issue is when the encounter is no longer available in the Encounter resource.
- The EHR use case: From the EHR, an encounter can be created and a triggering condition could be entered and a CREATE_eicr occurs. For some reason, the Encounter is cancelled after that initial eICR has been sent.

Are there any code implications if a row exists in the eicr table without a corresponding launch_details (i.e. launch_details.status contains the eicr.id for the CREATE)? The plan is to delete the scheduled_tasks and the launch_details.

**Comment by AnanthaKrishnaV** [comment]
PR fixes this issue #229
