### ISSUE TITLE
Use of Contained Resources within FHIR R4 Resource

### ISSUE THREAD

**Issue by ElizHough** [drajer-health/eCRNow#265]
Does the eCR Now 2.0 or eCR Now 3.0 FHIR app currently support use of Contained Resources within the MedicationRequest? "Contained" resources are part of the standard for referencing other resources. One of our EHR solutions uses "contained" resource within MedicationRequest and we are trying to establish whether the 2.0 FHIR app will support this. Through testing, we verified that the app does not support contained Location within the Encounter Resource.
[ContainedResources.zip](https://github.com/drajer-health/eCRNow/files/7180824/ContainedResources.zip)

**Comment by nbashyam** [comment]
This should be handled already in the current baseline. Please reopen ticket if it is still an issue.
