### ISSUE TITLE
SubmitReport action does not support auth

### ISSUE THREAD

**Issue by dehall** [drajer-health/eCRNow#273]
The SubmitReport action within the BSA currently assumes the submission endpoint will be open and no auth mechanism is provided: https://github.com/drajer-health/eCRNow/blob/24b55b9fad2b1ff21eb9632046677b15f81e60eb/src/main/java/com/drajer/bsa/kar/action/SubmitReport.java#L58
In practice I doubt PHAs are going to want the $process-message endpoint to be completely open with no auth - seems like a big security risk.

Given that the system already supports auth for fetching data from the EHR, it seems like this same logic could be refactored to support submission as well. However there would need to be some kind of data model change to track the auth params (client ID etc), I assume this would be a new table.

The MITRE fork did some refactoring on this, the main changes are to extract some of the FHIR server aspects out of KarProcessingData into a new class that is specific to FHIR servers. If there's interest in seeing how we did that I can submit a PR (with no pressure to merge)

**Comment by nbashyam** [comment]
Authorization to PHAs are supported now as part of the Release3.0 baseline, thanks to the contributions from the MITRE team.
