### ISSUE TITLE
Send athena practice ID in FHIR search queries

### ISSUE THREAD

**Issue by mthrilok** [drajer-health/eCRNow#281]
Hi Dragon,

Each practice in athenaNet has it's own FHIR url as below:
https:athenanet.athenahealth.com/432/52/fhir/r4
https:athenanet.athenahealth.com/1959/52/fhir/r4

We have a FHIR API Router that can route a request to the correct backend FHIR server.
https://api.fhir.athena.io/fhir/r4

When we make search queries to FHIR API Router, we have to pass the ah-practice parameter for the FHIR API Router to identify the correct athena Practice. The athena practice id can be pulled from the athena patientId which is in format a-<PracticeID>.E-<PatientId> or we can pass the practice id to the systemLaunch as parameter and the app can store and use it.

Below subroutines in com.drajer.sof.utils.FhirContextInitializer performs search query based on patient id:
getResourceByPatientId
getObservationByPatientId
getResourceByPatientIdAndCode

As discussed in call (on 18/11/2021) could you take a look on this request and prioritize. Please let us know if there are any queries on this request. Thanks

Regards
Thrilok Nath M
athenahealth

**Comment by mthrilok** [comment]
hi Dragon,

- As discussed during our last call , please find more details on athena practice ID.
- We maintain different database for all practice so our FHIR router url is responsible for routing to the correct practice using the practice id. 

In below examples "**432**" and "**1959**" represents athena practice id . 
https:athenanet.athenahealth.com/432/52/fhir/r4
https:athenanet.athenahealth.com/1959/52/fhir/r4

- At athena we have thousands of practice ids , so we have come up with FHIR router url which will route the request to correct FHIR practice url . Therefore  we need practice id for the FHIR router url to route it correctly. 

**Suggestions to Fix:**

- We can pass the practice id to the systemLaunch as parameter and the app can store and use it.
- In athena practice id can be pulled from the athena patientId which is in format a-<practice_id>.E-<enterprise_id> and then the app can use it to append in the url.
- Below subroutines in com.drajer.sof.utils.FhirContextInitializer performs search query based on patient id needs to be updated:
getResourceByPatientId
getObservationByPatientId
getResourceByPatientIdAndCode
- Current url : <FHIRRouterURL>/resourceName?patient=[patientID]
- Expected  url :<FHIRRouterURL>/resourceName?ah-practice=Organization/a-1.Practice-{practice_Id}&patient={patientID} 
[ Parameter Name= ah-practice , Parameter Value = **Organization/a-1.Practice-** {practice_Id}]
Please let us know if there are any queries , we can set up a quick call and discuss if required. Thanks

**Comment by nbashyam** [comment]
CAn you check if you can use any HTTP header parameters that can be used for the context ?

**Comment by mthrilok** [comment]
We have fixed this from athena side hence closing this one.
