### ISSUE TITLE
Enhance eCRNow App to update ersd files without requiring restart .

### ISSUE THREAD

**Issue by nbashyam** [drajer-health/eCRNow#283]
Currently, the eCRNow app requires a restart to accept changes in ERSD files, which is not desirable in production. An enhancement would be to monitor the ERSD files for changes and when it changes update the ERSD Without restart.

**Comment by medhost-chara** [comment]
@nbashyam checking on priority/anticipated release version?

**Comment by medhost-chara** [comment]
@nbashyam  - If we run multiple allocations for redundancy in a production environment, the in memory load is per instance of running application and does not share pulling from a shared cache correct? Are there plans to implement utilization of redis perhaps for this in the future?

**Comment by nbashyam** [comment]
Chara, you can open a request for Reddis, currently it is not planned.
