### ISSUE TITLE
Bug in checkEncounterClose - Always returning false [addAuthParameters220 branch]

### ISSUE THREAD

**Issue by sathieshkumar** [drajer-health/eCRNow#289]
There are couple of issues with checkEncounterClose that it always return false while checking whether an encounter is closed
1. To get the fhir version from launch_details, the app performs below check:

` if (details.getFhirVersion().equals(FhirVersionEnum.R4)) {`
FhirVersionEnum.R4 is an R4Version object and not a String. So, we have to call toString on R4 to get the fhir version as string. 

2. To identify whether an encounter is closed or not, the app checks the Period field in Encounter FHIR resource. Athena Encounter FHIR result doesn't contain the Period field.(Athena has Period field for Participant in Encounter Resource) However athena result has a status field that gives the encounter status(finished). We have to update the eCRNow app to look the status field for checking encounter close if it could not determine based on encounter end time.

**Comment by nbashyam** [comment]
This has been updated on the addAuthparameters branch.
