### ISSUE TITLE
Store completion status in launch_details table

### ISSUE THREAD

**Issue by sathieshkumar** [drajer-health/eCRNow#293]
For athenaOne, we are planning to stand one instance of the eCRNow app for serving all our clinical practices. With the volume we estimated(250K-300K), the LAUNCH_DETAILS and EICR table could be filled with data over 10M with in a month. To maintain the performance of the app and reduce storage requirement our database, we are planning achieve the processed requests from system_launch table. Currently we don't have any straight forward identifier to indicate that a launch request has completed it's processing. So, we need to add a column in system_launch table say launch_completed and set it when the processing is done.

**Comment by nbashyam** [comment]
Updated on master already.
