### ISSUE TITLE
Store and reuse access token at client level instead of launch level

### ISSUE THREAD

**Issue by sathieshkumar** [drajer-health/eCRNow#294]
athenaOne fhir API access token have expiration time of 1 hr and we will use a single client to communicate with FHIR APIs from the eCRNow app. athenaOne FHIR authentication service has a policy in place which blocks the clients requesting more than 200 tokens per minute. 

Currently the eCRNow app stores and reuse the access token for each launch however we will have same fhir uri, clientid and secret for our system launches. When we make over 200 system launch requests per minute, the client is blocked and all the subsequent token requests are failing. In our production, we expect to make more than 200 requests minute frequently.
 
We encountered this issue while doing some performance test on the app. We have to resolve this with either of the below approaches:

1. Move the access token to Client level as all launches for that client will have same clientid and secret thereby same access token.
2. Implement a caching where we generate access token

**Comment by mthrilok** [comment]
hi @nbashyam -- Could you please review this issue and let us know if you need more details on this . Thanks

**Comment by nbashyam** [comment]
Potential solutions:

1. Implement Access Token Cache for clientIds of a specific type
2. Examine feasibility of storing access token at the client details level.
3.

**Comment by mthrilok** [comment]
hi Dragon,

We use a SaaS product on our end with a hard limit on the number of tokens per minute we could have across all our integrations both internal and external. If we exceed that hard limit, all integrations will start failing until the limit gets reset at the next minute boundary. IP whitelisting and having a higher limit for this integration is not a solution.

Thanks

**Comment by nbashyam** [comment]
Updated on AddAuthParameters branch.

**Comment by nbashyam** [comment]
This has been updated and pushed to addAuthParameters branch on Release 2 and as part of the Release3.0 baseline.
