### ISSUE TITLE
Store data in location object of R4FHIRDATA along with location arraylist

### ISSUE THREAD

**Issue by gshivika** [drajer-health/eCRNow#300]
There is prepareJurisdicationData method to populate the address where the encounter took place in R4FhirData.java 
 It checks the address in location object of R4FhirData class , this object is never populated, instead the location FHIR call only add the data in arraylist locationList in class R4ResourcesData.java.
 
 The code in method getCommonResources of class R4ResourcesData needs to be updated to store the data from location FHIR call in the location object of R4FhirData pojo along with storing in arraylist locationList of R4FhirData.

**Comment by mthrilok** [comment]
Hi Dragon,

Could you please prioritize this request and do the fix as required.
We are planning for integration and load testing and it would be great if this issue is fixed by 18-Feb-2022  .
Thanks

**Comment by nbashyam** [comment]
Updated on addAuthParameters branch.

**Comment by nbashyam** [comment]
This has been fixed in the master, addAuthParameters and the Release3.0 baseline.
