### ISSUE TITLE
Move access token logging from info to debug level

### ISSUE THREAD

**Issue by characode** [drajer-health/eCRNow#303]
Please modify logging level for access token from info to debug level for security
https://github.com/drajer-health/eCRNow/blob/master/src/main/java/com/drajer/sof/launch/LaunchController.java#L384

**Comment by characode** [comment]
Additional locations of access token logging:

https://github.com/drajer-health/eCRNow/blob/Release-3.0/src/main/java/com/drajer/bsa/auth/impl/AuthorizationServiceImpl.java#L45 

https://github.com/drajer-health/eCRNow/blob/Release-3.0/src/main/java/com/drajer/bsa/auth/impl/AuthorizationServiceImpl.java#L84

Can these be moved to debug level?

**Comment by nbashyam** [comment]
Fixed with commit - https://github.com/drajer-health/eCRNow/commit/ee173a5b6b55070b13d280118bcb2953a1d34a90
