### ISSUE TITLE
Ecrnow Startup Performance

### ISSUE THREAD

**Issue by rtomas-pinc** [drajer-health/eCRNow#306]
The application takes 5-10 minutes to start when reading the ERSD file and processing the plan definitions.  Seems to be with the openSession in ValueSetDao.  Current workaround in place and now only takes 15 seconds to start. 

ECRNow possible performance issueApplication Startup is slow during Plan definition (takes about 5-10 minutes to process the ERSD file)Code is opening a session for each valueSet / ValueGroup / PlanDefinitionThis is currently not needed since you are not actually saving it.After the fix the startup is only 15 seconds and the Definitions still seem to be intact.

Please Validate.

**Comment by rtomas-pinc** [comment]
Date of ERSD (not sure this really applies to this issue) -- "lastUpdated": "2021-09-22T13:00:01.266+00:00"

**Comment by nbashyam** [comment]
Can you please revalidate this and let us know if you are seeing this behavior. We are not experiencing this based on all the vendor feedback received. Please re-open issue if this is still happening.
