### ISSUE TITLE
MedicationAdmin without a Medication Request does not trigger

### ISSUE THREAD

**Issue by rtomas-pinc** [drajer-health/eCRNow#308]
1. Patient with MedicationAdmin, but no MedicationRequest
a. Expected it to trigger an EICR, but code seems to override it.
i. R4ResourcesData.java, line 657, r4FhirData.setR4MedicationCodes(medicationCodes);
ii. Same for ResourceStatement, line 732
iii. Please advise if this is acceptable or provide fix to master,        r4FhirData.getR4MedicationCodes().addAll(medicationCodes

Please validate

**Comment by rtomas-pinc** [comment]
Date of ERSD --> "lastUpdated": "2021-09-22T13:00:01.266+00:00"

This was tested with master (2.0) code line.  In the process of testing with Release 3.0

**Comment by nbashyam** [comment]
Randy,
Please open a new ticket if this is still an issue on Release 3.0. These should be working on the current baseline.
