### ISSUE TITLE
Release 3.0 Exception during load if the ERSD file location for version 2 is not defined

### ISSUE THREAD

**Issue by characode** [drajer-health/eCRNow#312]
When using version 3.0 without defining version 2.0 0 exception is thrown. Can the application only attempt to load the file if the property is defined and accordingly just log?

`2022-02-24 00:44:04.788 ERROR 90039 --- [           main] c.d.e.service.PlanDefinitionProcessor    : Exception Reading ERSD File

java.io.FileNotFoundException:  (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)`

**Comment by nbashyam** [comment]
Fixed with commit
https://github.com/drajer-health/eCRNow/commit/d2354be383bd67ebca4a9a6189bc679bb778c1a4
