### ISSUE TITLE
503 errors under load

### ISSUE THREAD

**Issue by zeevalor** [drajer-health/eCRNow#313]
We had a client do batch processing of ADT's (798). We run 6 instances with 8 threads each. We saw 500+ 503 errors when we try the /systemLaunch end point. We do have a retry built in the call so the 500+ 503 errors maynot be distinct requests.
Girish

**Comment by nbashyam** [comment]
Is this still an issue, we have not heard of this issue in many of the performance and loading tests conducted.
Please open a specific issue with more details if this is happening with steps on how to best recreate the scenario.
