### ISSUE TITLE
Release 3.0 healthcare settings api returning Both as outputFormat even if defined as CDA_R11

### ISSUE THREAD

**Issue by characode** [drajer-health/eCRNow#314]
Both api/healthcareSettings?url= and api/healthcareSettings/:hsid return kars artifactstatus output as Both 

Create healthcare setting with 
`      "kars": {
        "artifactStatus": [
            {
                "karId": "bundle-ersd-specification-bundle",
                "karVersion": "2",
                "versionUniqueKarId": "bundle-ersd-specification-bundle|2",
                "isActive": true,
                "lastActivationDate": "2022-02-21T20:34:40.343+00:00",
                "lastInActivationDate": "2022-02-21T20:34:40.343+00:00",
                "subscriptionsEnabled": false,
                "subscriptions": "",
                "covidOnly": null,
                "outputFormat": "CDA_R11"
            }
        ]
    }
`

Calling endpoint to get the healthcare setting returns output format as Both
`  
   "kars": {
        "artifactStatus": [
            {
                "id": null,
                "hsId": null,
                "karId": "bundle-ersd-specification-bundle",
                "karVersion": "2",
                "versionUniqueKarId": "bundle-ersd-specification-bundle|2",
                "isActive": true,
                "lastActivationDate": "2022-03-04T15:20:42.314+00:00",
                "lastInActivationDate": "2022-03-04T15:20:42.314+00:00",
                "subscriptionsEnabled": false,
                "subscriptions": "",
                "covidOnly": null,
                "outputFormat": "Both"
            }
        ],
        "id": 74
    }
`

**Comment by nbashyam** [comment]
Fixed with commit 
https://github.com/drajer-health/eCRNow/commit/d2354be383bd67ebca4a9a6189bc679bb778c1a4
