### ISSUE TITLE
Adjust Line 44 of DSTU2 data spreadsheet

### ISSUE THREAD

**Issue by nviator** [drajer-health/eCRNow#326]
Dragon -

Reminding you to please fix line 44 of the DSTRU spreadsheet (https://github.com/drajer-health/eCRNow/blob/master/documents/eCR_R1.1_FHIR_Mapping_dstu2_v2.xlsx) - re: History of Present Illness.

**Comment by nbashyam** [comment]
The spreadsheets have been baselined, no new actions required.

**Comment by VenkatSaiReddyTeegala** [comment]
Resolved as part of 3.1.4
