### ISSUE TITLE
Socket connections not getting closed

### ISSUE THREAD

**Issue by gshivika** [drajer-health/eCRNow#328]
We are seeing following exceptions when hitting more than 20k system launch requests in a day :-
1. com.sun.jersey.api.client.ClientHandlerException: java.net.SocketException: Too many open files
2. Caused by: java.net.SocketException: Too many open files
3. java.io.IOException: Too many open files

When investigated further we found out that during the FHIR client or Rest Template calls lot of socket connections are left open and not closed due to which they are getting stuck in CLOSE_WAIT state.
This is stopping new system launch requests to be processed and our servers are getting read_timeouts.

Reference we found in google of what could be the reason :- https://blog.cloudflare.com/this-is-strictly-a-violation-of-the-tcp-specification/

**Comment by mthrilok** [comment]
hi Dragon, 

As discussed in call yesterday we have attached the stack trace details above for your reference. 
Also we want to apply additional filters to the FHIR APIs to avoid these socket exceptions. 

Please find the list of FHIR APIs to which we support additional filters with encounter id . 

HIR:search:/fhir/r4/ServiceRequest:
- Suuports filter by encounter id.
- Search condition to add: **encounter=<encounter-id>**

FHIR:search:/fhir/r4/Condition:
- Suuports filter by encounter id.
- Search condition to add: **encounter=<encounter-id>**

FHIR:search:/fhir/r4/MedicationRequest:
- Suuports filter by encounter id.
- Search condition to add: **encounter=<encounter-id>**

FHIR:search:/fhir/r4/DiagnosticReport:
- Suuports filter by encounter id.
- Search condition to add: **encounter=<encounter-id>**

FHIR:search:/fhir/r4/Immunization:
- Suuports filter by encounter id.
- Search condition to add: **encounter=<encounter-id>**

FHIR:search:/fhir/r4/Observation:
- Supports date based filter.
- Search condition to add: **date=ge<encounter-start-date>**

Note: For observation API alone we need to send the encounter start date.

Could you please review this information and provide us the custom query ersd file along with the latest 3.0 release version which supports custom queries.

**Comment by nbashyam** [comment]
Thrilok, I believe this issue is not happening anymore based on the latest baseline and socket pooling implemented.Please reopen issue if it is happening.
