### ISSUE TITLE
eCR CCDA Problems section narrative sometimes has unknown problem name

### ISSUE THREAD

**Issue by Torin-Shepard-athena** [drajer-health/eCRNow#341]
In eCR CCDA Problems section narrative, there sometimes is unknown for the problem name.
/eCRNow/src/main/java/com/drajer/cdafromr4/CdaProblemGenerator.java
generateProblemSection method logic to add body rows to problem section narrative
Change FROM: First Condition.code.coding.display
Change TO: Condition.code.text

**Comment by nbashyam** [comment]
This should be currently fixed in the latest baseline.
