### ISSUE TITLE
Incorrect logic for Patient deceasedBoolean values to generate CDA Header

### ISSUE THREAD

**Issue by Torin-Shepard-athena** [drajer-health/eCRNow#342]
eCR Now has incorrect logic for Patient deceasedBoolean values to generate CDA Header.
This may be related to #183
Change FROM: Assume presence of Patient.deceased[x] indicates deceased patient
Change TO: Use both Patient.deceasedBoolean and Patient.deceasedDateTime to generate proper deceasedInd and deceasedTime elements in CDA Header.

**Comment by nviator** [comment]
@nbashyam  - re: planning conversation on 1/9/2023, please indicate anticipate spring/release. Thank you! (Admin note: #183 #429  and #342 appear to be same issue.)

**Comment by nbashyam** [comment]
As long as FHIR R4 is being used, this issue is fixed.
