### ISSUE TITLE
Missing support for MedicationStatement.effectivePeriod

### ISSUE THREAD

**Issue by Torin-Shepard-athena** [drajer-health/eCRNow#343]
AIMS eCR validator gives medication effective time error
Change FROM: Use MedicationStatement.effectiveTime and MedicationAdministration.effectiveTime
Change TO: Use MedicationStatement.effectivePeriod and MedicationAdministration.effectivePeriod
/eCRNow/src/main/java/com/drajer/cdafromr4/CdaMedicationGenerator.java

**Comment by nbashyam** [comment]
Please retest after 3.1.5
