### ISSUE TITLE
eCR CCDA Medications section narrative often has unknown for medication name

### ISSUE THREAD

**Issue by Torin-Shepard-athena** [drajer-health/eCRNow#345]
eCR Now supports only FHIR contained references but athenaPractice/athenaFlow and some other FHIR Servers support only relative references.
http://hl7.org/fhir/R4/references.html#contained
eCR Now getStringForMedicationType must be changed to support relative references if contained reference is not found.

This may be related to #265

**Comment by nbashyam** [comment]
This should already be fixed in the current baseline, please reopen ticket if it is still an issue.
