### ISSUE TITLE
null pointer exception when calling getValueSetsAsStringForGrouper from the ValueSetSingleton.java class

### ISSUE THREAD

**Issue by AGABB** [drajer-health/eCRNow#356]
**Creating Issue based on input received from a representative from Flatiron Health. Copied directly below.**

When testing the eCR app, we've found that when a condition resource has a codeable concept code, the app runs into a null pointer exception when calling the getValueSetsAsStringForGrouper function in the ValueSetSingleton.java class.
This line of code returns a Set of size 1, but all elements are null: Set<ValueSet> grouperValueSet = getTriggerPathToGrouperMap().get(path);

Which ultimately leads down this code path where g is a null object and calling g.getId() throws the exception:
_if (grouperValueSet != null) {
for (ValueSet g : grouperValueSet) {
grouperId = g.getId();_

Not sure if this is something that needs fixing with a code update or it's an app setting that we missed and need to update locally. 
Any help is appreciated!

**Comment by nviator** [comment]
Conversation on this item still persists on Zulip: https://chat.fhir.org/#narrow/stream/236764-eCR-Now-FHIR-App/topic/NullPointerException.20in.20getValueSetsAsStringForGrouper

GitHub Issue: https://github.com/drajer-health/eCRNow/issues/356
