### ISSUE TITLE
Missing Author and AuthorID in initial eICR message from FHIR App

### ISSUE THREAD

**Issue by AGABB** [drajer-health/eCRNow#357]
After reviewing several source eICRs generated from the ECR Now FHIR App it has been observed that Author and AuthorID are not present in their expected locations:

**Author**
//ClinicalDocument/author/assignedAuthor/representedOrganization/name

**AuthorID**
//ClinicalDocument/author/assignedAuthor/representedOrganization/id

At least one public health agency has indicated that they use these fields to identify the HCO that is sending the message.

**Comment by AGABB** [comment]
Hello - 
Requesting an update on this issue. Is the observed behavior expected?

Please let me know if additional information is needed to investigate. Thanks!

**Comment by nbashyam** [comment]
Authors are always populated in the eICR based on the baseline that is being used in TEST And prod by many vendors. we dont believe there is an issue, please let us know if there are any other specifics by opening a new ticket.
