### ISSUE TITLE
eCRNOW2.0: RRObtianed is set to true by default even though RR is received

### ISSUE THREAD

**Issue by AnanthaKrishnaV** [drajer-health/eCRNow#358]
RRObtained is set to true by default[1].

[1] - https://github.com/drajer-health/eCRNow/blob/master/src/main/java/com/drajer/eca/model/ReportabilityResponseAction.java#L96

{"severity":"INFO","logger":"com.drajer.eca.model.ReportabilityResponseAction","time":"1655154848.776","thread":"db-scheduler-pool-4-thread-6","message":"Executing RR Check Eicr Action , Prior Execution State : = {\"patientId\":\"37744407\",\"encounterId\":\"60515678\",\"matchTriggerStatus\":{\"actionId\":\"match-trigger\",\"jobStatus\":\"COMPLETED\",\"triggerMatchStatus\":true,\"matchedCodes\":[{\"matchedCodes\":[\[http://hl7.org/fhir/sid/icd-10-cm|U07.1\](https://nam10.safelinks.protection.outlook.com/?url=http%3A%2F%2Fhl7.org%2Ffhir%2Fsid%2Ficd-10-cm%257CU07.1%2F&data=05%7C01%7CAnantha.Venkatachalaiah%40Cerner.com%7C48f134b404e14d7d1fce08da4e296d0e%7Cfbc493a80d244454a815f4ca58e8c09d%7C0%7C0%7C637908237079347808%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=dVxw2836siHKKaQHZvPvGQfNiBzkKHbQ%2FCyGioQAtuk%3D&reserved=0),\[http://snomed.info/sct|1119302008\](https://nam10.safelinks.protection.outlook.com/?url=http%3A%2F%2Fsnomed.info%2Fsct%257C1119302008%2F&data=05%7C01%7CAnantha.Venkatachalaiah%40Cerner.com%7C48f134b404e14d7d1fce08da4e296d0e%7Cfbc493a80d244454a815f4ca58e8c09d%7C0%7C0%7C637908237079347808%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=K5T0%2FO0Rq7CyLeFM4XAbDmAx8IgI9Nfm7N5px7bIyIY%3D&reserved=0)],\"matchedValues\":null,\"valueSet\":\"2.16.840.1.113762.1.4.1146.1123\",\"valueSetVersion\":\"1\",\"matchedPath\":\"Condition.code\"}]},\"createEicrStatus\":{\"actionId\":\"create-eicr\",\"jobStatus\":\"COMPLETED\",\"eicrCreated\":true,\"eICRId\":\"3898\"},\"periodicUpdateStatus\":[],\"periodicUpdateJobStatus\":\"SCHEDULED\",\"closeOutEicrStatus\":{\"actionId\":\"\",\"jobStatus\":\"NOT_STARTED\",\"eicrClosed\":false,\"eICRId\":\"\"},\"validateEicrStatus\":[{\"actionId\":\"validate-eicr\",\"jobStatus\":\"COMPLETED\",\"eicrValidated\":true,\"eICRId\":\"3898\",\"validationTime\":1655154731293}],\"submitEicrStatus\":[{\"actionId\":\"route-and-send-eicr\",\"jobStatus\":\"COMPLETED\",\"eicrSubmitted\":true,\"eICRId\":\"3898\",\"submittedTime\":1655154731474,\"transportUsed\":null}],\"rrStatus\":[{\"actionId\":\"3dd1c21e-2389-47d1-acda-673ba9c582ad\",\"jobStatus\":\"COMPLETED\",\**"rrObtained\":true,**\"eICRId\":\"3898\",\"rrTime\":1655154731506,\"transportUsed\":null}],\"eicrsReadyForSubmission\":[],\"eicrsForRRCheck\":[],\"eicrsReadyForValidation\":[]}","properties":{"domain-logicalDomainId":"m152w.uhs_pa.cernerasp.com-0","oauth.identifier":"435b5ba3-09ca-41ab-becb-2244f5f23b12","oauth.consumerKey":"435b5ba3-09ca-41ab-becb-2244f5f23b12","requestId":"aa3df4ab-5770-4290-b38c-74518e109158"}}

**Comment by nbashyam** [comment]
Anantha, we are assuming that you have addressed this in your version of the software and there is nothing we need to do currently.

**Comment by nbashyam** [comment]
Closing with the above assumption, please open a new ticket if something needs to be changed.
