### ISSUE TITLE
no dischargeDisposition in eICR generated from FHIR App

### ISSUE THREAD

**Issue by sopatidar** [drajer-health/eCRNow#360]
No inclusion of dischargeDisposition as requested in test scenario 2
Per Premier Inc.  DischargeDisposition FHIR system was fixed, but still not showing in EICR.

This issue was communicated via meeting with Premier Inc. and the Onboarding team on 7/6/22. It can also be found over follow up email after the meeting on 7/6/22.

**Comment by nviator** [comment]
Admin note: This will be communicated to PHAs as a "known issue" with respects to Premier Inc TheraDoc HCO eCR implementations.

**Comment by nbashyam** [comment]
This has been resolved and the fix is available in the latest baseline.

**Comment by nbashyam** [comment]
Add US Core DischargeDisposition also to the code system.

**Comment by nviator** [comment]
@nbashyam - was this checked in?
If not, bumping issue for consideration in an upcoming eCR Now FHIR App development sprint.

**Comment by nbashyam** [comment]
The code system OIDs and URLs have been updated to use the ones per FHIR. Please re-test and let us know if this is still an issue.
