### ISSUE TITLE
Diagnosis value of <value xsi:type="CD" nullFlavor="OTH">

### ISSUE THREAD

**Issue by sopatidar** [drajer-health/eCRNow#361]
Scenario 1 - Diagnosis value of < value xsi:type="CD" nullFlavor="OTH" >
Why is this nullFlavor? RCKMS will read the code in the translation to match, but the translation is an ICD code as expected to see in the value element

This issue was communicated via meeting with Premier Inc. and the Onboarding team on 7/6/22. It can also be found over follow up email after the meeting on 7/6/22.

**Comment by nbashyam** [comment]
This will be addressed as a low priority item as it does not impact RCKMS or the vendors for now.

**Comment by nviator** [comment]
Within encounter diagnosis section (NVC notes from 9/19 FHIR App team call).

**Comment by nbashyam** [comment]
Please retest with 3.1.5 baseline.
