### ISSUE TITLE
Issue: systemLaunch API responds with mixed object types

### ISSUE THREAD

**Issue by martha-garasky** [drajer-health/eCRNow#369]
When erroring - the app responds with a json object.  When successful - the app responds with a string.
The response should be consistent in what object type is responds with.

LaunchController.java > invokeSystemLaunch

Examples:
_Response for an issue/error_
```
{    
  "timestamp": "2022-08-12T18:50:33.398+00:00",
  "status": 405,
  "error": "Method Not Allowed",
  "message": "",
  "path": "/api/systemlaunch"
}
```
_Response when successful_
`App is launched successfully`

**Comment by nbashyam** [comment]
Fixed to provide OperationOutcome always.
