### ISSUE TITLE
Issue: Phone Number – The phone number in the EICR is getting mis-formatted.

### ISSUE THREAD

**Issue by sopatidar** [drajer-health/eCRNow#374]
Observed by athenaClinicals team.

Phone Number – The phone number in the EICR is getting mis-formatted.

Here is what it looks like in the EICR:
< telecom value=tel:(555)-55-5-20/ >
< telecom value=tel:(555)-55-5-20/ >
 
Here is what it looks like in the resource: 
  "telecom": [ {
        "system": "phone",
        "value": "555-555-5006",
        "use": "home"
      }, {
        "system": "phone",
        "value": "555-555-5006",
        "use": "mobile"

**Comment by AnanthaKrishnaV** [comment]
Fixed with PR #378
