### ISSUE TITLE
MedicationRequest needs 'intent' parameter along with 'patient' parameter

### ISSUE THREAD

**Issue by martha-garasky** [drajer-health/eCRNow#381]
Per the hl7.fhir.us.core requirements a MedicationRequest request with just the 'patient' parameter is not a valid request; a MedicationRequest request also requires an 'intent' parameter along with the 'patient' parameter.

[http://hl7.org/fhir/us/core/STU5.0.1/StructureDefinition-us-core-medicationrequest.html#mandatory-search-parameters](http://hl7.org/fhir/us/core/STU5.0.1/StructureDefinition-us-core-medicationrequest.html#mandatory-search-parameters)

**Comment by nbashyam** [comment]
This is fixed in the latest ERSD released in August 2023 on ERSD version 1.2.0.0 
This is also supported via custom-queries.
