### ISSUE TITLE
How can integrate launch type : "Launch App-Standlone Launch"

### ISSUE THREAD

**Issue by vasupujy** [drajer-health/eCRNow#382]
Hello Everyone
Greetings for the day
We are implementing launch type "Launch Type:Standlone Launch" using "api/systemlaunch"
But getting 400 error unauthorised.

Anyone have any idea about this?

Thanks in advance
Vasupujy Patel

**Comment by nbashyam** [comment]
Is this still an issue ?

**Comment by nbashyam** [comment]
This is not supported by the eCRNow App and is not intended to be supported in teh future either.
