### ISSUE TITLE
eCRNOW-V3.0: Kars_active column on healthcare_settings table will have all Kars active irrespective of hs_kar_status data.

### ISSUE THREAD

**Issue by AnanthaKrishnaV** [drajer-health/eCRNow#383]
Kars_active column on healthcare_settings table will have all Kars active irrespective of hs_kar_status data.

**Comment by nbashyam** [comment]
Fixed with commit
https://github.com/drajer-health/eCRNow/commit/d2354be383bd67ebca4a9a6189bc679bb778c1a4
