### ISSUE TITLE
eCRNOW-V3.0: Duplicate patient launch is added in notification_context table

### ISSUE THREAD

**Issue by AnanthaKrishnaV** [drajer-health/eCRNow#384]
Duplicate patient launch is added in notification_context table
![image](https://user-images.githubusercontent.com/28885907/192799256-bb0a425a-5392-4ea3-b4be-e3d88bc08cd2.png)

**Comment by Pramodshetty08** [comment]
Hi Drajer, This duplicate issue is still open with the latest code (date of testing 01/10/2023)

**Comment by Pramodshetty04** [comment]
discussion dated 06/05/2023, drajer will add a check in the db to avoid multiple launch API calls.
@nbashyam

**Comment by nbashyam** [comment]
Fixed in an earlier baseline.
