### ISSUE TITLE
eCRNOW-V3.0: With off-hours set, timers are scheduled to past hours. 

### ISSUE THREAD

**Issue by AnanthaKrishnaV** [drajer-health/eCRNow#385]
eCRNOW-V3.0: With off-hours set, timers are scheduled to past hours. 

![image](https://user-images.githubusercontent.com/28885907/192799505-2be343a2-5e68-41c9-9a0e-72e30daf4347.png)

**Comment by nbashyam** [comment]
This has been fixed with the latest baseline.
