### ISSUE TITLE
Immunizations without matching encounter reference fail to hit logical block using start and end dates

### ISSUE THREAD

**Issue by characode** [drajer-health/eCRNow#389]
The comments seem to indicate that if the immunization does not have an encounter reference that it should be filtered based on dates however in the case that the encounter reference is not present on the immunization, it is imbedded within logic block and never hits the next else statement:
`      } else {
        for (BundleEntryComponent entry : bundle.getEntry()) {`

`  public List<Immunization> getImmunizationData(
      FhirContext context,
      IGenericClient client,
      LaunchDetails launchDetails,
      R4FhirData r4FhirData,
      Encounter encounter,
      Date start,
      Date end) {
    logger.trace("Get Immunization Data");
    Bundle bundle =
        (Bundle)
            resourceData.getResourceByPatientId(launchDetails, client, context, "Immunization");
    List<Immunization> immunizations = new ArrayList<>();
    List<CodeableConcept> immunizationCodes = new ArrayList<>();
    if (bundle != null && bundle.getEntry() != null) {
      // Filter Immunizations based on Encounter Reference
      if (encounter != null && !encounter.getIdElement().getValue().isEmpty()) {
        for (BundleEntryComponent entry : bundle.getEntry()) {
          Immunization immunization = (Immunization) entry.getResource();
          if (!immunization.getEncounter().isEmpty()
              && immunization
                  .getEncounter()
                  .getReferenceElement()
                  .getIdPart()
                  .equals(encounter.getIdElement().getIdPart())) {
            immunizations.add(immunization);
            immunizationCodes.addAll(findImmunizationCodes(immunization));
          }
        }
        // If Encounter Id is not present using start and end dates to filter
        // Immunizations
      } else {
        for (BundleEntryComponent entry : bundle.getEntry()) {
          Immunization immunization = (Immunization) entry.getResource();
          // Checking If Immunization DateTime is present in Immunization
          // resource
          if (immunization.getOccurrence().isDateTime()
              && immunization.getOccurrenceDateTimeType() != null) {
            if (isResourceWithinDateTime(
                start, end, immunization.getOccurrenceDateTimeType().dateTimeValue().getValue())) {
              immunizations.add(immunization);
              immunizationCodes.addAll(findImmunizationCodes(immunization));
            }
          }
          // If Immunization Date is not present looking for LastUpdatedDate
          else {
            Date lastUpdatedDateTime = immunization.getMeta().getLastUpdated();
            if (isResourceWithinDateTime(start, end, lastUpdatedDateTime)) {
              immunizations.add(immunization);
              immunizationCodes.addAll(findImmunizationCodes(immunization));
            }
          }
        }
      }
      r4FhirData.setR4ImmunizationCodes(immunizationCodes);
    }
    logger.info("Filtered Immunizations -----------> {}", immunizations.size());
    return immunizations;
  }`

**Comment by nbashyam** [comment]
Fixed with commit 
https://github.com/drajer-health/eCRNow/commit/d2354be383bd67ebca4a9a6189bc679bb778c1a4
