### ISSUE TITLE
Observation Code Issue

### ISSUE THREAD

**Issue by mthrilok** [drajer-health/eCRNow#392]
As discussed today , we have looked at our Observation resource code. We are populating the “code” attribute with a LOINC code if we receive one from the lab. However, if we do not receive a LOINC code, we are populating the code.text with the name of the analyte that we receive from the lab. We can’t leave this attribute blank as the FHIR spec the observation.code is Mandatory.

I think this needs to be handled on the ECR code . Please review and let us know. Thanks

**Comment by nbashyam** [comment]
This has been fixed with the latest baseline.
