### ISSUE TITLE
HealthCareFacility Location Telecom is missing

### ISSUE THREAD

**Issue by rtomas-pinc** [drajer-health/eCRNow#398]
Location.telecom is missing during EICR.  The serviceProviderOrganization has it.        

 
If you compare getLocationXml vs getOrganizationXml, you will see the first one doesn’t have this line, thus no telecom for location.
 
Line 612
sb.append(
    CdaGeneratorUtils.getXmlForStartElement(CdaGeneratorConstants.HEALTHCARE_FACILITY_EL_NAME));

sb.append(getLocationXml(data.getLocation(), data.getOrganization(), details));

sb.append(
    CdaGeneratorUtils.getXmlForStartElement(
        CdaGeneratorConstants.SERVICE_PROVIDER_ORG_EL_NAME));

sb.append(getOrganizationXml(data.getOrganization(), details, false));
 
here are those sections
 
getLocationXml (missing the getTelecomXml row)
addrs.add(loc.getAddress());
sb.append(CdaFhirUtilities.getAddressXml(addrs));
sb.append(CdaGeneratorUtils.getXmlForEndElement(CdaGeneratorConstants.LOCATION_EL_NAME));
 
 
getOrganizationXml
sb.append(CdaGeneratorUtils.getXmlForText(CdaGeneratorConstants.NAME_EL_NAME, org.getName()));
sb.append(CdaFhirUtilities.getTelecomXml(org.getTelecom(), onlyOneTelecom));
sb.append(CdaFhirUtilities.getAddressXml(org.getAddress()));

**Comment by nbashyam** [comment]
This is not there as per the CDA eICR R11 IG, hence it is not present in the code.
