### ISSUE TITLE
Encounter status in notification_context table is not closed

### ISSUE THREAD

**Issue by mthrilok** [drajer-health/eCRNow#401]
Encounter status is not updated in the notification_context table  for long pending encounters . According to ersd definition the app should update the status in notification_context table as "COMPLETED" , but this is not happening with the current code . Also we have seen encounters that are 1 month old for which the app is rescheduling the tasks everyday.

This is related to long pending encounters which are open for more than 7 days.

**Comment by nbashyam** [comment]
Resolved with commit : 
https://github.com/drajer-health/eCRNow/commit/ba3ef9119e4c2f16c8688aa0c7f0176c6fbbf7f5
