### ISSUE TITLE
App is not considering the encounter end time and status 

### ISSUE THREAD

**Issue by mthrilok** [drajer-health/eCRNow#405]
For an encounter in the initial launch request if there is no data received for end date / status then in subsequent reschedules the app is not considering this data from encounter resource even though the data is available. 

We observed that in these cases app is having logic to populate the  new encounter start date  (which is less than 7 days) . But when it received the end time and status in encounter FHIR API it will save them in table  but still it is scheduling the tasks(check reportable) for the same encounter.

**Comment by nbashyam** [comment]
Resolved with the commit https://github.com/drajer-health/eCRNow/commit/ba3ef9119e4c2f16c8688aa0c7f0176c6fbbf7f5
