### ISSUE TITLE
Check Reportable tasks being scheduled during Business Hours

### ISSUE THREAD

**Issue by mthrilok** [drajer-health/eCRNow#407]
As per our observation in Production we have seen that "Check Reportable tasks being scheduled during Business Hours" . We will be sharing logs for these examples in email . Could you please review this request and let us know if you need any other details.

**Comment by nbashyam** [comment]
This has been resolved with commit
https://github.com/drajer-health/eCRNow/commit/e080727e10dcd17b256de4c4303af3d8323b842f
