### ISSUE TITLE
Ability to customize eCRNow for optional unsupported resources in FHIR server capability statement

### ISSUE THREAD

**Issue by kmarx** [drajer-health/eCRNow#408]
Our FHIR server's capability statement doesn't include `MedicationDispense` or `Bundle`. eCRNow doesn't mind, but we get a lot of false exceptions in our logs for these resource requests.

We can hack the ERSD file, but then we're out of sync with AIMS updates and would have to constantly re-edit our customizations.

It would be nice if eCRNow could allow us to explicitly exclude unsupported resources that aren't required.

**Comment by nbashyam** [comment]
We have updated the custom-queries capability to address this. If it is left blank in the cutom-query it will not be executed.
