### ISSUE TITLE
AIMS eICR validation error on encompassingEncounter.location.healthCareFacility.code

### ISSUE THREAD

**Issue by kmarx** [drajer-health/eCRNow#409]
Our EHR emits a `Location` resource with `Location.type[0].coding[0].code`=`ONCL` and `Location.type[0].coding[0].system` of either 

```
urn:oid:2.16.840.1.113883.1.11.17660
``` 
or
```
urn:oid:2.16.840.1.113883.5.111
```
The resulting eICR has `encompassingEncounter.location.healthCareFacility.code` of `<code nullFlavor="NI"/>` which results in an error in the AIMS validator.

Our workaround (provided by Dragon) is to use a system URI of http://terminology.hl7.org/CodeSystem/v3-RoleCode instead of an OID. But he also says the OID (`2.16.840.1.113883.5.111` is the correct one) should work.

**Comment by kmarx** [comment]
[LoadingQueryBundle_22D51767B45B4C34B9FEE2E988375BFE_Appointment.5F9ED41E76064B06B907F86BF20E26D3.json.zip](https://github.com/drajer-health/eCRNow/files/10078813/LoadingQueryBundle_22D51767B45B4C34B9FEE2E988375BFE_Appointment.5F9ED41E76064B06B907F86BF20E26D3.json.zip)

**Comment by nbashyam** [comment]
Fixed with commit 
https://github.com/drajer-health/eCRNow/commit/d2354be383bd67ebca4a9a6189bc679bb778c1a4
