### ISSUE TITLE
NPE for null occurrence date in CdaImmunizationGenerator.generateImmunizationSection

### ISSUE THREAD

**Issue by kmarx** [drajer-health/eCRNow#412]
`java.lang.NullPointerException: Cannot invoke "java.util.Date.toString()" because the return value of "org.hl7.fhir.r4.model.DateTimeType.getValue()" is null
	at com.drajer.cdafromr4.CdaImmunizationGenerator.generateImmunizationSection(CdaImmunizationGenerator.java:86)
	at com.drajer.cdafromr4.CdaBodyGenerator.generateCdaBody(CdaBodyGenerator.java:39)
	at....`

Currently:
`        if (imm.getOccurrenceDateTimeType() != null) {
          dt = imm.getOccurrenceDateTimeType().getValue().toString();
        }`

Add NPE protection:
`        if (imm.hasOccurrenceDateTimeType() && imm.getOccurrenceDateTimeType() != null) {
          dt = imm.getOccurrenceDateTimeType().getValue().toString();
        }`

**Comment by nbashyam** [comment]
Resolved with commit : 
https://github.com/drajer-health/eCRNow/commit/ba3ef9119e4c2f16c8688aa0c7f0176c6fbbf7f5
