### ISSUE TITLE
Marital status not included in eICR despite being present in patient.maritalStatus in Trigger Query

### ISSUE THREAD

**Issue by AGABB** [drajer-health/eCRNow#416]
Logging issue that came up during Evident's Scenario based testing. Marital status is a required field in scenario and it is not showing in the XML output from the FHIR App. 

This is what is included in the Trigger Query:
<img width="313" alt="image" src="https://user-images.githubusercontent.com/107709349/206226012-640c457e-34b8-4972-959c-577d729940f4.png">

**Comment by nviator** [comment]
@nbashyam - was this checked in? 
If not, bumping issue for consideration in an upcoming eCR Now FHIR App development sprint.

**Comment by nbashyam** [comment]
Fixed with the above commit.
