### ISSUE TITLE
eCRNow-UI Kar listing incorrectly displays contents of the Kar subduers

### ISSUE THREAD

**Issue by kmarx** [drajer-health/eCRNow#417]
- Kar.directory root is empty
- Kar.directory has one subdirectory, xxx, with kar json file(s) (ersd)
- UI shows kar files as being in the kar root and the xxx subdirectory as being empty

**Comment by nbashyam** [comment]
Is this still an issue, because it looks like it is working properly. Please reopen if it is still an issue.
