### ISSUE TITLE
Add version number to Kar file listing

### ISSUE THREAD

**Issue by kmarx** [drajer-health/eCRNow#418]
![karfile-no-version-in-ui](https://user-images.githubusercontent.com/1240433/207124951-90451fa2-22b1-4932-ba81-143ba47ecc30.png)
If two versions of an ersd (for example) exist in the kar directory (or subdirectory), there's no way to distinguish them in the UI. Adding a version number somewhere would disambiguate this.

**Comment by VenkatSaiReddyTeegala** [comment]
Resolved as part of 3.1.4
