### ISSUE TITLE
Reduce the periodic tasks for encounters which are closed

### ISSUE THREAD

**Issue by mthrilok** [drajer-health/eCRNow#419]
hi Dragon,

As discussed in our sync up calls submitting this request to validate this request on your side. 

With the current implementation in ECRAPP code , for encounters which are closed we are scheduling tasks to execute on every day for next 3 days/72  hours . Can we remove this setting , instead of scheduling tasks every day can we have one final task to be executed after 72 hours/ 3 days. This change will reduce more number of tasks to be executed on a daily basis looking at the volumes we have observed on our side. 

Please let us know your thoughts.

**Comment by mthrilok** [comment]
@nbashyam  -- Please review this request if it is already addressed in new code/ersd changes ?

**Comment by nbashyam** [comment]
This is being closed based on the use of ERSD v2 by the vendor where the issue is resolved.
