### ISSUE TITLE
EICR generation taking time

### ISSUE THREAD

**Issue by mthrilok** [drajer-health/eCRNow#421]
hi Dragon,

As per our analysis with the current Dark Launch data we have that for EICR generation "Each observation result is being looped and compared with one another ". We suspect this logic is taking time and this is adding up to end-to-end flow. Can you please review this , we can discuss in our sync up call if you need any examples. 

Min and Max Time Range for EICR report generation we have observed on our side : 0.2 - 19 second

**Comment by lakshman301195** [comment]
Adding the screenshot of the code snippet.
<img width="816" alt="Screenshot 2022-12-22 at 5 18 21 PM" src="https://user-images.githubusercontent.com/121233760/209129152-6db01e27-acd0-472c-8f0c-887a06e9d6bd.png">

**Comment by nbashyam** [comment]
This has been fixed in the current baseline.
