### ISSUE TITLE
Consume Observation data in DiagnosticReport FHIR call

### ISSUE THREAD

**Issue by mthrilok** [drajer-health/eCRNow#422]
Hi Dragon,

In the current app code we have seen that the app is trying to call each Observations which are received in Diagnostic report FHIR call . Instead of doing multiple Observation calls again from the app can we use the Observations obtained in DiagnosticReport FHIR call.

on Athena side if we use include  parameter we will get the Observation results in DiagnosticReport itself . Please review this request if this possible , this will help to avoid Observation calls to our monolith system and reduce the time take for processing each encounter.

**Comment by nbashyam** [comment]
This has been fixed in the current baseline.
