### ISSUE TITLE
Implement Database connection pooling 

### ISSUE THREAD

**Issue by characode** [drajer-health/eCRNow#423]
Connection Pooling for database

- Upon review it appears that the built in configuration has been disabled: https://github.com/drajer-health/eCRNow/blob/5db70b170a40d064555638f3a56276a71bf38e50/src/main/java/com/drajer/ecrapp/EcrApp.java#L18

- And connection open/close was implemented instead:https://github.com/drajer-health/eCRNow/blob/5db70b170a40d064555638f3a56276a71bf38e50/src/main/java/com/drajer/ecrapp/config/HibernateConfiguration.java#L37

This prevents us from taking advantage of automatically configuring a connection pool via spring.

**Comment by nbashyam** [comment]
This has been implemented for the merged release 3 and master baseline on master.
