### ISSUE TITLE
Implement Rest Template pooling connection configuration

### ISSUE THREAD

**Issue by characode** [drajer-health/eCRNow#424]
Rest template connection pooling/configuration

- Defined socket timeout - https://github.com/drajer-health/eCRNow/blob/Release-3.0/src/main/java/com/drajer/sof/utils/FhirContextInitializer.java#L67
- Can this be configured as a property instead of hard coded?
- Can other standard configurations be added as well? ConnectTimeout, PoolMaxPerRoute, PoolMaxTotal and ConnectionRequestTimeout

Reviewed ECRNOW for restApiURL requests:

- Using spring resttemplate.exchange https://github.com/drajer-health/eCRNow/blob/Release-3.0/src/main/java/com/drajer/routing/RestApiSender.java#L73
- Can this be configured to utilize the same properties for timeouts and pooling - https://howtodoinjava.com/spring-boot2/resttemplate/resttemplate-timeout-example/

**Comment by nbashyam** [comment]
This has been committed for the Release3.0 and the master merged baseline.
