### ISSUE TITLE
Observations with new ERSD file - Version 2

### ISSUE THREAD

**Issue by mthrilok** [drajer-health/eCRNow#428]
1. Version id is not available in ERSD file 
2. CheckReportable job is scheduled for every 5 minutes
3. DiagnosticReport matches are not marked as reportable with the new ersd where as the same were reportable in earlier ersd

**Comment by mthrilok** [comment]
hi @nbashyam  --Please review this issue , thanks .

**Comment by nbashyam** [comment]
#1 and #2 are fixed with the previous ERSD release on 4/3/2023
#3 is inprogress.

**Comment by nbashyam** [comment]
This has been fixed with the latest ERSD released in August 2023 version 1.2.0.0.
