### ISSUE TITLE
Issue with ersd.file.location in application.properties set to unknown file for launchPatient API

### ISSUE THREAD

**Issue by martha-garasky** [drajer-health/eCRNow#430]
When using launchpatient API and ersd.file.location is set to an unknown file (i.e. line 14 of the application.properties file), then line 372 of CdaProblemGenerator file doesn’t work - that function is trying to get information from a location that doesn’t exist with the LaunchPatient API.

This situation can cause validation errors that look like the following: 

> Message
> 
> If either value/@sdtc:valueSet or value/@sdtc:valueSetVersion is present then both value/@sdtc:valueSet and value/@sdtc:valueSetVersion *SHALL* be present and if either value/translation/@sdtc:valueSet or value/translation/@sdtc:valueSetVersion is present then both value/translation/@sdtc:valueSet and value/translation/@sdtc:valueSetVersion *SHALL* be present and either value or translation *SHALL* contain sdtc:valueSet and sdtc:valueSetVersion (CONF:3284-409).
> 
> Context
> 
> /ClinicalDocument[1]/component[1]/structuredBody[1]/component[2]/section[1]/entry[1]/encounter[1]/entryRelationship[2]/act[1]/entryRelationship[1]/observation[1]/entryRelationship[1]/observation[1]
> 
> Test
> 
> cda:value[@xsi:type='CD'][@sdtc:valueSetVersion and @sdtc:valueSet] or cda:value[@xsi:type='CD']/cda:translation[@sdtc:valueSetVersion and @sdtc:valueSet]

**Comment by nbashyam** [comment]
Fixed issue with commit https://github.com/drajer-health/eCRNow/commit/539b1ebe9a88b076fe14a52b7bdb8eacfcc0dc9f
