### ISSUE TITLE
Validation error - cvc-type.2: The type definition cannot be abstract for element value

### ISSUE THREAD

**Issue by kmarx** [drajer-health/eCRNow#432]
Seeing validation errors for an observation where no value is present. The `type` of the nullFlavor needs to be specified.

There’s a Lantana validator (https://validator-legacy.lantanagroup.com/validator/FileProcessor) that yields the same along with line numbers:
 
`org.xml.sax.SAXParseException; systemId: file:/usr/local/tomcat/tempcdaxml_E5F2CB97099B3C664B4D206E308331F7/create-report_7CAAA92FED434641A9A2BCC5F7B3232C_7a42cc1d-fd0f-40d3-896c-9d0348b64750.xml; lineNumber: 390; columnNumber: 61; cvc-type.2: The type definition cannot be abstract for element value.`

`...
    <organizer classCode="CLUSTER" moodCode="EVN">
        <templateId root="2.16.840.1.113883.10.20.22.4.1"/>
        <templateId root="2.16.840.1.113883.10.20.22.4.1" extension="2015-08-01"/>
        <id root="6d10917e-2a9f-45ad-a37d-b4b044f133d4"/>
        <code code="20966-8" codeSystem="2.16.840.1.113883.6.1" codeSystemName="LOINC" displayName="Culture, Staphylococcus aureus"></code>
        <statusCode code="completed"/>
        <component>
            <observation classCode="OBS" moodCode="EVN">
                <templateId root="2.16.840.1.113883.10.20.22.4.2"/>
                <templateId root="2.16.840.1.113883.10.20.22.4.2" extension="2015-08-01"/>
                <id root="deadbeef-ae69-4cc0-8195-70569b7f29aa" extension="Observation/799ad83c-247e-3b99-b891-c10762d12728.23175169"/>
                <code code="20966-8" codeSystem="2.16.840.1.113883.6.1" codeSystemName="LOINC" displayName="Culture, Staphylococcus aureus">
                    <originalText>
                        <reference value="#labTestName1"/>
                    </originalText>
                </code>
                <statusCode code="completed"/>
                <effectiveTime value="20221207090300-0800"/>
                <value nullFlavor="NI"/> 
            </observation>
        </component>
    </organizer>
</entry>`

I can fix the validation by specifying a `type` for the value:

`
<value xsi:type="PQ" nullFlavor="NI"/>
`

Here are the Loading query, Triggering bundle, and eICR files
[ecrNow-issue432.zip](https://github.com/drajer-health/eCRNow/files/10365715/ecrNow-issue432.zip)

**Comment by nbashyam** [comment]
Fixed with commit 75396ae80971be82ba355715c4e46420342e1b8c
