### ISSUE TITLE
substanceAdministration effectiveTime Issue

### ISSUE THREAD

**Issue by martha-garasky** [drajer-health/eCRNow#434]
effectiveTime is not being populated for the substanceAdministration element even though AuthoredOn Date is populated.

Debug Notes:
CdaMedicationGenerator.java >> generateMedicationSection
 Line 206: This evaluates to TRUE. All of these things that are checked are empty, but they’re not null

> if (t != null && t.getRepeat() != null && t.getRepeat().getBoundsPeriod() != null) {
>  startDate = t.getRepeat().getBoundsPeriod().getStartElement();
> }
<img width="626" alt="Screen Shot 2023-01-10 at 12 24 11 PM" src="https://user-images.githubusercontent.com/111151151/211642917-8cd66360-5316-4917-a5d3-c217731d3d1f.png">

Line 211 evaluates to FALSE because startDate is not null… it’s just empty

**Comment by nbashyam** [comment]
Fixed with commit - https://github.com/drajer-health/eCRNow/commit/ee173a5b6b55070b13d280118bcb2953a1d34a90
