### ISSUE TITLE
ECR Document submission errors

### ISSUE THREAD

**Issue by martha-garasky** [drajer-health/eCRNow#435]
Although our application is only set up to send R1.1 files, it is trying to send to both FHIR and R1.1 for some reason.

> 2023-01-03 18:23:10.235  INFO 7216 --- [db-scheduler-pool-1-thread-2] com.drajer.bsa.kar.action.SubmitReport   : PHA is NULL
> 2023-01-03 18:23:10.237  WARN 7216 --- [db-scheduler-pool-1-thread-2] com.drajer.bsa.kar.action.SubmitReport   : No PHA was found with submission endpoint https://cqpdvipcr3.execute-api.us-east-1.amazonaws.com/dev
> 2023-01-03 18:23:10.237  WARN 7216 --- [db-scheduler-pool-1-thread-2] com.drajer.bsa.kar.action.SubmitReport   : Continuing without auth token
> 2023-01-03 18:23:10.237  INFO 7216 --- [db-scheduler-pool-1-thread-2] com.drajer.bsa.kar.action.SubmitReport   : 1 Resources to submit
> 2023-01-03 18:23:10.241  INFO 7216 --- [db-scheduler-pool-1-thread-2] com.drajer.bsa.kar.action.SubmitReport   :  Trying to invoke $process-message
> 2023-01-03 18:23:11.531 DEBUG 7216 --- [db-scheduler-execute-due-pool-2-thread-1] com.github.kagkarlsson.scheduler.Waiter  : Waiter start wait.
> 2023-01-03 18:23:15.176 ERROR 7216 --- [db-scheduler-pool-1-thread-2] com.drajer.bsa.kar.action.SubmitReport   : Error calling $process-message endpoint

Looks like it might be getting pulled from healthcare_setting.kars_active: 
{"artifactStatus":[{"id":null,"hsId":null,"karId":"rctc-release-2022-10-19-Bundle-rctc","karVersion":"","versionUniqueKarId":"rctc-release-2022-10-19-Bundle-rctc|","isActive":true,"lastActivationDate":1672780634543,"lastInActivationDate":1672780634543,"subscriptionsEnabled":false,"subscriptions":[],"covidOnly":null,"outputFormat":"BOTH"}],"id":8}

Not sure where that comes from? Or how best to update? Opened and re-saved on the healthcaresettings page (which I’ve done before) and that column was updated to null. However, once it gets to the SubmitReport file, somehow that column is once again populated with the info above.
<img width="558" alt="Screen Shot 2023-01-10 at 12 27 37 PM" src="https://user-images.githubusercontent.com/111151151/211643563-479193d5-f980-4867-a503-cb373f6efa83.png">

**Comment by nbashyam** [comment]
Fixed with the latest commits on 1/23/2023.
