### ISSUE TITLE
Encounter end time calculation error

### ISSUE THREAD

**Issue by sathieshkumar** [drajer-health/eCRNow#438]
We add the EncounterStartThreshold instead of EncounterEndThreshold to the fhir encounter end date to get the final end date.

Current code in EhrFhirR4QueryServiceImpl.java:

```
if (substitutedQuery.contains(ENCOUNTER_START_DATE_PARAM)
        || substitutedQuery.contains(ENCOUNTER_END_DATE_PARAM)) {
      int startThreshold =
          -1 * Integer.valueOf(data.getHealthcareSetting().getEncounterStartThreshold());
      int endThreshold = Integer.parseInt(data.getHealthcareSetting().getEncounterStartThreshold());
```

**Comment by nbashyam** [comment]
Fixed with commit - https://github.com/drajer-health/eCRNow/commit/ee173a5b6b55070b13d280118bcb2953a1d34a90
