### ISSUE TITLE
Unit test failure in ApplicationUtilsTest

### ISSUE THREAD

**Issue by sathieshkumar** [drajer-health/eCRNow#445]
We are getting unit test failure in ApplicationUtilsTest.java when we run the tests on the last day of the month. The failing assertion is below:
` assertTrue(
        t.atZone(ZoneOffset.UTC).getDayOfMonth()
            >= (ct.atZone(ZoneOffset.UTC).getDayOfMonth() + 1));`

On the last day of the month the scheduled datetime day of the month will be 1st of next month and will be less than current day. So updated the assertion to below:
```
    assertTrue(
        t.atZone(ZoneOffset.UTC).getDayOfMonth() >= (ct.atZone(ZoneOffset.UTC).getDayOfMonth() + 1)
            || t.atZone(ZoneOffset.UTC).getMonthValue()
                > ct.atZone(ZoneOffset.UTC).getMonthValue());

```

**Comment by nbashyam** [comment]
This is already fixed as part of the 3.1.1 baseline.
