### ISSUE TITLE
Reduce the number of Encounter FHIR calls per taks

### ISSUE THREAD

**Issue by sathieshkumar** [drajer-health/eCRNow#448]
We make 6 calls to the Encounter FHIR API for every check-reportable task. Out of this 5 calls are to get the encounter end time in different steps. We can reuse encounter resource pulled initially to get the end time across steps.
The logic lies in EhrFhirR4QueryServiceImpl.java, here retrieveContextEncounter makes the FHIR call to Encounter API.
`      if (substitutedQuery.contains(ENCOUNTER_END_DATE_PARAM)) enc = retrieveContextEncounter(data);
`
Method retrieveContextEncounter has a check to get encounter from KarProcessingData but the encounter is not retrieved and we are always making FHIR call.

```
    if (data.getContextEncounter() != null) enc = data.getContextEncounter();
    else {
      String encId = data.getContextEncounterId();

      if (encId != null && !encId.isEmpty()) {

        logger.info(LOG_FHIR_CTX_GET);
        FhirContext context = fhirContextInitializer.getFhirContext(R4);

        logger.info(LOG_INIT_FHIR_CLIENT);
        IGenericClient client = getClient(data, context);

        Resource res = getResourceById(client, context, ResourceType.Encounter.toString(), encId);

        if (res != null) enc = (Encounter) res;
      }
    }
```

**Comment by mthrilok** [comment]
@nbashyam  -- Please review this on priority as this would reduce the number of FHIR calls . Thanks

**Comment by nbashyam** [comment]
Fixed with the above commit.
