### ISSUE TITLE
eCRNOW2.0: Condition filter by verification status doesn't work as expected.

### ISSUE THREAD

**Issue by AnanthaKrishnaV** [drajer-health/eCRNow#456]
Condition filter by verification status doesn't work as expected.

If there is no VerificationStatus element present in the condition resource, then condition filtering doesn't work as expected. condition.getVerificationStatus() returns valid empty object when the field is not present instead of NULL, same with the method condition.getVerificationStatus().getCodingFirstRep(). 

`        if ((condition.getVerificationStatus() == null)
            || (condition.getVerificationStatus() != null
                && condition.getVerificationStatus().getCodingFirstRep() != null
                && condition.getVerificationStatus().getCodingFirstRep().getCode() != null
                && !condition
                    .getVerificationStatus()
                    .getCodingFirstRep()
                    .getCode()
                    .equals(ENTERED_IN_ERROR))) {

          if (condition.getAbatement() == null && condition.hasCategory()) {
            List<CodeableConcept> conditionCategory = condition.getCategory();
            for (CodeableConcept categoryCodeableConcept : conditionCategory) {
              List<Coding> categoryCodingList = categoryCodeableConcept.getCoding();
              for (Coding categoryCoding : categoryCodingList) {
                boolean foundPregnancyCondition =
                    condition
                        .getCode()
                        .getCoding()
                        .stream()
                        .anyMatch(
                            coding ->
                                Arrays.stream(QueryConstants.getPregnancySmtCodes())
                                    .anyMatch(coding.getCode()::equals));
                if (categoryCoding.getCode().equals(PROBLEM_LIST_CONDITION)
                    && !foundPregnancyCondition) {
                  logger.debug("Added condition to problem list {}", condition.getId());
                  problemConditions.add(condition);
                  conditionCodes.addAll(findConditionCodes(condition));
                } else if (categoryCoding.getCode().equals(ENCOUNTER_DIAGNOSIS_CONDITION)
                    && condition.hasEncounter()
                    && !foundPregnancyCondition) {

                  if (condition
                      .getEncounter()
                      .getReference()
                      .equals("Encounter/" + launchDetails.getEncounterId())) {
                    logger.debug(
                        "Added condition to Encounter Diagnosis list {}", condition.getId());
                    encounterDiagnosisConditions.add(condition);
                    conditionCodes.addAll(findConditionCodes(condition));
                  }
                }
              }
            }
          } else {
            conditionMissingAbatement++;
          }
        } else {
          conditionInError++;
        }`

Do to this logic goes to the else part and we miss the condition.

**Comment by nbashyam** [comment]
@AnanthaKrishnaV - Assuming you will send a PR with the above fix.

**Comment by AnanthaKrishnaV** [comment]
Addressed with PR #470
