### ISSUE TITLE
Question about communication

### ISSUE THREAD

**Issue by j-hobeck** [drajer-health/eCRNow#457]
I was looking at using eCR Now and wanted to ask a few questions.  
My understanding is that the eCR Now service calls out to the EHR (using SMART on FHIR) to query for reportable conditions.  It would then call out to the EHR passing the Reportability Response.  So, the communication flow is always from eCR Now to the EHR and not from the EHR to eCR Now?  Are these queries run off of a timer that can be configured?
If I wanted to use a single eCR Now service to connect to an EHR that is multi-tenant (supports multiple different customers) I am assuming I would have to setup a connection per customer? Is there a limit to the number of connections a single eCR Now service can support?

**Comment by nbashyam** [comment]
eCRNow is horizontally scalable and the eCRNow app accomodates many workflows. The primary workflow gets triggered from the EHR based on events and then the eCRNow schedules timers to execute various tasks. For more information it might be better to reach out the eCR Onboarding team and schedule a discussion with the team.

**Comment by AGABB** [comment]
Hi @j-hobeck, My name is Andrew with the eCR Onboarding team. Feel free to send any questions to our team at ecr@cdc.gov

@nbashyam request to close issue.
