### ISSUE TITLE
eCRNOW2.0: Exception handling in createEicr action when failed to create eicr for matched code.

### ISSUE THREAD

**Issue by AnanthaKrishnaV** [drajer-health/eCRNow#462]
eCRNOW: Exception handling in createEicr action when failed to create eicr for matched code.

When eicr creation is failed during createEicrAction:

1. creationEicrAction is not retried and exception is not returned to the main method.
2. Also, periodicEicrAction will fail to create eicr due to missing logic in PatientExecutioStatus.hasEicrBeenCreated method. It is checking only for status and not whether eicr is created true.

**Comment by nbashyam** [comment]
@AnanthaKrishnaV - Assuming you will send a PR with the above fix.

**Comment by AnanthaKrishnaV** [comment]
> @AnanthaKrishnaV - Assuming you will send a PR with the above fix.

Yes

**Comment by nbashyam** [comment]
This is not needed in 3.X of the app, hence closing the issue.
