### ISSUE TITLE
Lab result section has "unknown" in narrative

### ISSUE THREAD

**Issue by sathieshkumar** [drajer-health/eCRNow#464]
After recent fix the lab tests are not pulled in eICR. Attached an example loading query.

**Comment by sathieshkumar** [comment]
[loading_query.txt](https://github.com/drajer-health/eCRNow/files/10863714/loading_query.txt)

**Comment by mthrilok** [comment]
hi Dragon , As discussed in todays call , this is related to the issue "Lab result section has "unknown" in narrative" in excel.

**Comment by nbashyam** [comment]
@sathieshkumar  - Please upload observation test data to debug the issue further.

**Comment by sathieshkumar** [comment]
@nbashyam  The lab result section was missing as observations are not pulled. When it's pulled properly, we can see the Lab result section but still has unknown in testName.
![image](https://user-images.githubusercontent.com/7060059/223215032-af56c7f0-8f78-4fa5-bd98-6b81f74a3158.png)

**Comment by sathieshkumar** [comment]
Attaching a sample labTest below:

```
   "resource": {
      "resourceType": "DiagnosticReport",
      "id": "a-15467.inptresultlab-346083",
      "meta": {
        "security": [ {
          "system": "http://terminology.hl7.org/CodeSystem/v3-ActCode",
          "code": "NOPAT",
          "display": "no disclosure to patient, family or caregivers without attending provider's authorization"
        }, {
          "system": "http://terminology.hl7.org/CodeSystem/v3-ObservationValue",
          "code": "SUBSETTED",
          "display": "subsetted"
        } ]
      },
      "extension": [ {
        "url": "https://fhir.athena.io/StructureDefinition/ah-practice",
        "valueReference": {
          "reference": "Organization/a-1.Practice-15467"
        }
      }, {
        "url": "https://fhir.athena.io/StructureDefinition/ah-chart-sharing-group",
        "valueReference": {
          "reference": "Organization/a-15467.CSG-1"
        }
      } ],
      "status": "final",
      "category": [ {
        "coding": [ {
          "system": "http://terminology.hl7.org/CodeSystem/v2-0074",
          "code": "LAB",
          "display": "Laboratory"
        } ]
      } ],
      "code": {
        "coding": [ {
          "system": "http://loinc.org",
          "code": "1988-5"
        } ]
      },
      "subject": {
        "reference": "Patient/a-15467.E-55476"
      },
      "encounter": {
        "reference": "Encounter/a-15467.stay-131246"
      },
      "effectiveDateTime": "2023-02-01T11:22:00-05:00",
      "issued": "2023-02-01T11:22:42.000-05:00",
      "performer": [ {
        "reference": "Organization/a-1.CP-12189930"
      } ],
      "result": [ {
        "reference": "Observation/a-15467.inptlabobservation-2594800"
      } ]
    }
  }
```

**Comment by sathieshkumar** [comment]
Observation resource:

` {
    "resource": {
      "resourceType": "Observation",
      "id": "a-15467.inptlabobservation-2594800",
      "meta": {
        "security": [ {
          "system": "http://terminology.hl7.org/CodeSystem/v3-ActCode",
          "code": "NOPAT",
          "display": "no disclosure to patient, family or caregivers without attending provider's authorization"
        } ]
      },
      "extension": [ {
        "url": "https://fhir.athena.io/StructureDefinition/ah-practice",
        "valueReference": {
          "reference": "Organization/a-1.Practice-15467"
        }
      }, {
        "url": "https://fhir.athena.io/StructureDefinition/ah-chart-sharing-group",
        "valueReference": {
          "reference": "Organization/a-15467.CSG-1"
        }
      } ],
      "identifier": [ {
        "system": "https://fhir.athena.io/sid/ah-observation",
        "value": "a-15467.inptlabobservation-2594800"
      } ],
      "status": "final",
      "category": [ {
        "coding": [ {
          "system": "http://terminology.hl7.org/CodeSystem/observation-category",
          "code": "laboratory",
          "display": "Laboratory"
        } ]
      } ],
      "code": {
        "text": "CRP"
      },
      "subject": {
        "reference": "Patient/a-15467.E-55476"
      },
      "encounter": {
        "reference": "Encounter/a-15467.stay-131246"
      },
      "effectiveDateTime": "2023-02-01T11:22:00-05:00",
      "valueQuantity": {
        "value": 2.24,
        "unit": "mg/dL"
      },
      "referenceRange": [ {
        "text": "0.00-0.50"
      } ]
    }
  }`

**Comment by nbashyam** [comment]
This has been resolved with the above commit.
