### ISSUE TITLE
ITBaseCustom Test Failed during build with latest version of master and Release 3.0

### ISSUE THREAD

**Issue by intrinsiqdev** [drajer-health/eCRNow#467]
[ERROR]
 callApi[customQuery](com.drajer.bsa.controller.ITBaseCustom)  Time elapsed: 40.502 s  <<< FAILURE!
com.github.tomakehurst.wiremock.client.VerificationException:
No requests exactly matched. Most similar request was:  expected:<
GET
/FHIR/Encounter?patient=12742571
> but was:<
GET
/FHIR/Encounter/97953900

**Comment by nbashyam** [comment]
This should already be fixed in the baseline, please reverify.

**Comment by nbashyam** [comment]
This is already fixed as part of the 3.1.1 baseline.
