### ISSUE TITLE
Medication Admin - in eicr DosageQuantity  pulling 'unit' instead of 'code'

### ISSUE THREAD

**Issue by BhoomikaRGopal** [drajer-health/eCRNow#483]
Should be displaying the dosage quantity units based on this spec : [UCUM / UCUM Specification (unitsofmeasure.org)](https://unitsofmeasure.org/ucum) https://build.fhir.org/valueset-ucum-units.html

we need replace getUnit() with getCode() here ( https://github.com/drajer-health/eCRNow/blob/master/src/main/java/com/drajer/cdafromr4/CdaFhirUtilities.java#L1265
)

What a specific message looks should like out of MedicationAdmin for this doseQuantity 
 
"doseAndRate": [
              {
                "doseQuantity": {
                  "value": 1,
                  "unit": "caps",
                  "system": "[http://unitsofmeasure.org](https://urldefense.com/v3/__http:/unitsofmeasure.org__;!!ACWV5N9M2RV99hQ!JjI2xpowfo62i2hjWaoic_5vMv8nNmwHYdG1IgxjHCnSPF7uI3qeZscWEYbY9ZbtevHQrCWW7YPenRVfl74pu_loow$)",
                  "code": "{Capsule}"
                }
              }
            ]

**Comment by nbashyam** [comment]
Will analyze and get back in our scrum calls.

**Comment by nbashyam** [comment]
Fixed with the above commit.
