### ISSUE TITLE
Post Merge issue with Social History section for Employment

### ISSUE THREAD

**Issue by dp8ton** [drajer-health/eCRNow#487]
Since receiving the latest master build, there seems to be an issue around Social History > Observation > Employment.  The eCR-Now app is adding the <observation> for employment, however, the app is not adding the coded value.  When validating the report, the validator will error since the syntax is incorrect.

My guess is becuase the version of the [eRSD file from 12/12/2022](https://github.com/drajer-health/eCRNow/blob/master/documents/app-artifacts/kars/eRSDv2_specification_bundle%2012_12_2022.json) is not pulling Employment history.  However, you will see employment info is within the loading file.

Here's an example of the observation.  Note the "/value" without any addtional info.

`<observation classCode="OBS" moodCode="EVN">
	<templateId root="2.16.840.1.113883.10.20.22.4.38" extension="2015-08-01"/>
	<id root="39d1ec2b-99f6-4788-91c2-b61b5e127a06"/>
	<code code="364703007" codeSystem="2.16.840.1.113883.6.96" codeSystemName="SNOMED-CT" displayName="Employment Detail">
		<translation code="11295-3" codeSystem="2.16.840.1.113883.6.1" codeSystemName="LOINC" displayName="Current employment - Reported"/>
		<translation code="364703007" codeSystem="2.16.840.1.113883.6.96" codeSystemName="SNOMED-CT" displayName="Employment Detail"/>
	</code>
	<statusCode code="completed"/>
	<effectiveTime value="20230326065700-0500"/>
</value>
</observation>`

Attached are the reports and loading query in the zip file
[EmploymentExample.zip](https://github.com/drajer-health/eCRNow/files/11092600/EmploymentExample.zip)

**Comment by nbashyam** [comment]
We will analyze and add it to the current sprint.

**Comment by dp8ton** [comment]
Update to this issue...  We're still seeing an issue with an incomplete </value> for Employment with the lastest build - includes changes from April 3rd.  

What we're seeing is four (4) <observations> for employment - two (2) are good, and two (2) are invalid.  The patient being reported only has one (1) employment record in fhir.

**Comment by nbashyam** [comment]
The Code system for the employement status should be 2.16.840.1.114222.4.5.314 instead of 2.16.840.1.114222.4.11.7186
This has to be corrected.

**Comment by dp8ton** [comment]
We can make that change.  We're using this valueset for employment, as defined for Cancer Case - https://phinvads.cdc.gov/vads/ViewValueSet.action?oid=2.16.840.1.114222.4.11.7186#

**Comment by dp8ton** [comment]
With the latest code change (4/26), this appears to be working better.  We made a change with the OID for the fhir resource and loaded the latest code.  eCR-Now is generating an eCR report that passes the validator.

However, one quick thing.  There are four (4) observation records in the eCR report for employment.

![image](https://user-images.githubusercontent.com/122484204/234883491-0beed928-eb3f-4a44-afe4-20be4d5346f4.png)

**Comment by dp8ton** [comment]
Andrew - Attached is Scenario 1 for Jill Test.
[Scenario1JillTest.zip](https://github.com/drajer-health/eCRNow/files/11345787/Scenario1JillTest.zip)

**Comment by dp8ton** [comment]
Andrew - Attached is Scenario 1 for Jill Test.
[Scenario1JillTest.zip](https://github.com/drajer-health/eCRNow/files/11347777/Scenario1JillTest.zip)

**Comment by nbashyam** [comment]
can you look into the loading query so that we can see how many observations are there ?

**Comment by nbashyam** [comment]
As per our discussion this seems to be a problem in the EHR, please re-open if it is not so.

**Comment by dp8ton** [comment]
Attached is the eCR report, loading/trigger queries, plus a respones from the EHR observation fhir response.  

The EHR stores employment observations at the encounter level, so for this scenario there are two respones coming back since there are two encounters for this patient.  See attached zip file for more info.

[Scenario1JillTest.zip](https://github.com/drajer-health/eCRNow/files/11422334/Scenario1JillTest.zip)
