### ISSUE TITLE
FHIR Race code data coded as ASKU - creates non null flavor race code element for dtsu2

### ISSUE THREAD

**Issue by characode** [drajer-health/eCRNow#489]
Patient was asked to declare race but it is unknown so is coded as ASKU in FHIR, however the ECR specifications states that the patient shall contain exactly:
This patient SHALL contain exactly one [1..1] raceCode, which SHALL be selected from ValueSet Race Category Excluding Nulls urn:oid:2.16.840.1.113883.3.2074.1.1.3 DYNAMIC (CONF:1198- 5322).

The FHIR standard includes 2 values which can be a representation of unknown:
https://build.fhir.org/ig/HL7/US-Core/ValueSet-omb-race-category.html
ASKU - Asked but unknown 
UNK - Unknown

The logic for DSTU only checks if race and race.code are not null and then creates a coded raceCode section for ECR. The logic does not treat ASKU as a null flavor nor does it treat UNK as null flavor if they are defined for the patient only if those values are not present are they treated as a null. 

Should another logical block manage instances where the coded values are ASKU and UNK as well? Similar issue with ethnicity. 

`    
if (race != null && race.getCode() != null) {
      patientDetails.append(
          CdaGeneratorUtils.getXmlForCD(
              CdaGeneratorConstants.RACE_CODE_EL_NAME,
              race.getCode(),
              CdaGeneratorConstants.RACE_CODE_SYSTEM,
              CdaGeneratorConstants.RACE_CODE_SYSTEM_NAME,
              race.getDisplay()));
    } else {
      patientDetails.append(
          CdaGeneratorUtils.getXmlForNullCD(
              CdaGeneratorConstants.RACE_CODE_EL_NAME, CdaGeneratorConstants.NF_NI));
    }
` 
    
    Resulting ECR document creates a document with the following:
`
<raceCode code="ASKU" codeSystem="2.16.840.1.113883.6.238" codeSystemName="Race &amp; Ethnicity - CDC" displayName="asked but unknown"/>
<ethnicGroupCode code="UNK" codeSystem="2.16.840.1.113883.6.238" codeSystemName="Race &amp; Ethnicity - CDC" displayName="unknown"/>
`

**Comment by nbashyam** [comment]
Will analyze and get back.

**Comment by nbashyam** [comment]
Fixed with the above commit.
