### ISSUE TITLE
Closed encounters are scheduling tasks every day

### ISSUE THREAD

**Issue by sathieshkumar** [drajer-health/eCRNow#491]
Closed encounters are running for ever in the app. Looks like this is introduced in this commit: https://github.com/drajer-health/eCRNow/commit/62bd33578470a98c33ee7dbbe1549607a86d412b#diff-7012dd47d002f4f5f220e33b36a7bc4d775b20eb68f3dcc5baaa325c63b81c0c

Encounter resource is pulled from the notification_context.notification_data which is set only during launch request. So the encounter end date is always empty and current date is used for evaluating in-progress encounter. Below screenshot shows logs for a closed encounter, here the current date is considered as end date everyday:
<img width="1209" alt="image" src="https://user-images.githubusercontent.com/7060059/230662396-eb3db3a3-9567-4e51-95df-a10f76cd6003.png">

**Comment by nbashyam** [comment]
Will examine the encounter resource status and see if it is being setup properly.

**Comment by nbashyam** [comment]
Fixed with the above commit.
