### ISSUE TITLE
Confirm on ECRNOW specifications

### ISSUE THREAD

**Issue by mthrilok** [drajer-health/eCRNow#496]
hi Dragon/Team ,

Could you please confirm on the below queries 

1) For Case Report/EICR are we following the standard/spec HL7 CDA eICR IG in § 170.205(t)(2) ?
2) Also for RR what is the current version that app is supporting ?
Receive, consume, and process a case report response that is formatted to either the RR profile of
The HL7 FHIR IG in § 170.205(t)(1) or
The HL7 CDA RR IG in § 170.205(t)(3); and

**Comment by nbashyam** [comment]
The current version of the app supports HL7 CDA R1.1 eICR and HL7 CDA RR 1.0
The app is being enhanced to handle the eICR from eCR FHIR IG mentioned in the above regulations and the HL7 CDA R3.1 eICR standards.
