### ISSUE TITLE
Evaluate diagnostic report to find/support trigger code in 2.0

### ISSUE THREAD

**Issue by Pramodshetty04** [drajer-health/eCRNow#500]
As discussed on 04/24/2023 please add diagnostic report support to evaluate the trigger code in ecrnow 2.0, separate email has been sent on the same.

If thats not supported to be on the trigger query please confirm.

**Comment by nbashyam** [comment]
This is already supported in eCRNow App 3.0, is this required to be supported in 2.0 ?

**Comment by Pramodshetty04** [comment]
Yes we want the diagnostic report to be supported in 2.0

**Comment by nbashyam** [comment]
We are not planning on changing any 2.X software going forward, please look to upgrade to 3.X of the app.
