### ISSUE TITLE
Could not have two eRSDs(active-inactive) to execute older tasks 

### ISSUE THREAD

**Issue by sathieshkumar** [drajer-health/eCRNow#502]
When we use new eRSD, the existing tasks are filing. We want run the old tasks with inactive eRSDs.

**Comment by nbashyam** [comment]
New issue that has to be addressed as an enhancement to allow eICRs to be generated even after being de-activated.

**Comment by nbashyam** [comment]
Since it is directly comparing to the KARExecutionState, the fix may work.
