### ISSUE TITLE
dq-resultObservation-002 Observations with text Code

### ISSUE THREAD

**Issue by sathieshkumar** [drajer-health/eCRNow#510]
These observations have code as text. The app has logic to pull code from DiagnosticReport if the observation doesn't have a LOINC code. But this logic applies only if the DiagnosticReport code is in the rctc valueset.

Could we update logic for this observations to get code from their DiagnosticReport instead of sending null Flavor.

**Comment by nbashyam** [comment]
Can you add the diagnostic report fhir resource also.

**Comment by nbashyam** [comment]
This has been resolved wiht the above commit.
