### ISSUE TITLE
Inactive Medications in Premier are being translated to Aborted status

### ISSUE THREAD

**Issue by deb-hall-alt** [drajer-health/eCRNow#514]
As originally reported in [AIMS-45573](https://aphlinformatics.atlassian.net/servicedesk/customer/portal/3/AIMS-45573), Premier Healthcare (Theradoc EHR) has noticed that if a medication order is discontinued, it will show as Aborted in the eICR under “MedicationStatement“ and “MedicationRequest“. In Theradoc, there is not a status of Aborted for medication orders; they only have Active, Inactive and Cancelled.

Theradoc and RCKMS staff would like more information on why Inactive medications are being translated to Aborted. Here are the possible values from the eICR v1.1 specification:
![image](https://github.com/drajer-health/eCRNow/assets/97293747/0f579c07-be0d-48f7-8810-cb660d884de6)

Please refer to the redacted eICR attached, which has 34 medications with an Aborted status (attached as a .txt since GitHub does not support attaching .xml files): 
[Overdose_Tennessee_Sample_Redacted_20230413.txt](https://github.com/drajer-health/eCRNow/files/11546039/Overdose_Tennessee_Sample_Redacted_20230413.txt)

And, here is an example of the code with the Aborted status:
```
  <entry typeCode="DRIV">
    <substanceAdministration classCode="SBADM" moodCode="EVN">
      <templateId root="2.16.840.1.113883.10.20.22.4.16"/>
      <templateId root="2.16.840.1.113883.10.20.22.4.16" extension="2014-06-09"/>
      <id root="1.2.840.114350.1.13.0.1.7.777.555.222" extension="https://ips-tdapi-prod2.app.medcity.net/tdapi/tdfhir/api/fhir/MedicationStatement/1048239791"/>
      <statusCode code="aborted"/>
      <effectiveTime value="20230409194800-0500"/>
      <doseQuantity value="1.0"/>
      <consumable>
        <manufacturedProduct classCode="MANU">
          <templateId root="2.16.840.1.113883.10.20.22.4.23"/>
          <templateId root="2.16.840.1.113883.10.20.22.4.23" extension="2014-06-09"/>
          <id root="6ea70dc1-d02e-4bf6-a047-96d04c5022ed"/>
          <manufacturedMaterial>
            <code code="6185" codeSystem="2.16.840.1.113883.6.88" codeSystemName="RXNORM" displayName="labetalol"/>
          </manufacturedMaterial>
        </manufacturedProduct>
      </consumable>
    </substanceAdministration>
  </entry>
```

**Comment by nbashyam** [comment]
Added to 3.1.3
