### ISSUE TITLE
new eRSD bug - DiagnosticReport codes are marked as reportable

### ISSUE THREAD

**Issue by sathieshkumar** [drajer-health/eCRNow#517]
In the new eRSD rctc-release-2023-02-03-Bundle-rctc|1.1.0, the is-encounter-reportable condition doesn't include diagnosticOrder and diagnosticReport conditions. So the encounters with these reportable codes are not generating eICR.

**Comment by nbashyam** [comment]
Addressed as part of the July / August 2023 ERSD release.
