### ISSUE TITLE
Version Number field inside EICR xml is always 1, even if we send 2nd/3rd version of EICR

### ISSUE THREAD

**Issue by lakshman301195** [drajer-health/eCRNow#518]
While inspecting the eICR generated for version above 1, it is found that versionNumber is always 1 in all the documents. The ideal expectation is that the versionnumber field inside xml should be updated as per data stored in the column submitted_version_number in ph_messages table. But in the actual behaviour, it is trying to pull from wrong table "eicr", which is why the version is always set to 1 in xml.

<img width="270" alt="Screenshot 2023-05-31 at 5 01 39 PM" src="https://github.com/drajer-health/eCRNow/assets/121233760/9c3f2387-654e-427a-8fd8-513843260ffc">
<img width="568" alt="Screenshot 2023-05-31 at 5 02 34 PM" src="https://github.com/drajer-health/eCRNow/assets/121233760/9e40a347-9020-497e-a197-a9802348f158">

**Comment by nbashyam** [comment]
Fixed in a previous baseline
