### ISSUE TITLE
Request to update trigger_match_status  column in ph_message with sufficient  data

### ISSUE THREAD

**Issue by Pramodshetty04** [drajer-health/eCRNow#524]
I kindly request the inclusion of precise and up-to-date information in this column, specifically regarding the action status and a comprehensive list of all available trigger codes in the EICR (as currently only the first code is displayed). Additionally, it would be beneficial to include the EICR ID in the Outproduced section, aiming for a similar setup as we had in the 2.0 launch details (in the "status" column).

@skshahi 

currently, this is how it displays:

{"statuses":[{"actionId":"","actionType":"**UNKNOWN**","actionStatus":"NOT_STARTED","outputProduced":[],"triggerMatchStatus":true,"matchedCodes":[{"matchedCodes":["[http://snomed.info/sct|189486241000119100"],"matchedValues":[],"valueSet":"http://ersd.aimsplatform.org/fhir/ValueSet/dxtc","valueSetVersion":"2022-10-19","matchedPath":"Condition.code"},{"matchedCodes":["http://hl7.org/fhir/sid/icd-10-cm|T40.1X1A"],"matchedValues":[],"valueSet":"http://ersd.aimsplatform.org/fhir/ValueSet/dxtc","valueSetVersion":"2022-10-19","matchedPath":"Condition.code"}],"matchedResources":null}]}](http://snomed.info/sct%7C189486241000119100%22],%22matchedValues%22:[],%22valueSet%22:%22http://ersd.aimsplatform.org/fhir/ValueSet/dxtc%22,%22valueSetVersion%22:%222022-10-19%22,%22matchedPath%22:%22Condition.code%22%7D,%7B%22matchedCodes%22:[%22http://hl7.org/fhir/sid/icd-10-cm%7CT40.1X1A%22],%22matchedValues%22:[],%22valueSet%22:%22http://ersd.aimsplatform.org/fhir/ValueSet/dxtc%22,%22valueSetVersion%22:%222022-10-19%22,%22matchedPath%22:%22Condition.code%22%7D],%22matchedResources%22:null%7D]%7D)

**Comment by nbashyam** [comment]
I have looked into this and there are other complications, let us discuss this further on our call today.

**Comment by nbashyam** [comment]
After discussion the following information is being requested:
1. Code that matched is required
2. State of the Encounter / Patient processing is required
3. Timer that generated the eICR.

Check Notification_context table and the triggerMatchStatus attribute in the ph_messages to verify the above data.

**Comment by Pramodshetty04** [comment]
Hi Drajer, any further updates on this one?

**Comment by nbashyam** [comment]
Fixed in 3.1.6
