### ISSUE TITLE
ecrNow not compatible with java17

### ISSUE THREAD

**Issue by BhoomikaRGopal** [drajer-health/eCRNow#528]
Compiled ecrNow with java17 we are getting issues , we need to make ecrNow compatible to jdk17

**Tried to update few dependecy version but few testcases are failing unable to load application properties into environment variables**

<img width="439" alt="image" src="https://github.com/drajer-health/eCRNow/assets/126087082/63f21da9-a87a-46ec-9525-d25275e429ef">

java.lang.NullPointerException: Cannot invoke "String.getBytes(java.nio.charset.Charset)" because "com.drajer.ecrapp.security.AESEncryption.secretKey" is null
        at com.drajer.ecrapp.security.AESEncryption.encrypt(AESEncryption.java:42)
        at com.drajer.sof.model.LaunchDetails.setDirectPwd(LaunchDetails.java:425)
        at com.drajer.cdafromr4.CdaEicrGeneratorTest.getLaunchDetails(CdaEicrGeneratorTest.java:117)

**few classes are using depricated api** 

[INFO] /Users/bg092673/workspace/Java 17/eCRNow/eCRNow/src/test/java/com/drajer/test/BaseIntegrationTest.java: Some input files use or override a deprecated API.
[INFO] /Users/bg092673/workspace/Java 17/eCRNow/eCRNow/src/test/java/com/drajer/test/BaseIntegrationTest.java: Recompile with -Xlint:deprecation for details.
[INFO] /Users/bg092673/workspace/Java 17/eCRNow/eCRNow/src/test/java/com/drajer/test/ITEicrController.java: Some input files use unchecked or unsafe operations.
[INFO] /Users/bg092673/workspace/Java 17/eCRNow/eCRNow/src/test/java/com/drajer/test/ITEicrController.java: Recompile with -Xlint:unchecked for details.

**Comment by BhoomikaRGopal** [comment]
[Errors running master branch](https://gist.github.com/sabirnits15/bd807524eb2a93f56751889e9fc9e23d )

[Erros with upgrading dependencies](https://gist.github.com/BhoomikaRGopal/ce193d309e51934a98fde5d60ed9fdaf )

**Comment by nbashyam** [comment]
MAster is now compatible with Java 17.
