### ISSUE TITLE
/api/phMessage: Support "light" fetch to omit large data columns

### ISSUE THREAD

**Issue by kmarx** [drajer-health/eCRNow#529]
We'd like the ability to fetch phMessage data that excludes large data columns such as `submittedCdaData` and `cdaResponseData`.

The use case is that our UI shows a list of encounters (light/meta-data). The user clicks on a given row's `eICR` or `RR` link to render the CDA in a viewing pane. We'd like the CDA data fetch to be lazy instead of fetching it for every record in the UI, since most will typically not be viewed.

**Comment by nbashyam** [comment]
Please subset the data only for batch requests, not for all requests. For all other requests send back the whole record.

**Comment by nbashyam** [comment]
Added in 3.1.3
