### ISSUE TITLE
Observation results included in Diagnostic Report Results are ignored by the app

### ISSUE THREAD

**Issue by lakshman301195** [drajer-health/eCRNow#531]
Currently if we make a fhir call to the diagnostic report endpoint along with the _include filter, it returns the observation results along with it. But the app ignores the observation results from diagnostic report results and goes on to make additional calls to the observation endpoint without reusing the results.

Custom query:
diagnosticOrders=/DiagnosticReport?_include=DiagnosticReport:result&patient=Patient/{{context.patientId}}&date=ge{{context.encounterStartDate}}&ah-practice=a-1.Practice-{{athena.practiceId}}&_query=skip_filecloud_operations

**Comment by lakshman301195** [comment]
[Diagnostic_Report_Result.txt](https://github.com/drajer-health/eCRNow/files/11798830/Diagnostic_Report_Result.txt)

Attached a sample diagnostic result fhir call response with _include filter

**Comment by sathieshkumar** [comment]
We are able to fix this with the below change in EhrFhirR4QueryServiceImpl.java(getResourcesFromSearch method):
![image](https://github.com/drajer-health/eCRNow/assets/7060059/5c9f99cb-4275-4749-b48e-1a63848606aa)

**Comment by mmatiasalt** [comment]
This defect/request has been fixed in the 3.1.2 release.

**Comment by lakshman301195** [comment]
We checked from 3.1.2 Release and this is causing an ClassCastException Error. (Expected Type - DiagnosticReport but type Observation is present)

**Comment by mmatiasalt** [comment]
@lakshman301195 thank you for reporting. Can you please provide examples and Loading query for team to review?

**Comment by nbashyam** [comment]
Investigate getResourcesFromSearch in 3.1.4 and check if any class cast exception occurs.
