### ISSUE TITLE
Encounter Diagnosis: Missing Snomed Code (California)

### ISSUE THREAD

**Issue by rtomas-pinc** [drajer-health/eCRNow#535]
Comments from the State:

Encounter Diagnosis: Missing SNOMED code, please use the recommended value set.
![ecrEnctounterDiagnosis](https://github.com/drajer-health/eCRNow/assets/15131757/2caf334d-227e-48e7-8148-e33db6caa960)

**Comment by rtomas-pinc** [comment]
Reconfirmed with California and Aaron was able to confirm the mockup...

Hi Randy,
 
You are correct. In the value line there should be either a SNOMED (preferred) or ICD code. So the “after change” would be correct. The recommended value set is described on pg. 184 of the HL7 1.1 IG and contains SNOMED codes, which is what we prefer.
 
The value line is where we parse our diagnoses codes from. Typically the translation line is used if the code in the value line can be translated to another codeset (i.e., SNOMED vs. ICD).
 
Aaron Ling, MSN, RN
----------
Here is sample mockup of a format switch.
Before change:
<value xsi:type="CD" nullFlavor="OTH">                        
<translation code="B97.21" codeSystem="2.16.840.1.113883.6.90" codeSystemName="ICD-10-CM" displayName="Coronavirus as the cause of diseases classified to other chapters"/>
 
After change:
<value xsi:type="CD" code="B97.21" codeSystem="2.16.840.1.113883.6.90" codeSystemName="ICD-10-CM" displayName="Coronavirus as the cause of diseases classified to other chapters"/>

**Comment by rtomas-pinc** [comment]
Not sure how to show the html text sample, if I edit the above, I can see it

**Comment by nbashyam** [comment]
Please retest after 3.1.5
