### ISSUE TITLE
Provider Fax Number Support (Utah)

### ISSUE THREAD

**Issue by rtomas-pinc** [drajer-health/eCRNow#536]
There is no placeholder for fax #. This should be found in the assigned author section as a telecom value similar to phone numbers and emails

**Comment by nbashyam** [comment]
This is being included in the upcoming release this week.

**Comment by nbashyam** [comment]
This is included in the release 3.1.2

**Comment by mmatiasalt** [comment]
This defect/request has been fixed in the 3.1.2 release.
