### ISSUE TITLE
CDA: Social History Section, Birth Sex should support us-core-birthsex

### ISSUE THREAD

**Issue by AnanthaKrishnaV** [drajer-health/eCRNow#54]
Currently code look for agro-birthsex with url http://fhir.org/guides/argonaut/StructureDefinition/argo-birthsex. it should also support us-core-birthsex with url http://hl7.org/fhir/us/core/StructureDefinition/us-core-birthsex.

**Comment by nbashyam** [comment]
Pushed change to use US Core Birth Sex url
