### ISSUE TITLE
heathcareSettings Response Options: Add a "No Action" option 

### ISSUE THREAD

**Issue by kmarx** [drajer-health/eCRNow#545]
Out eCRNow deployment gets all its data via the /phMessage API and doesn't require either of the Response Options required in the UI radio button options. Please add a third option for when no response processing is required. Our current work-around is to smash the values in Postgres so that the code skips this logic. 

When "None" is specified, there should be no additional entry widget.

![image](https://github.com/drajer-health/eCRNow/assets/1240433/a4e25bbf-781f-4e48-a3d5-1f3d4ce141c4)

**Comment by kmarx** [comment]
We have to hack things in hc settings using space chars in order that we can successfully save them. We believe that this causes `ph_messages.response_processing_status` to get values of `FAILED_RR_CONVERSION_TO_DOCREF` or `FAILED_RR_SUBMISSION_TO_EHR`.
![image](https://github.com/drajer-health/eCRNow/assets/1240433/5b8858bc-ecab-4881-b99c-34bc0c5bc96d)

**Comment by VenkatSaiReddyTeegala** [comment]
Resolved as part of 3.1.4
