### ISSUE TITLE
Primary Language preference isn't honored

### ISSUE THREAD

**Issue by steve-hill-c** [drajer-health/eCRNow#547]
Based on the code link below it appears we only take the first iteration found for language. 

https://github.com/drajer-health/eCRNow/blob/b1ab750716063e0bc5f81bd9af5cd4498cc4f9a0/src/main/java/com/drajer/cdafromr4/CdaFhirUtilities.java#L249-L266

In R4 and R5 FHIR it is possible that value to have multiple entries and one may have the indicator as the patient's preferred language: http://hl7.org/fhir/R4/patient.html

<img width="958" alt="image" src="https://github.com/drajer-health/eCRNow/assets/67438399/ebae324a-7cb0-40e1-bf7a-8977a38e58b8">

This could lead to an issue with initial communication with a patient from the PHA either in writing or speech.

**Comment by nbashyam** [comment]
We will include this in the upcoming release.

**Comment by mmatiasalt** [comment]
This defect/request has been fixed in the 3.1.2 release.
