### ISSUE TITLE
Observation quantity prioritizing unit (display code) instead of code

### ISSUE THREAD

**Issue by steve-hill-c** [drajer-health/eCRNow#548]
This is similar to #483 : 

https://github.com/drajer-health/eCRNow/blob/b1ab750716063e0bc5f81bd9af5cd4498cc4f9a0/src/main/java/com/drajer/cdafromr4/CdaFhirUtilities.java#L1530-L1558

When processing quantities for Observation resources (Observation.component.valueQuantity) it appears the app will pull the getUnit before getCode. However, it should be honoring Code over Unit as Unit is a human readable display key and code is the actual codified unit:

<img width="971" alt="image" src="https://github.com/drajer-health/eCRNow/assets/67438399/a4146096-6884-45c9-9f16-6d731dd0488c">

<img width="1082" alt="image" src="https://github.com/drajer-health/eCRNow/assets/67438399/21d9f215-1e53-4add-bc6a-8dfcd9949174">

**Comment by nbashyam** [comment]
Will include it in the upcoming release.

**Comment by nbashyam** [comment]
Added to release 3.1.2

**Comment by BhoomikaRGopal** [comment]
can these changes be adaptable for ecrNow 2.0 aswell ?

**Comment by mmatiasalt** [comment]
This defect/request has been fixed in the 3.1.2 release.
