### ISSUE TITLE
County Support missing in CDA (Colorado reported)

### ISSUE THREAD

**Issue by rtomas-pinc** [drajer-health/eCRNow#550]
States (Colorado) have been asking for County (patient, facility, provider)

Ecrnow app doesn't support the field, only address, city, state, zip, country.  They would need a change also.

**Comment by nbashyam** [comment]
Will add to the release in 3.1.3 
Need to add to data needs spreadsheet also.

**Comment by mmatiasalt** [comment]
This will be included in 3.1.4 - please see https://github.com/drajer-health/eCRNow/issues/676

**Comment by VenkatSaiReddyTeegala** [comment]
Resolved as part of 3.1.4
