### ISSUE TITLE
Performing Lab (Utah) and Collection Date (Nevada)

### ISSUE THREAD

**Issue by rtomas-pinc** [drajer-health/eCRNow#551]
ECR support for Performing Lab.  We believe this is the Lab Location Name / Information to know where it was done.

Collection Date is also requested from Nevada

**Comment by nbashyam** [comment]
Please attach the loading queries.

**Comment by nbashyam** [comment]
No data supplied, closing the issue as no changes are anticipated.

**Comment by VenkatSaiReddyTeegala** [comment]
Resolved as part of 3.1.4
