### ISSUE TITLE
Issue with correctly populating address in eICR

### ISSUE THREAD

**Issue by bhuvansalanke** [drajer-health/eCRNow#553]
The assignedCustodian, representedOrganization, and serviceProviderOrganization are pulling back the incorrect address.

The problem is that the Organization resource returns multiple addresses for an organization and in the code we only pick the first one in the order. This is an issue, as the first address in the list is not always the business address of the organization.

Please consider using the work address from the list of addresses.
https://hl7.org/fhir/r4/valueset-address-use.html

https://github.cerner.com/ipaas/eCRNow/blob/master/src/main/java/com/drajer/cdafromr4/CdaFhirUtilities.java#L270

**Comment by nbashyam** [comment]
This is for 2.0 and 3.0 version, where the queries will have to be modified.

**Comment by Pramodshetty04** [comment]
Fix is added with unit test, this can be closed

**Comment by mmatiasalt** [comment]
This defect/request has been fixed in the 3.1.2 release.
