### ISSUE TITLE
eCRNOW 3.0 Adding suspended status in notification processing in notification_context 

### ISSUE THREAD

**Issue by Pramodshetty04** [drajer-health/eCRNow#555]
whenever the recurring timer or check reportable timer gets suspended based on the threshold value in the ersd, we need the status to be updated. (HELPS US IN RELAUNCHING API)

**Comment by nbashyam** [comment]
Will be included in 3.1.2

**Comment by nbashyam** [comment]
Notification Context table : notification processing status is set to suspended when the timers are suspended.

**Comment by mmatiasalt** [comment]
This defect/request has been fixed in the 3.1.2 release.
