### ISSUE TITLE
doseQuantity element is missing if dosageInstruction is not present in medication adminitration fhir resource

### ISSUE THREAD

**Issue by lakshman301195** [drajer-health/eCRNow#561]
doseQuantity element is missing if dosageInstruction is not present in medication administration fhir resource. The ideal expectation is that, it should populate an element with a nullFlavor.
<img width="523" alt="Screenshot 2023-08-11 at 11 47 17 AM" src="https://github.com/drajer-health/eCRNow/assets/121233760/b180beb6-8570-4c11-8d0a-815c47714193">

We have attempted to fix the issue on our side with the following change:
<img width="894" alt="Screenshot 2023-08-11 at 11 42 55 AM" src="https://github.com/drajer-health/eCRNow/assets/121233760/24d97a9c-3826-44b3-9271-35ac069d520b">

Please check and revert back, if this fix holds good.

**Comment by nbashyam** [comment]
Will add to 3.1.2 baseline.
