### ISSUE TITLE
"result organizer effectiveTime is preferred" issue (dq-resultOrganizer-effectiveTime-001) from product testing

### ISSUE THREAD

**Issue by AGABB** [drajer-health/eCRNow#562]
effTime not added in cdaResultGenerator. This is being logged as an issue during Product Testing. Observed in ModMed EMA.

https://github.com/drajer-health/eCRNow/blob/f5b0ba447ebc927f58d98c6ef21dc4ad65b1137f/src/main/java/com/drajer/cdafromr4/CdaResultGenerator.java#L144C5-L144C5

**Comment by nbashyam** [comment]
Data Quality team is investigating the issue.

**Comment by nbashyam** [comment]
Add to 3.1.4
