### ISSUE TITLE
dq-encompassingEncounter-providerTelecom-003 - Logged for ModMed EMA in Product Testing

### ISSUE THREAD

**Issue by AGABB** [drajer-health/eCRNow#563]
**Error Text**
Data Quality: The encompassing encounter provider telecom data element does not include an email value which is identified with prefix = "mailto:"

**Code (Only pulls ContactPoint.ContactPointSystem.PHONE):**
https://github.com/drajer-health/eCRNow/blob/master/src/main/java/com/drajer/cdafromr4/CdaFhirUtilities.java#L433

**Comment by nbashyam** [comment]
Added to 3.1.2 baseline

**Comment by mmatiasalt** [comment]
This defect/request has been fixed in the 3.1.2 release.
