### ISSUE TITLE
Lab Results Notes / Comment (Utah)

### ISSUE THREAD

**Issue by rtomas-pinc** [drajer-health/eCRNow#564]
Utah is asking for the Lab Results Notes section to be available in the CDA.  These are details I found in the CDA 1.1.1 Volume 2 for the Results Sections with "Text" as the location for this.  The are other "Text" sections to look at for samples if there are questions.

![image](https://github.com/drajer-health/eCRNow/assets/15131757/17949b1d-d280-46b9-9bbb-9655452fc5eb)

**Comment by nbashyam** [comment]
Text element is already included in the section, not sure what the specific issue is. Can you please clarify.

**Comment by nbashyam** [comment]
No change, data is already being populated.

**Comment by VenkatSaiReddyTeegala** [comment]
Resolved as part of 3.1.4
