### ISSUE TITLE
Empty tbody in social history observation section in CDA - XML validation error

### ISSUE THREAD

**Issue by bhuvansalanke** [drajer-health/eCRNow#565]
We are seeing validation error when the tbody is empty for social history

`
<component>
				<section>
					<templateId root="2.16.840.1.113883.10.20.22.2.17"/>
					<templateId extension="2015-08-01" root="2.16.840.1.113883.10.20.22.2.17"/>
					<code code="29762-2" codeSystem="2.16.840.1.113883.6.1" codeSystemName="LOINC" displayName="Social History"/>
					<title>SOCIAL HISTORY</title>
					<text>
						<table border="1" width="100%">
							<thead>
								<tr>
									<th>Social History Observation</th>
									<th>Social History Observation Result</th>
								</tr>
							</thead>
							<tbody/>
						</table>
					</text>
				</section>
			</component>
`
![MicrosoftTeams-image](https://github.com/drajer-health/eCRNow/assets/5147301/78046914-06d1-48b0-8818-cfd06fb05066)

In the investigation found that, the occupation observation returned a boolean type, and it is not accounted in the qualification which skips adding it to the tbody here:

https://github.com/drajer-health/eCRNow/blob/master/src/main/java/com/drajer/cdafromr4/CdaSocialHistoryGenerator.java#L128-L130

**Comment by nbashyam** [comment]
What does the BooleanType mean for OccupationObservation ?

**Comment by bhuvansalanke** [comment]
It looks like a Questionnaire with Yes/No response.

**Comment by nbashyam** [comment]
Added to 3.1.3
