### ISSUE TITLE
Need delete api for Notification Context

### ISSUE THREAD

**Issue by saloniswaroop** [drajer-health/eCRNow#567]
In 2.0 there was a delete api for launchdetails:
@DeleteMapping(value = "/api/launchDetails")
  public String deleteLaunchDetails()

https://github.com/drajer-health/eCRNow/blob/master/src/main/java/com/drajer/sof/launch/LaunchController.java#L664

Similar api is required in 3.0 to delete notificationContext.

**Comment by umamaheshwari27** [comment]
Please share us an estimated timeline by which APi will be ready. So we can update our internal timelines for release. We are using these apis for ecase post-deploy-tests.

**Comment by mmatiasalt** [comment]
This defect/request has been fixed in the 3.1.2 release.
