### ISSUE TITLE
Need delete api for phMessage and HealthcareSettings

### ISSUE THREAD

**Issue by umamaheshwari27** [drajer-health/eCRNow#568]
In 2.0 there was a delete api for eicrData and clientdetails:
1)@DeleteMapping(value = "/api/clientDetails")
  public ResponseEntity<String> deleteClientDetails()
    https://github.cerner.com/ipaas/eCRNow/blob/6b6a74eb9daf2db3cedcbf3e08e2c224e830d01c/src/main/java/com/drajer/sof/launch/ClientDetailsController.java#L103

2) @DeleteMapping(value = "/api/eicr")
  public ResponseEntity<String> deleteEicr()
  https://github.cerner.com/ipaas/eCRNow/blob/6b6a74eb9daf2db3cedcbf3e08e2c224e830d01c/src/main/java/com/drajer/ecrapp/controller/EicrController.java#L217

Similar api is required in 3.0 to delete phMessage and HealthcareSetting.

**Comment by umamaheshwari27** [comment]
Please share us an estimated timeline by which APi will be ready. So we can update our internal timelines for release.

**Comment by mmatiasalt** [comment]
This defect/request has been fixed in the 3.1.2 release.
