### ISSUE TITLE
Need for mapping the Emergency Contact information in the eICR report

### ISSUE THREAD

**Issue by bhuvansalanke** [drajer-health/eCRNow#569]
![image](https://github.com/drajer-health/eCRNow/assets/5147301/75705b7e-69fd-4a4a-8858-26054287a1ed)

**Comment by bhuvansalanke** [comment]
@nbashyam Found the commit that has the implementation.
https://github.com/drajer-health/eCRNow/commit/4eba398c486df02cab4ed10a838e173066030d33

**Comment by mmatiasalt** [comment]
This defect/request has been fixed in the 3.1.2 release.
