### ISSUE TITLE
Guardian role code not populated in ecrNow

### ISSUE THREAD

**Issue by medhost-chara** [drajer-health/eCRNow#574]
The specification documents include a guardian role code however it does not look like this is being populated in the ecrNow application. Is this planned for any future release?

Example
`             <guardian>
                 <code code="POWATT" displayName="Power of Attorney"
 codeSystem="2.16.840.1.113883.1.11.19830" codeSystemName="ResponsibleParty" />
                 <addr use="HP">`
             

<img width="1061" alt="GuardianRoleCode" src="https://github.com/drajer-health/eCRNow/assets/46822924/ee6e2916-f7ed-48db-bd1a-ac841768b158">

It is subsequently also not present on the example document eCR-TC-1_DiagnosisSNOMED CT.xml which includes a guardian.

**Comment by mmatiasalt** [comment]
@medhost-chara , Thank you for your patience. Are you able to please provide loading queries for this issue for our team to review? Thank you.

**Comment by medhost-chara** [comment]
@mmatiasalt  we are working on implementing the guardian contact in fhir and we had a question about the roles codes and how ecrnow would pull them so we just reviewed the ecrnow code base to validate how you are pulling data and utilizing the role codes and noticed that I could not find the logic for where these are implemented.

I see the guardian is built there but do not see logic for implementation of a role code
https://github.com/drajer-health/eCRNow/blob/master/src/main/java/com/drajer/cdafromdstu2/Dstu2CdaHeaderGenerator.java#L709

nor do I see it implemented here:
https://github.com/drajer-health/eCRNow/blob/master/src/main/java/com/drajer/cdafromr4/CdaHeaderGenerator.java#L985

Please correct me if I am overlooking.

**Comment by nbashyam** [comment]
Add to 3.1.4

**Comment by VenkatSaiReddyTeegala** [comment]
Resolved as part of 3.1.4
