### ISSUE TITLE
Conditions in Entered-in-error verificationStatus included in eICR

### ISSUE THREAD

**Issue by VictoriaVaughn** [drajer-health/eCRNow#577]
Conditions voided/deleted within the EHR have a verificationStatus of "entered-in-error" and no clinicalStatus.

http://hl7.org/fhir/us/core/STU4/StructureDefinition-us-core-condition.html

"*The status element has the following constraints: SHALL be present if verification status is not entered-in-error and SHALL NOT be present if verification Status is entered-in-error." 

eCR Now code seems to be checking for clinicalStatus only, so these records mentioned above are pulled into the eICR as "Active" problems since the clinicalStatus is Null and not Active, Resolved, or Remission.  

![CdaProblemGenerator](https://github.com/drajer-health/eCRNow/assets/145029157/48bd1b79-483a-4802-aad9-100cc119ba62)

**Comment by nbashyam** [comment]
Add verificationStatus to the filter criteria. Also look at other resources with multiple status values which may fall into the same category.

**Comment by VictoriaVaughn** [comment]
After merging in v3.1.2, it does not appear this issue is resolved.

Patient Problem G21.2 was added and then Voided within the EHR:

![image](https://github.com/drajer-health/eCRNow/assets/145029157/c07139e4-1b1b-4e7d-b96b-22526d0d8c56)

The verification status correctly shows in FHIR as expected as entered-in-error:

![image](https://github.com/drajer-health/eCRNow/assets/145029157/081da71b-fb32-468b-b526-1bc8a5f980d8)

While it's not listed in the initial problem list, the code is still present further down in the eICR and listed as a triggering code:

![image](https://github.com/drajer-health/eCRNow/assets/145029157/e7cf3efe-3ed3-4bd6-aec3-5bbff3eed6ca)

Attaching the trigger query and loading query:
[2024-01-22T15_18_49,000000000+00_00_TriggerQueryBundle_2754802_2754946.json](https://github.com/drajer-health/eCRNow/files/14012318/2024-01-22T15_18_49.000000000%2B00_00_TriggerQueryBundle_2754802_2754946.json)
[2024-01-22T15_18_53,000000000+00_00_LoadingQueryBundle_2754802_2754946.json](https://github.com/drajer-health/eCRNow/files/14012321/2024-01-22T15_18_53.000000000%2B00_00_LoadingQueryBundle_2754802_2754946.json)

The eicr xml is not a supported file type - adding as .JSON:
[2024-01-22T15_18_53,000000000+00_00_create-report_2754802_439bd3a8-5dc4-4737-89cb-9557fd097eb8.json](https://github.com/drajer-health/eCRNow/files/14012396/2024-01-22T15_18_53.000000000%2B00_00_create-report_2754802_439bd3a8-5dc4-4737-89cb-9557fd097eb8.json)

**Comment by VictoriaVaughn** [comment]
Potential cause? Shouldn't entered-in-error also reference the verification status URL and not the clinical status URL? 


![image](https://github.com/drajer-health/eCRNow/assets/145029157/bfd7ce6e-bc25-4679-b28e-acd82b1a574c)

https://github.com/drajer-health/eCRNow/blob/3.1.2/src/main/java/com/drajer/bsa/ehr/service/impl/EhrFhirR4QueryServiceImpl.java

**Comment by nbashyam** [comment]
Updated to 3.1.3 baseline.

**Comment by nbashyam** [comment]
Fixed in 3.1.3

**Comment by VictoriaVaughn** [comment]
@nbashyam  We are not seeing that this is resolved after upgrading to 3.1.3. Can this issue be re-opened and reviewed?
