### ISSUE TITLE
Expand Condition displayName to allow condition.code.text

### ISSUE THREAD

**Issue by VictoriaVaughn** [drajer-health/eCRNow#578]
Currently, the Condition.code.coding.display is the only value that will populate the Problem name within the eICR. Otherwise, the Unknown value will display.

![Condition Display Name](https://github.com/drajer-health/eCRNow/assets/145029157/cc7a3f94-e858-4033-b8db-5d36e0da70f6)
![Condition Display Name 2](https://github.com/drajer-health/eCRNow/assets/145029157/a53bd21b-8e39-4e05-a0a2-fc6b35cb066c)

**We would like to request that the Condition.code.text field also be allowed as an input for the this logic to display in the problem list section.**

http://hl7.org/fhir/us/core/STU4/StructureDefinition-us-core-condition.html
![image](https://github.com/drajer-health/eCRNow/assets/145029157/c2e7f5f5-b7f9-4110-9226-474774806873)

**Comment by nbashyam** [comment]
Use codeableconcept.text element when the displayname is not present in the coding element.

**Comment by VictoriaVaughn** [comment]
Discussed in weekly call with Dragon for this to be implemented.

**Comment by nbashyam** [comment]
Fixed in 3.1.3
