### ISSUE TITLE
Request to support additional FHIR travel history/observations codes in ecrnow, Refer code list in the comment

### ISSUE THREAD

**Issue by Pramodshetty04** [drajer-health/eCRNow#579]
Last travel within 21 day, Alternate Display: Last travel within 21 days
Alternate Display: Last travel within 21 days
History of travel within past twenty-one days (situation)
SNOMED CT 46541000175105

Last travel within 7 days, Alternate Display: Last travel within 7 days
History of travel within past seven days (situation)
SNOMED CT 46551000175107

Last travel within 14 day, Alternate Display: Last travel within 14 days
Alternate Display: Last travel within 14 days History of travel within past fourteen days (situation)
SNOMED CT 46531000175104

Let me know if this can be added in ecnow 2.0 and 3.0 asap?

**Comment by VenkatSaiReddyTeegala** [comment]
Resolved as part of 3.1.4
