### ISSUE TITLE
Schematron URL on README.md Invalid

### ISSUE THREAD

**Issue by deb-hall-alt** [drajer-health/eCRNow#582]
The README.md page says this:

>SCHEMATRON FILE LOCATION

>Change the Schematron File location to reflect where to find the actual eICR Schematron. The schematron file can be downloaded from https://gforge.hl7.org/gf/project/pher/scmsvn/?action=browse&path=%2Ftrunk%2FPHCASERPT_eICR%2Fschematron%2F with the appropriate HL7 authorization.

**However, that gforge URL is no longer valid.** 

The correct URL for the eICR v1.1 Schematron is here: https://github.com/HL7/CDA-phcaserpt-1.1.1/tree/main/validation

In case you need it, the eICR v3.1 Schematron is here: https://github.com/HL7/CDA-phcaserpt-1.3.0/tree/CDA-phcaserpt-1.3.1/validation

**Comment by nbashyam** [comment]
Fixed in 3.1.3
