### ISSUE TITLE
Observing 35 Test failures after pulling changes from 3.1.2 branch

### ISSUE THREAD

**Issue by Nikiitha** [drajer-health/eCRNow#585]
After pulling the code changes from 3.1.2 branch in github, we are noticing 35 test case failures
Fixing these test cases is essential to move the bug fixes to production. Kindly expedite.

PFB the test Failures After Pulling the Code:

15:28:00 [ERROR] Errors:
15:28:00 [ERROR] ChronicBPECSDTest.test[ChronicDSControllingBloodPressure/bp-trigger-condition-missing] ? IllegalState
15:28:00 [ERROR] ChronicBPECSDTest.test[ChronicDSControllingBloodPressure/bp-trigger-condition-out] ? IllegalState
15:28:00 [ERROR] ChronicBPECSDTest.test[ChronicDSControllingBloodPressure/bp-trigger-in] ? IllegalState
15:28:00 [ERROR] ChronicBPECSDTest.test[ChronicDSControllingBloodPressure/bp-trigger-out] ? IllegalState
15:28:00 [ERROR] DiabetesECSDTest.test[ChronicDSDiabetesPoorControl/diabetes-trigger-condition-missing] ? IllegalState
15:28:00 [ERROR] DiabetesECSDTest.test[ChronicDSDiabetesPoorControl/diabetes-trigger-condition-out] ? IllegalState
15:28:00 [ERROR] DiabetesECSDTest.test[ChronicDSDiabetesPoorControl/diabetes-trigger-in] ? IllegalState
15:28:00 [ERROR] DiabetesECSDTest.test[ChronicDSDiabetesPoorControl/diabetes-trigger-out] ? IllegalState
15:28:00 [ERROR] ErsdV2BundleTest.test[PlanDefinition_eRSD_Instance_Example/NotTriggered] ? IllegalState
15:28:00 [ERROR] FhirPathTest.test[FhirPath/today_or_now] ? IllegalState Failed to load Applica...
15:28:00 [ERROR] RuleFiltersERSDCQLOnlyTest.test[PlanDefinition_eRSD_Instance_CqlOnly/NotTriggered] ? IllegalState
15:28:00 [ERROR] RuleFiltersERSDFhirPathOnlyTest.test[PlanDefinition_eRSD_Instance_FhirPathOnly/ex-trigger-all-criteria-missing] ? IllegalState
15:28:00 [ERROR] RuleFiltersERSDFhirPathOnlyTest.test[PlanDefinition_eRSD_Instance_FhirPathOnly/ex-trigger-all-criteria-out] ? IllegalState
15:28:00 [ERROR] RuleFiltersERSDFhirPathOnlyTest.test[PlanDefinition_eRSD_Instance_FhirPathOnly/ex-trigger-encounter-inprogress-out] ? IllegalState
15:28:00 [ERROR] RuleFiltersERSDFhirPathOnlyTest.test[PlanDefinition_eRSD_Instance_FhirPathOnly/ex-trigger-in] ? IllegalState
15:28:00 [ERROR] RuleFiltersERSDFhirPathOnlyTest.test[PlanDefinition_eRSD_Instance_FhirPathOnly/ex-trigger-out] ? IllegalState
15:28:00 [ERROR] SeenPatientsECSDTest.test[ChronicDSSeenPatients/seen-patients-no-trigger-in] ? IllegalState
15:28:00 [ERROR] SeenPatientsECSDTest.test[ChronicDSSeenPatients/seen-patients-trigger-in] ? IllegalState
15:28:00 [ERROR] EicrDaoTest.deleteEicr ? IllegalState Failed to load ApplicationContext
15:28:00 [ERROR] EicrDaoTest.getEicrAndRRDataByXRequestId ? IllegalState Failed to load Applica...
15:28:00 [ERROR] EicrDaoTest.getEicrByCoorrelationId ? IllegalState Failed to load ApplicationC...
15:28:00 [ERROR] EicrDaoTest.getEicrByDocId ? IllegalState Failed to load ApplicationContext
15:28:00 [ERROR] EicrDaoTest.getEicrById ? IllegalState Failed to load ApplicationContext
15:28:00 [ERROR] EicrDaoTest.getMaxVersionId ? IllegalState Failed to load ApplicationContext
15:28:00 [ERROR] EicrDaoTest.saveOrUpdateEicr ? IllegalState Failed to load ApplicationContext
15:28:00 [ERROR] ClientDetailsDaoTest.deleteClientDetails ? IllegalState Failed to load Applica...
15:28:00 [ERROR] ClientDetailsDaoTest.getAllClientDetails ? IllegalState Failed to load Applica...
15:28:00 [ERROR] ClientDetailsDaoTest.getClientDetailsById ? IllegalState Failed to load Applic...
15:28:00 [ERROR] ClientDetailsDaoTest.getClientDetailsByUrl ? IllegalState Failed to load Appli...
15:28:00 [ERROR] ClientDetailsDaoTest.saveClientDetails ? IllegalState Failed to load Applicati...
15:28:00 [ERROR] LaunchDetailsDaoTest.deleteLaunchDetails ? IllegalState Failed to load Applica...
15:28:00 [ERROR] LaunchDetailsDaoTest.getAuthDetailsById ? IllegalState Failed to load Applicat...
15:28:00 [ERROR] LaunchDetailsDaoTest.getLaunchDetailsByPatientAndEncounter ? IllegalState Fail...
15:28:00 [ERROR] LaunchDetailsDaoTest.getLaunchDetailsByState ? IllegalState Failed to load App...
15:28:00 [ERROR] LaunchDetailsDaoTest.saveLaunchDetails ? IllegalState Failed to load Applicati...
15:28:00 [ERROR] Tests run: 499, Failures: 0, Errors: 35, Skipped: 3

**Comment by lakshman301195** [comment]
After updating application-test.properties ecrNow log file location, issue got resolved. Please close the issue.
