### ISSUE TITLE
getValidServiceRequests Should Exclude Entered-in-error and Revoked Statuses

### ISSUE THREAD

**Issue by VictoriaVaughn** [drajer-health/eCRNow#586]
While we were reviewing the CdaPlanofTreatmentGenerator, we saw that there was a recent commit that removed the check for the status of the record.

https://github.com/drajer-health/eCRNow/commit/5f51392cc4d21dfe3b0bca677d93787a06b49dc9#diff-c9a636806817ff8325857e3c07382572bf3cd4ca5f61dc78f5e268f2bd5b46e2

![image](https://github.com/drajer-health/eCRNow/assets/145029157/ac576bf0-84e9-487b-9fe9-e768da5ad922)

Our concern is that this will then allow the Revoked and Entered-in-error statuses to be added to the eICR when they should not be.

http://build.fhir.org/ig/HL7/case-reporting/StructureDefinition-eicr-servicerequest.html

**Comment by bhuvansalanke** [comment]
if you are using v3.0 it will be filtered here: 
https://github.com/drajer-health/eCRNow/blob/master/src/main/java/com/drajer/bsa/ehr/service/impl/EhrFhirR4QueryServiceImpl.java#L1134

**Comment by VictoriaVaughn** [comment]
Thank you for pointing us to the new location with this logic. 

When reviewing we noticed that not only are "Revoked" and "Entered-in-error" status filtered out but also "Unknown" 

 (sr.getStatus() == ServiceRequestStatus.REVOKED
              || sr.getStatus() == ServiceRequestStatus.ENTEREDINERROR
              || sr.getStatus() == ServiceRequestStatus.UNKNOWN))

Can you explain why Unknown is being filtered out? We were expecting this status to be available.

**Comment by nbashyam** [comment]
Victoria - How often the "Unknown" status is used in-lieu of the other more appropriate statuses ?

**Comment by VictoriaVaughn** [comment]
We have common situations where our system knows that there is a valid record, but it's not able to differentiate between "Active" , "Draft", or "Completed" , so we send them as "Unknown".

**Comment by nbashyam** [comment]
Different vendors are using the Unknown status differently, it is recommended that you use Active, Draft or completed as you indicated above instead of Unknow.

**Comment by nbashyam** [comment]
Latest changes to the Plan of Treatment generation is present in 3.1.5
