### ISSUE TITLE
ServiceProviderOrganization field is always empty in EICR

### ISSUE THREAD

**Issue by lakshman301195** [drajer-health/eCRNow#589]
We have the same ID for both the resources Location & ServiceProviderOrganization. So the app logic checks for Unique ID in the Hashmap function and skips populating ServiceProviderOrganization as an organization resource.

Expected Fix:
The logic which checks if a resource is already present has to be modified by checking for both ID and resourcetype instead of ID alone.
kd.containsResourceWithId("Test-ID") function to be modified as kd.containsResourceWithId("Test-ID", "Resourcetype")

**Comment by mmatiasalt** [comment]
This defect/request has been fixed in the 3.1.2 release.
