### ISSUE TITLE
Workflow is not re initiated if a patients discharge is cancelled_ can this be handled in 3.1.2?

### ISSUE THREAD

**Issue by Pramodshetty04** [drajer-health/eCRNow#592]
Question around eCR Workflow for "cancelled discharge on an encounter:"
    Hoping someone can help address this question from a client! 

Tested in ecrnow 2.0 version below is what we found:

Looks like when encounter had end date, it scheduled the close out action. Later when the discharge was cancelled and when the close out action actually ran, it determined the encounter was not closed anymore but it did not execute the close out action, there is some issue that puts it in state where it does not execute anymore.

Kindly address

**Comment by mmatiasalt** [comment]
Hello @Pramodshetty04 , 

Thanks so much for your patience. Our team was able to confirm that relaunching API is possible but not in v2 of the app. 

Regards,

**Comment by nbashyam** [comment]
closing the issue as no changes required.

**Comment by VenkatSaiReddyTeegala** [comment]
Resolved as part of 3.1.4
