### ISSUE TITLE
Incorrect coding system is used for filling healthcarefacility code

### ISSUE THREAD

**Issue by bhuvansalanke** [drajer-health/eCRNow#594]
The application is sending a different code system as OID 2.16.840.1.113883.4.642.3.414 
https://build.fhir.org/valueset-organization-type.html and sending the code as "prov".

<code code="prov" codeSystem="2.16.840.1.113883.4.642.3.414" codeSystemName="organization-type" displayName="Healthcare Provider"><translation code="prov" codeSystem="2.16.840.1.113883.4.642.3.414" codeSystemName="organization-type" displayName="Healthcare Provider"/>
<translation code="prov" codeSystem="2.16.840.1.113883.4.642.3.414" codeSystemName="organization-type" displayName="Healthcare Provider"/>
</code>

But as per the CDA 1.1 Specs, the app should send the urn:oid:2.16.840.1.113883.1.11.17660 (ServiceDeliveryLocationRoleType).
![image](https://github.com/drajer-health/eCRNow/assets/5147301/bf19f9cd-323a-4b4d-acc0-9bef1b795852)

**Comment by mmatiasalt** [comment]
@bhuvansalanke resolution for this issue is to be included in V3.1.7 for release in Dec 2024.

**Comment by nbashyam** [comment]
Closing this ticket as it has already been fixed in the baseline.
