### ISSUE TITLE
Issue Reported from PHA for Patient ID

### ISSUE THREAD

**Issue by lakshman301195** [drajer-health/eCRNow#599]
Patient ID (ClinicalDocument/recordTarget/patientRole/id @extension) has the full FHIR API URL being displayed at this location. Could you please remove so only the part that is the patient's MRN is displayed in this location? It is also being populated on the HTML this way. Our end users will use the MRN if they need to contact the healthcare facility for any reason, so it is important that an accurate MRN is provided.

**Comment by nbashyam** [comment]
Included in 3.1.2

**Comment by lakshman301195** [comment]
Can you specify the Commit-ID to check this?

**Comment by lakshman301195** [comment]
We have verified the fix and it works fine. Please close the issue.
