### ISSUE TITLE
Results section is missing result values.

### ISSUE THREAD

**Issue by lakshman301195** [drajer-health/eCRNow#602]
Results section is missing result values.

**Comment by lakshman301195** [comment]
In the generated EICR, actual there is a table section which lists all results first, followed by a section which details each lab result entry present in the table. The PHA has reported the Value field is missing in the table. But in the section, where each individual lab result gets added, the value element is present. 

Attached screenshots and a sample response.
<img width="684" alt="Screenshot 2023-11-02 at 3 09 55 PM" src="https://github.com/drajer-health/eCRNow/assets/121233760/ce88f7d2-e5e0-4fb3-a270-24f262f058c7">
<img width="880" alt="Screenshot 2023-11-02 at 3 10 58 PM" src="https://github.com/drajer-health/eCRNow/assets/121233760/5c5ec2a6-83e5-4797-b194-ccba7d6a0b33">

[result_section.json](https://github.com/drajer-health/eCRNow/files/13237218/result_section.json)

**Comment by nbashyam** [comment]
Is this still an issue Lakshman ?

**Comment by mmatiasalt** [comment]
@lakshman301195 Following up to see is this still an issue? Thank you.

**Comment by lakshman301195** [comment]
Please find the additional details as below:

Have provided examples of Observation FHIR Resource when the Values in the Results Section gets populated (1 example) and when it doesn't (5 examples).
<img width="713" alt="Screenshot 2024-01-08 at 6 13 16 PM" src="https://github.com/drajer-health/eCRNow/assets/121233760/e5db6b9e-04d7-4c52-a01d-371add90ff78">

Please analyse the zip for the scenarios.

[Results_Issue.zip](https://github.com/drajer-health/eCRNow/files/13860183/Results_Issue.zip)

**Comment by mmatiasalt** [comment]
This defect/request has been fixed in the 3.1.2 release.

**Comment by lakshman301195** [comment]
@mmatiasalt 

This is still an open issue. Attached reports for failing cases on Jan 8? Was that zip analysed?

**Comment by nbashyam** [comment]
Fixed in 3.1.3
