### ISSUE TITLE
Problem List section is missing dates.

### ISSUE THREAD

**Issue by lakshman301195** [drajer-health/eCRNow#603]
Problem List section is missing dates.

**Comment by lakshman301195** [comment]
In the generated EICR, actual there is a table section which lists all problems first, followed by a section which details each problem in the table. The PHA has reported the Date to be added in the table. The table currently has 2 columns ( <th>Problem or Diagnosis</th>,<th>Problem Status</th>) Request to add one more column with a date field as well.

We have verified from the FHIR Response if date is present it is getting populated in the effectiveTime low/high element.

**Comment by lakshman301195** [comment]
Pulling the latest code from Branch 3.1.2 fixes this. Kindly close the issue.

**Comment by mmatiasalt** [comment]
This defect/request has been fixed in the 3.1.2 release.
