### ISSUE TITLE
Update auth token validity check to be configurable

### ISSUE THREAD

**Issue by martha-garasky** [drajer-health/eCRNow#605]
The eCR app currently has a check to see if an auth token is about to expire before it starts any round of queries for a specific profile. However, it only checks to make sure that the token is not going to expire within the next 20 seconds.  It seems like this is enough time for most things, but there are a few situations where this 20 second buffer is not enough time to complete all the querying.

Specifically, this request is to allow the hardcoded 20 seconds to become a configurable value within the [hasValidAccessToken function](https://github.com/drajer-health/eCRNow/blob/master/src/main/java/com/drajer/bsa/model/KarProcessingData.java#L695)

**Comment by mmatiasalt** [comment]
Hi @martha-garasky, We have reviewed your request and find the app is behaving as expected. Is there anything you are observing that is causing you to believe it is working otherwise? If you can please provide examples/screenshots that would be helpful. Thank you.

**Comment by martha-garasky** [comment]
Understood that it's behaving as expected. This was more of an enhancement request to make that check of 20 seconds configurable so users can choose a different amount of time.

**Comment by nbashyam** [comment]
Add to 3.1.3 baseline

**Comment by nbashyam** [comment]
Fixed in 3.1.6
