### ISSUE TITLE
eICR Shows Trigger Codes in Incorrect Sections

### ISSUE THREAD

**Issue by VictoriaVaughn** [drajer-health/eCRNow#608]
We have noticed that when documenting LOINCs within the "observation-lab" and "servicerequest" resources we are seeing the trigger codes being used interchangeably between the sections unexpectedly.

Observation-lab = Lab Observation Test Name in RCTC sheets = RESULTS section in the eICR
ServiceRequest = Lab Order Test Name in RCTC sheets = Plan of Treatment section in the eICR

We documented LOINC 34941-5 on a patient. eCR Now was able to match the code and generate a case report. However, it is listed as trigger under the "RESULTS' section within the eICR. This code is only listed under Lab  Order Test Name section of ERSD, so we were not expecting it to pull into the "RESULTS" section as a trigger since this code is not a part of that value set. Example attached.

We've also seen the opposite is true. When a Lab Observation Test Name trigger code is documented, it can also be pulled into the "Plan of Treatment" section in the eICR instead of the "RESULTS" section.

Should there be a check for the trigger code to be a part of the specific section's value set before it is marked as a trigger within the eICR?

[LOINC Issue.zip](https://github.com/drajer-health/eCRNow/files/13244260/LOINC.Issue.zip)

**Comment by nbashyam** [comment]
Check with AIMS team to see if there any side effects as the code is working as designed. Close the ticket if there are no side effects.
