### ISSUE TITLE
R4Bundle: Duplicate Practitioner in the Bundle

### ISSUE THREAD

**Issue by AnanthaKrishnaV** [drajer-health/eCRNow#61]
Logic at line[1] will add duplicate Practitioner to the Bundle as Encounter may contain same Practitioner multiple time with different relationship. This would eventually cause duplicate in CDA.

[1]-https://github.com/drajer-health/eCRNow/blob/master/src/main/java/com/drajer/sof/utils/R4ResourcesData.java#L721

Add unique Practitioner to the bundle.

**Comment by nbashyam** [comment]
Updated the baseline with fixes.
