### ISSUE TITLE
Medication Name is Placed 'Unknown' in eICR

### ISSUE THREAD

**Issue by ahmedkunwar** [drajer-health/eCRNow#610]
eCR App Version: 3.1.1

Issue:
We are getting medication name Unknown under Medications Administered section of eICR report.

On further investigation we found that the medication name is populated on the basis of one of the following resources: Medication Statement, Medication Request or Medication Administration.

We are using Medication Request and still it appears Unknown.
 
![eICR](https://github.com/drajer-health/eCRNow/assets/88528080/4f7b9b13-6fb2-445a-b543-029e4bfc67b2)

**Comment by ahmedkunwar** [comment]
[LoadingQueryBundle_18864_20485.json](https://github.com/drajer-health/eCRNow/files/13300657/LoadingQueryBundle_18864_20485.json)

Kindly find the Loading Query File attached

**Comment by mmatiasalt** [comment]
@ahmedkunwar This issue is under review and is related to the way athena is presenting the data. We will provide updates as we have them. Thank you

**Comment by ahmedkunwar** [comment]
Any update?

**Comment by nbashyam** [comment]
Fixed in 3.1.3
