### ISSUE TITLE
The author id data element has no @extension attribute in addAdditionalAuthorXml function

### ISSUE THREAD

**Issue by lakshman301195** [drajer-health/eCRNow#613]
1. The author id data element has no @extension attribute in **addAdditionalAuthorXml** function. Request to add extension attribute.
2. author assignedAuthoringDevice data element is not present - Reported by PHA

**Comment by nbashyam** [comment]
1. Need more information on what the extension attribute will contain and how the app will get it , from which resource ? 
2. There is a configurable property for adding Authoring Device in the App. Please use that to populate the Authoring Device.

**Comment by nbashyam** [comment]
Will discuss on 12/4/2023 with vendor.

**Comment by nbashyam** [comment]
DQ Report will be updated to validate that the primary author will have an extension when appropriate, however the additional authors related to AuthoringDevice, Software Version and Vendor name will not be required to have an extension.

**Comment by mmatiasalt** [comment]
@lakshman301195 

Please find the communication that should be shared with the PHAs that reported this issue: 
For any data element that is an /id and throws a schematron error “has no @extension attribute” this really requires follow up with the vendor/HCO. This schematron rule flaggs an identifier that only has a @root attribute. A @root attribute alone may be enough to convey uniqueness in the id, but many senders have a common @root oid and identify uniqueness via a distinct @extension attribute. Follow up will require either looking at some example identifiers to see if the root is unique or ask the sender to confirm if the @root is sufficient to uniquely identify. This is not an app issue

Thank you!
