### ISSUE TITLE
Patient Re-Launch API Should Support the new Ambulatory Reporting Path

### ISSUE THREAD

**Issue by VictoriaVaughn** [drajer-health/eCRNow#615]
The Patient Re-Launch API is only respecting the "normal reporting" path that existed prior to eRSD version 1.2 being released where the new "ambulatory reporting" path was introduced. 

The patient re-launch functionality should be able to support all encounter classes. 

We expect the majority of our Encounters to be 'AMB' encounters, so we need this support added in order to launch eCR Now successfully in many scenarios where important clinical information (potentially including trigger codes) is added to patient encounters more than 72 hours after they have been checked out.

For example, it is extremely common for Lab Results to be returned back into the EHR more than 72 hours after the encounter. And given that there are almost 10,000 possible trigger codes within the Lab Observation Test Name trigger list, we expect that we will need to use the patient re-launch API commonly as well, so we greatly need this ambulatory path supported.

**Comment by nbashyam** [comment]
Add for discussion on Wednesday 11/29/2023.
Write up the Relaunch / AMB / Inpatient path implementation in the App documentation.

**Comment by VenkatSaiReddyTeegala** [comment]
Resolved as part of 3.1.4
