### ISSUE TITLE
Race Code element is NULLFLAVOR if the FHIR Response has 'Other Race'

### ISSUE THREAD

**Issue by lakshman301195** [drajer-health/eCRNow#620]
While going through the logic for generating racecode element in patient details, found that the ECRNOW App filters out only if the url of us-core-race is ombCategory.
<img width="514" alt="Screenshot 2023-11-24 at 3 52 43 PM" src="https://github.com/drajer-health/eCRNow/assets/121233760/49dd06fb-a607-4a77-b8ca-73be159c7d9a">

If the FHIR response gets returned as 'Other Race' it is getting populated as NULLFLAVOR.
<img width="590" alt="Screenshot 2023-11-24 at 3 55 38 PM" src="https://github.com/drajer-health/eCRNow/assets/121233760/b7109db2-cd8a-4c63-b264-fe4aacdb012f">

**Comment by nbashyam** [comment]
In Analysis

**Comment by nbashyam** [comment]
In CDA eICR 1.1, the Other Race category is not allowed for Race Code, hence it has to be some kind of a nullFlavor.

**Comment by ctobias84** [comment]
note that race category OTH and ASKU should output as NULL under current specifications

**Comment by ctobias84** [comment]
Adding sample files of Race Category OTH and ASKU queries
[Race_OTH_and_ASKU_Loadingquery.zip](https://github.com/drajer-health/eCRNow/files/13968530/Race_OTH_and_ASKU_Loadingquery.zip)

**Comment by nbashyam** [comment]
In CDA eICR R1.1, the Race Category can only contain 5 values apart from Null Flavors. Other is not an allowed value, hence cannot be included as a code. That is why it is a nullFlavor currently. 
<img width="861" alt="Screen Shot 2024-01-22 at 8 36 51 AM" src="https://github.com/drajer-health/eCRNow/assets/4450817/d042cca9-38f8-4fc8-95c6-cf46921b7527">

**Comment by nbashyam** [comment]
Closed for CDA eICR R1.1

**Comment by mmatiasalt** [comment]
@ctobias84 I have opened issue #648 to address the secondary portion of the ticket. Can you please confirm that this issue is still occurring? Thank you.
