### ISSUE TITLE
dq-encompassingEncounter-healthCareFacility-004 (Encompassing encounter healthcare facility code data element and translation are not in ValueSet ServiceDeliveryLocationRoleType)

### ISSUE THREAD

**Issue by lakshman301195** [drajer-health/eCRNow#621]
dq-encompassingEncounter-healthCareFacility-004 (Encompassing encounter healthcare facility code data element and translation are not in ValueSet ServiceDeliveryLocationRoleType)

Additional Info from PHA: This code   indicates the type of facility where the encounter occurred.  This code should be selected from ValueSet   ServiceDeliveryLocationRoleType (2.16.840.1.113883.1.11.17660).  This value set contains a constrained set   of values drawn from code system HL7 Role Code   (2.16.840.1.113883.5.111).  Commonly   used values are 'HOSP' (Hospital), 'HU' (Hospital Unit), 'OF' (Outpatient   facility), 'ER' (Emergency Room).

**Comment by nbashyam** [comment]
In Analysis

**Comment by lakshman301195** [comment]
Can you check these two files

https://github.com/drajer-health/eCRNow/blob/668accb3639d60118013da5709490f38aeec20d9/src/main/java/com/drajer/cda/utils/CdaGeneratorConstants.java#L226C54-L226C77

https://github.com/drajer-health/eCRNow/blob/668accb3639d60118013da5709490f38aeec20d9/src/main/resources/oid-uri-mapping-r4.properties#L354C1-L354C1

**Comment by lakshman301195** [comment]
As discussed we have checked the FHIR Response, which gives back code as TELE HEALTH which is not a part of eiCR 1.1 Standard. So please close the ticket.

**Comment by nbashyam** [comment]
Athena to follow up internally 1/29/2024

**Comment by nbashyam** [comment]
Cannot reproduce.
