### ISSUE TITLE
Patagonia Health Data Feed Issues

### ISSUE THREAD

**Issue by komalpatagonia** [drajer-health/eCRNow#622]
Below are the fields which are present in Patagonia FHIR server but not being picked by ECR app
1. dq-dataCheck-immunizationActivity-performer
FHIR have Perfomer in immunization, , but eCR Now App not picking that value.

2. dq-dataCheck-immunizationActivity-routeCode
FHIR have RouteCode in Immunization, but eCR Now App not picking that value.
We required RouteCode in eICR 

3. Scenario Data Omission: No Observed guardian-code
FHIR have guarding code in Patient section, but eCR Now App not picking that value.

**Comment by AGABB** [comment]
Hey Komal - Would it be possible to attach a Loading Query file for a case report where this data is present in FHIR but not included in the eICR Output?

**Comment by komalpatagonia** [comment]
Hi Sasi ,

Can you please look into this

Thanks and Regards,
Komal Sadani
Data Integration Manager
Patagonia Health

**Comment by komalpatagonia** [comment]
Hi Nagesh,

Enclosing the FHIR resources for the Test,Jill patient.
1) The guardian code is located in the relationship section of the attached
patient resource, along with contact details. However, eCR is not updating
the code in the eICR CDA xml PatientRole -> guardian section.
FHIR Query : /Patient/{patientId}

2) The immunizations of the patient are attached. They have the routecode
Activty Performers.
However, eCR did not map these values in the eICR CDA xml Immunization ->
SubstanceAdministration section.
FHIR Query : /Immunization?patient=Patient/{{context.patientId}}

Regards,
*Sasidhar*

**Comment by mmatiasalt** [comment]
Hi @komalpatagonia , can you please confirm where those loading queries were sent to? Can you please upload them here? Thank you!

**Comment by komalpatagonia** [comment]
Hi Maria,

Attached are the FHIR response for the queries sent by ECR app now and EiCR
request/response to AIMS

Thanks and Regards,
Komal Sadani
Data Integration Manager
Patagonia Health

**Comment by mmatiasalt** [comment]
Hi @komalpatagonia I don't think the files are being uploaded properly to GitHub. Can you please click on this link and upload them directly to Github? Thanks! 
https://github.com/drajer-health/eCRNow/issues/622

**Comment by komalpatagonia** [comment]
Please find the attached files
[TestJill_PatientResouce.json](https://github.com/drajer-health/eCRNow/files/13709580/TestJill_PatientResouce.json)
[TestJill_ImmunizationResouce.json](https://github.com/drajer-health/eCRNow/files/13709581/TestJill_ImmunizationResouce.json)
[Jill XML.zip](https://github.com/drajer-health/eCRNow/files/13709628/Jill.XML.zip)

**Comment by komalpatagonia** [comment]
Is there any update on this issue

**Comment by mmatiasalt** [comment]
Hi @komalpatagonia , 

Thank you for your patience. The team is reviewing but there may be a delay due to the recent holidays. We will provide an update as soon as it is available. Thank you.

**Comment by medhost-chara** [comment]
Following up to see if there is an ETA on routeCode support for both Immunizations and medication administrations?

**Comment by AGABB** [comment]
@mmatiasalt Bringing this one back up as Nightingdale Notes has also asked the question about immun routeCode support

**Comment by nbashyam** [comment]
Fixed in 3.1.6
