### ISSUE TITLE
Lab results are not being written to coded section but appear in HTML of eICR

### ISSUE THREAD

**Issue by ctobias84** [drajer-health/eCRNow#625]
Lab results are not being written to coded section but appear in HTML of eICR. If the lab result is alphanumeric (not simply numeric) then the lab result is not persisted to the HTML section.

I believe aP/aF FHIR resources do not mix” numeric vs. text in a single FHIR Observation resource.  Dev Portal FHIR Observation API documentation mapping shows that OBSTYPE determines the behavior.

https://docs.mydata.athenahealth.com/fhir-r4/StructureDefinition-athena-observation-profile-mappings.html
   value[x]	IfEqual(%OBSTYPE%,"N").Then(Context::MakeQuantity,%OBSVALUE%,%UNIT%,%HDID%) | 
IfNotEqual(%OBSTYPE%,"N").Then(Context::MakeObservationValue,%HDID%, %OBSVALUE%)

https://hl7.org/fhir/R4/observation-definitions.html#Observation.value_x_

We output either valueCodeableConcept when OBSTYPE = T or valueQuantity when OBSTYPE = N.

For textual OBS, we output valueCodableConcept.text = OBSVALUE, and will also output valueCodableConcept.coding if the OBSVALUE is coded with a row in CQM_Map table where MapType = ExactCodeDescription. You can see an example of this on our Dev Portal at https://docs.mydata.athenahealth.com/fhir-r4/Observation-Example3.json.html.

For a lab result where OBSTYPE = T, I would expect:
  "valueCodeableConcept" : {
    "text" : OBS.OBSVALUE
  }

With the example of OBSVALUE = ‘GT 45’, I would expect:
  "valueCodeableConcept" : {
    "text" : "GT 45"
  }

For a lab result where OBSTYPE = N and OBSVALUE is numeric, I would expect:
  "valueQuantity" : {
    "value" : OBS.OBSVALUE,
    "unit" : OBSHEAD.UNIT,
    "system" : "http://unitsofmeasure.org",
    "code" : OBSHEAD.UNIT
  },

https://docs.mydata.athenahealth.com/fhir-r4/Observation-Example6.json.html
If there is no unit for an OBS term such as head circumference profile example OBSVALUE = 95 (percent has no units), valueQuantity will have only the OBSVALUE.
  "valueQuantity" : {
    "value" : 95
  }

Each aP/aF FHIR Observation resource will have at most 1 value[x] element; either valueCodeableConcept or valueQuantity.  Some Obs resources such as pulse oximetry and blood pressure will also have values at the component level: component.value[x].

Some Obs resources will have data absent reason extension if the value[x] is required by US Core profile but cannot be output because either OBSVALUE is null or blank or OBSVALUE is not numeric when OBSTYPE is N.

When OBSTYPE = N and OBSVALUE is NOT numeric, I’d like engineering team to confirm the behavior.  I think the behavior could be neither valueCodableConcept nor valueQuantity element is present and a dataAbsentReason element may be present.

**Comment by ctobias84** [comment]
Adding XML 
[LabResults_loadingQuery_XML.zip](https://github.com/drajer-health/eCRNow/files/13968517/LabResults_loadingQuery_XML.zip)
sample data to assist in problem reproduction and sample query

**Comment by nbashyam** [comment]
Adding to 3.1.3 baseline

**Comment by nbashyam** [comment]
Fixed in 3.1.3
