### ISSUE TITLE
CDA Generation: Medication Request data should be used in addition to Medication Statement along with ingredients that are present.

### ISSUE THREAD

**Issue by nbashyam** [drajer-health/eCRNow#63]

**Comment by nbashyam** [comment]
check status fields for mapping per Liz's email.

**Comment by nbashyam** [comment]
The status codes have to be checked for Service Request also and map only those that are not entered in error or revoked

**Comment by nbashyam** [comment]
Specific Questions for Discussion
MedicationsAdministered
Are Meds and Injectables included?
…They have different codeableConcepts
…..MedicationAdministration.medicationCodeableConcept.coding.display[Hough,Elizabeth]  Should be MedicationRequest.codeableConcept.coding
 
…..MedicationAdministration.contained.ingredient.itemCodeableConcept.coding.display[Hough,Elizabeth]  Should be MedicationRequest.contained.ingredient.itemCodeableConcept.coding
 
Which MedicationRequest.status(s) are mapped to -> statuscode? If moodCode eq INT, should we only pull the Active medreqs (not a 1-1 relationship between FHIR MedReq status and HL7 ActStatus which MedAdmin uses).
.... MedReq 'active' to MedAdmin 'in-progress'? (moodCode = INT)?
......MedReq 'completed' to MedAdmin 'completed' (moodCode = EVN)?
 
Plan of Treatment
What service request Categories will be supported? Laboratory Only?
What ServiceRequest.status is selected and mapped? Active only?
   ... (HL7ActStatus) = active. Only select "active" ServiceRequests.
    ...Where ServiceRequest.status eq 'active'
Are Lab Orders only being mapped to ->Planned Observation entry?
….In eICR v1.1 IG: only Planned Observations entry is documented. Are any other entries being supported? Planned Medication Activity, Planned Immunization Activity
For Planned Observation, which moodCode? INT (Intent (pre-starting action) or RQO (requested)

**Comment by nbashyam** [comment]
Updates pushed to baseline.

**Comment by AnanthaKrishnaV** [comment]
Not able to verify this as Cerner doesn't support Medication Statement.
