### ISSUE TITLE
Removed KARs Files Still Seen by eCR Now

### ISSUE THREAD

**Issue by VictoriaVaughn** [drajer-health/eCRNow#632]
When disabling and subsequently fully deleting "Old" eRSD files, we've noticed that eCR Now still attempts to process all KARs files even though they may no longer be present.

![image](https://github.com/drajer-health/eCRNow/assets/145029157/8571821d-9cf0-4503-8b87-25a938c75bb6)

In the screenshot, you can see that eCR Now is attempting to view 7 different KARs files even though later it errors when they are not able to be found. Once deleted, shouldn't it no longer populate them as part of the "active Kars" list?

**Comment by mmatiasalt** [comment]
Hi @VictoriaVaughn , this issue is under review and update will be provided as soon as available. Thank you

**Comment by NaveenKoujalagi** [comment]
This ticket was raised to remove the inactive kars related logs from eCRNow. But we are still seeing the service to check into the inactive Kars file and printing in eCRNow logs.

![Image](https://github.com/user-attachments/assets/ea3bf15e-19ed-486b-a1f2-b02bca8493c4)
