### ISSUE TITLE
Need assistance for FHIR multi- tenancy setup 

### ISSUE THREAD

**Issue by komalpatagonia** [drajer-health/eCRNow#634]
Patagonia Team want to schedule call with ECR App now team to setup FHIR muti tenancy.
Our FHIR vendor has questions for ECR app now team which needs to be clarified inorder for Patagonia Team to move ahaed with the Project.

**Comment by mmatiasalt** [comment]
Hi @komalpatagonia, Thank you for your patience.  Your request has been received and we will provide updates as soon as possible on when the call will be scheduled. Thank you.

**Comment by VenkatSaiReddyTeegala** [comment]
Resolved as part of 3.1.4
