### ISSUE TITLE
Data Quality: Result observation interpretationCode data element not included for Positive or non-Negative result observation value of type string

### ISSUE THREAD

**Issue by lakshman301195** [drajer-health/eCRNow#636]
Positive string results with no interpretation code will not be processed by RCKMS. SHOULD contain zero or more [0..*] interpretationCode, which SHALL be selected from ValueSet Observation Interpretation (HL7) urn:oid:2.16.840.1.113883.1.11.78 DYNAMIC (CONF:1198-7147).

**Comment by mmatiasalt** [comment]
Hello @lakshman301195  can you please provide some examples (Loading queries, screenshot, xml) and the version of the app you are using? Thank you.

**Comment by mmatiasalt** [comment]
Hi @lakshman301195 can you please provide some examples (Loading queries, screenshot, xml) and the version of the app you are using? We need this information in order to review your request. Thank you!

**Comment by lakshman301195** [comment]
Hi @mmatiasalt ,

We will discuss on this issue with dragon on today's call 08-Jan-2024.

**Comment by mmatiasalt** [comment]
Hi @lakshman301195 - Dragon is in need of loading queries to assist in triaging this issue. Can you please provide these so that we may review? Thank you.

**Comment by lakshman301195** [comment]
[636.zip](https://github.com/drajer-health/eCRNow/files/14161598/636.zip)

Please find the zip for loading query

**Comment by nbashyam** [comment]
Consider propagating text from interpretation FHIR element to interpretationCode CDA Element as Text when the value is not coded. DQ report will still flag that the interpretationCode does not meet the IG requirement since the data being propagated is TEXT and not a CODE.
Add to 3.1.4

**Comment by nbashyam** [comment]
This is an issue with the data being provided by the EHR's FHIR Resources to the eCRNow App.

**Comment by VenkatSaiReddyTeegala** [comment]
Resolved as part of 3.1.4
