### ISSUE TITLE
 History of Present Illness does not include any dates.

### ISSUE THREAD

**Issue by lakshman301195** [drajer-health/eCRNow#637]
History of Present Illness does not include any dates. This is being reported by the PHA's

**Comment by mmatiasalt** [comment]
Hello @lakshman301195 can you please provide some examples (Loading queries, screenshot, xml) and the version of the app you are using? Thank you.

**Comment by mmatiasalt** [comment]
Hi @lakshman301195 , we are working on addressing your issue but we are in need of examples in order to do so. Can you please provide some examples (Loading queries, screenshot, xml) and the version of the app you are using? Thank you.

**Comment by lakshman301195** [comment]
Hi @mmatiasalt ,

In the generated EICR, we have a section called History of Present Illness. This section displays only the names, whereas the PHA's are expecting onsetDatetime for these entries.

Below screenshot shows, how it is currently getting populated in EICR.
<img width="952" alt="Screenshot 2024-01-08 at 12 14 25 PM" src="https://github.com/drajer-health/eCRNow/assets/121233760/f109eaad-850b-4391-9c59-7ada71166aca">

**Comment by nbashyam** [comment]
Add to 3.1.4

**Comment by nbashyam** [comment]
Will not be addressed due to mapping issues with FHIR.
