### ISSUE TITLE
ScheduledJobData deserialization breaking change in 3.1.2

### ISSUE THREAD

**Issue by claylong** [drajer-health/eCRNow#641]
Change to file:
Update to the `src/main/java/com/drajer/bsa/scheduler/ScheduledJobData.java` file in the ['3.1.2 PR](https://github.com/drajer-health/eCRNow/pull/638/files#diff-4ba9400ec309b1b55e7d9cd94b6deb444f81666b66c26a4b3aa6bc41bad28433) - Only seemed to change accessibility of the constructor
![image](https://github.com/drajer-health/eCRNow/assets/5192644/91923bb5-7179-4508-be7e-743572bdc3ee)

Error:
In a working deployment, updating the version of ECRNow to the 3.1.2 version, we see the following error (buried in a scheduled job "WARNING" about an unhandled exception) when trying to read records from the scheduled task table in the DB:
`java.io.InvalidClassException: com.drajer.bsa.scheduler.ScheduledJobData; local class incompatible: stream classdesc serialVersionUID = 1403267933737660088, local class serialVersionUID = -5922589586885857138`
 
Notes on `serialVersionUID` - https://medium.com/@AlexanderObregon/a-deep-dive-into-java-serialization-e514346ac2b2#f5f6

This means that when upgrading to 3.1.2, any existing scheduled jobs are corrupted an unusable.  Presumably tasks are lost as a result.

**Comment by VictoriaVaughn** [comment]
Adding a note as discussed in our call today - since this warning is unhandled/uncaught that these are continuously re-trying every 5 minutes instead of failing after 3 total tries.

**Comment by claylong** [comment]
Some older Java docs seem to indicate we can/should be providing a serialVersionUID to avoid unintentional breaks like this one - https://docs.oracle.com/javase/8/docs/api/java/io/Serializable.html

> If a serializable class does not explicitly declare a serialVersionUID, then the serialization runtime will calculate a default serialVersionUID value for that class based on various aspects of the class, as described in the Java(TM) Object Serialization Specification. However, it is strongly recommended that all serializable classes explicitly declare serialVersionUID values, since the default serialVersionUID computation is highly sensitive to class details that may vary depending on compiler implementations, and can thus result in unexpected InvalidClassExceptions during deserialization. Therefore, to guarantee a consistent serialVersionUID value across different java compiler implementations, a serializable class must declare an explicit serialVersionUID value. It is also strongly advised that explicit serialVersionUID declarations use the private modifier where possible, since such declarations apply only to the immediately declaring class--serialVersionUID fields are not useful as inherited members. Array classes cannot declare an explicit serialVersionUID, so they always have the default computed value, but the requirement for matching serialVersionUID values is waived for array classes.

Incidentally, while examining the `java.security.Key` class for another issue, I see an example of this practice:
![image](https://github.com/drajer-health/eCRNow/assets/5192644/3a688648-99f7-43c5-9975-565876acacb8)

**Comment by claylong** [comment]
A thought:  Is the computed serialVersionUID value deterministic?  Was it the same value for all implementations of the pre-3.1.2 class?  My error messages above indicate the value was `1403267933737660088`.

If it was the same, would it be as simple as adding that specific serialVersionUID value to the class?

**Comment by mmatiasalt** [comment]
Hi @claylong @VictoriaVaughn , This issue has been added to v3.1.3.

**Comment by VictoriaVaughn** [comment]
@nbashyam  Just verifying that this is still expected in v3.1.3 since we aren't currently able to see it addressed in the recently updated branches.
