### ISSUE TITLE
Represented organization section is a required section under the author/assigned author section - Reported by South Dakota

### ISSUE THREAD

**Issue by lakshman301195** [drajer-health/eCRNow#643]
The South Dakota PHA Team has come up with a requirement to include Represented organization section under author/assigned author.

<img width="1008" alt="Screenshot 2024-01-24 at 12 03 26 PM" src="https://github.com/drajer-health/eCRNow/assets/121233760/058a0188-be4b-4afc-a01c-7206bb15bc61">

In our communication with them, we told that Represented organization is a section under encompassingEncounter but they want this data to be included under author/assigned author.

**Comment by nbashyam** [comment]
Is it possible to use a PractitionerRole resource associated with Encounter.participant.individual then it would be possible to populate the RepresentedOrganization as the PractitionerRole can be associated with an Organization. 1/29/2024

**Comment by jesposito9027** [comment]
Hi Dragon, 

We are not populating the PractitionerRole within the with the Practitioner resource. Can we use encounter.serviceProvider?

Thanks,
Jared
