### ISSUE TITLE
ProblemDate format is not usable - Reported by PHA

### ISSUE THREAD

**Issue by lakshman301195** [drajer-health/eCRNow#657]
Would it be possible for the problemDate section to be formatted with separators? Such as “Tue Jan 11 12:34:56 GMT 2024 |Unknown|Unknown”?

![image002](https://github.com/drajer-health/eCRNow/assets/121233760/57d1ef83-92bb-478b-80b7-5f3b0ad7fbea)

**Comment by mmatiasalt** [comment]
Hi @lakshman301195 , this issue has been reviewed and it will be addressed in V3.1.4. Thank you.

**Comment by VenkatSaiReddyTeegala** [comment]
Resolved as part of 3.1.4

**Comment by lakshman301195** [comment]
Please close the issue.
