### ISSUE TITLE
Condition onset is not populated on EICR Document (R4)

### ISSUE THREAD

**Issue by medhost-chara** [drajer-health/eCRNow#669]
Condition onset is not populated on EICR Document (R4)
Per Specifications - defined as https://hl7.org/fhir/condition.html with type designation ie "onsetString": "2024-02-05T00:00:01.000Z" 

<img width="1355" alt="image" src="https://github.com/drajer-health/eCRNow/assets/46822924/ed99caaa-3d58-49c2-8520-8616148b03dc">

[LoadingQueryBundle_8ee98205-e9ae-43a1-8f85-2b962f8595a6_616b443f-2ef7-435f-a4e1-2ff4cd00f0fc.json](https://github.com/drajer-health/eCRNow/files/14363865/LoadingQueryBundle_8ee98205-e9ae-43a1-8f85-2b962f8595a6_616b443f-2ef7-435f-a4e1-2ff4cd00f0fc.json)

**Comment by medhost-chara** [comment]
Note: We are making a change internally for defining onset and abatement as DateTime instead of String

**Comment by nbashyam** [comment]
Strings will not be converted to Dates currently, so the issue will be closed as part of 3.1.4

**Comment by VenkatSaiReddyTeegala** [comment]
Resolved as part of 3.1.4
