### ISSUE TITLE
Record Status Within Each Section Should Be Dynamic & Not Hard-Coded

### ISSUE THREAD

**Issue by VictoriaVaughn** [drajer-health/eCRNow#672]
Record Status Within Each Section Should Be Dynamic & Not Hard-Coded

For example, within the [CdaPlanofTreatmentGenerator,](https://github.com/drajer-health/eCRNow/blob/master/src/main/java/com/drajer/cdafromr4/CdaPlanOfTreatmentGenerator.java#L243) for Valid ServiceRequest Resources, the hard-coded status is "Active" and that causes confusion when the possible statuses (that aren't ignored) are more detailed:

![image](https://github.com/drajer-health/eCRNow/assets/145029157/7aba0f1f-5d73-422c-a7f5-777146662da4)

We've noticed this within other sections as well with a hard-coded status of "Completed", which also causes confusion in those scenarios where other more detailed statuses are possible that do not match with "Completed".

For example, within [CdaResultsGenerator](https://github.com/drajer-health/eCRNow/blob/master/src/main/java/com/drajer/cdafromr4/CdaResultGenerator.java#L181) .

When possible received values are:
![image](https://github.com/drajer-health/eCRNow/assets/145029157/9c11fe28-1e5c-42c3-95fa-6f19ba83b068)

**Comment by nbashyam** [comment]
We will have to check with the filtering criteria to see if any changes need to be made.

**Comment by nbashyam** [comment]
Allow only active and completed for orders. 
Allow preliminary, final, amended and corrected. (Drop Registered)
Add to 3.1.4

**Comment by nbashyam** [comment]
Updated status mappings to include the above recommendations in 3.1.5
