### ISSUE TITLE
Pregnancy Condition Not Ignoring Resourced Based on Verification Status

### ISSUE THREAD

**Issue by VictoriaVaughn** [drajer-health/eCRNow#678]
https://github.com/drajer-health/eCRNow/blob/master/src/main/java/com/drajer/cdafromr4/CdaSocialHistoryGenerator.java#L90

During testing, we noticed that an entered-in-error pregnancy condition, was still present within the eICR. The verification status should be checked for these conditions as well just like the standard condition query that was recently updated for issue #577

**Comment by VenkatSaiReddyTeegala** [comment]
Resolved as part of 3.1.4
