### ISSUE TITLE
Invalid FHIR Query for MedicationRequest - Remove single quotes

### ISSUE THREAD

**Issue by VictoriaVaughn** [drajer-health/eCRNow#681]
Invalid FHIR Query for MedicationRequest

In the eRSD file we can see:

    "id": "mrdata",
          "extension": [ {
            "url": "http://hl7.org/fhir/us/ecr/StructureDefinition/us-ph-fhirquerypattern-extension",
            "valueString": "MedicationRequest?patient=Patient/{{context.patientId}}&intent='order'"

And in the logs we can see that the full query used is:
message | Final serach Query URL:*fhirurl*/MedicationRequest?patient=Patient/*resourceID*&intent='order'

The single quote on the intent value appear to be causing an issue with FHIRAPI returning results. It seems the query should be:
*fhirurl*/MedicationRequest?patient=Patient/*resourceID*&intent=order

Also small note, of the typo of "serach" vs. "search" in the logger

**Comment by nbashyam** [comment]
Added to 3.1.4
