### ISSUE TITLE
Detailed Ethnicity not appearing in eCR3.0 CCDA

### ISSUE THREAD

**Issue by rashmi1977** [drajer-health/eCRNow#682]
In EMR products we have the option of capturing both Ethnicity and Detaield Ethnicity(Ethnicity 2). Please see screen below
![image](https://github.com/drajer-health/eCRNow/assets/60920244/7da44ed9-42df-47e3-b543-c980715545b5)
After entering detailed Ethnicity we get the same in GET response of Patient FHIR resource. Please see screen below
![image](https://github.com/drajer-health/eCRNow/assets/60920244/27d145d7-942c-4182-8819-93ed52113f03)
But in the eCR3.0 CCDA we do not see the detailed Race. Please find attached
[eCR_CCDA.txt](https://github.com/drajer-health/eCRNow/files/14534596/eCR_CCDA.txt)
The eCR3.0 CCDA which does not have detailed Ethnicity -It is an eCR CCDA generated on eCR version 3.1.3
Similar to race we need detailed ethnicity
![image](https://github.com/drajer-health/eCRNow/assets/60920244/673093c9-fad9-42c3-9c31-fec9e9f3a276)
We require Detailed Ethnicity in order to address AIMS feedback.

**Comment by VenkatSaiReddyTeegala** [comment]
Resolved as part of 3.1.4
