### ISSUE TITLE
FHIR R4 MedicationAdministration resource supports status "not-done" however based on logic ecrNow treats as "completed" (release/3.1.4)

### ISSUE THREAD

**Issue by medhost-chara** [drajer-health/eCRNow#688]
FHIR R4 MedicationAdministration Resource includes the statuses of 
in-progress \| not-done \| on-hold \| completed \| entered-in-error \| stopped \| unknown
https://hl7.org/fhir/R4/medicationadministration.html
However during translation of the status field of a medicationAdministration resource had a value of "not-done" 
based on using method 
https://github.com/drajer-health/eCRNow/blob/3.1.4/src/main/java/com/drajer/cdafromr4/CdaMedicationGenerator.java#L166
With this logic https://github.com/drajer-health/eCRNow/blob/3.1.4/src/main/java/com/drajer/cdafromr4/CdaFhirUtilities.java#L2583
It would return as "completed".

**Comment by nbashyam** [comment]
Added to 3.1.4

**Comment by VenkatSaiReddyTeegala** [comment]
Resolved as part of 3.1.4
