### ISSUE TITLE
Provider Phone in Loading Query but not in eICR

### ISSUE THREAD

**Issue by VictoriaVaughn** [drajer-health/eCRNow#702]
Within the assigned author section of the eICR, the provider fax is able to pull in and the phone has been able to pull in in other scenarios, but it wasn't for this one. 

![image](https://github.com/drajer-health/eCRNow/assets/145029157/590bfe31-1486-49db-aa3e-0abebadc2528)

![image](https://github.com/drajer-health/eCRNow/assets/145029157/ec45344d-595d-4b35-be1a-1f7ba39f2f5e)

Is this due to the system being 'other'? 

See attached:
[ProviderPhoneLoading Query.json](https://github.com/drajer-health/eCRNow/files/14795921/ProviderPhoneLoading.Query.json)
[ProviderPhoneMissing_eICR.json](https://github.com/drajer-health/eCRNow/files/14795922/ProviderPhoneMissing_eICR.json)

**Comment by bhargavchowdhary** [comment]
we are display if  system is phone ,email,fax

**Comment by nbashyam** [comment]
Looks like the type of telecom is not one of hte above, hence it is not being included.

**Comment by VictoriaVaughn** [comment]
Thank you , we have resolved this internally.
