### ISSUE TITLE
Medication Requests in FHIR server not getting pulled in to medicationAdministration section of eICR.

### ISSUE THREAD

**Issue by nmarmelo1** [drajer-health/eCRNow#704]
We are sending MedicationRequest objects to our FHIR server that reflect patient prescriptions.
However, none of these have been present in any of our test scenario TriggerQueryBundles, LoadingQueryBundles, or eICRs.
Here is an example of a MedicationRequest response from our FHIR server (Test Scenario #1 Jill Test): 
[JillTest_remdesivir_MedicationRequest_FHIRResponse.json](https://github.com/drajer-health/eCRNow/files/14826883/JillTest_remdesivir_MedicationRequest_FHIRResponse.json)

LoadingQuery: 
[LoadingQueryBundle_JillTest_3-4-2024.json](https://github.com/drajer-health/eCRNow/files/14826902/LoadingQueryBundle_JillTest_3-4-2024.json)

TriggerQuery:
[TriggerQueryBundle_JillTest.json](https://github.com/drajer-health/eCRNow/files/14826904/TriggerQueryBundle_JillTest.json)

eICR:
[JillTest_eICR_2024-03-05.txt](https://github.com/drajer-health/eCRNow/files/14826912/JillTest_eICR_2024-03-05.txt)

We were advised by testing team (Andrew Gabbeit, Deepshika Medapalli) to open a GitHub issue to discover why this is not functioning as expected and if there are any changes we could make to the data we send to the FHIR server so that the medicationAdministration section of eICRs will be populated appropriately. Can provide more information if necessary.

**Comment by nbashyam** [comment]
Since the data is not present in the bundle, please check the log file to see what query is being run for medicationrequest.
There must be something wrong with the query , hence the data is not being returned.

**Comment by nmarmelo1** [comment]
Thank you - after reviewing the log, the query below seems to be the issue:
https://pc-fhir-stg.amazingcharts.com/fhir/r4/MedicationRequest?patient=Patient/622c3a96-5915-d92b-479f-ebd4e5c43c16&intent='order'

Testing with Postman indicates that the single quotes around 'order' are the reason for the lack of data being returned. The same query executed without the single quotes does indeed return a result. I double checked the MedicationRequest.intent value to confirm that it is 'order'.

I've attached updated files from the test scenario in case they may be of use to you. The MedicationRequest processing starts at line 3382 of ecrNow.log.2024-04-02
[Scenario 1 - Jill.zip](https://github.com/drajer-health/eCRNow/files/14910203/Scenario.1.-.Jill.zip)

**Comment by nbashyam** [comment]
That should have been addressed in the latest ERSDv2 file. Have you used the latest ERSD file?

**Comment by mmatiasalt** [comment]
@nmarmelo1 please advise if you have any additional issues after testing latest eRSD V2 file. Thank you

**Comment by mmatiasalt** [comment]
@nmarmelo1 are you still having issues after testing the latest eRSD V 2 file?

**Comment by mmatiasalt** [comment]
@nmarmelo1 are you still having issues after testing the latest eRSD V2 File? Can this issue be closed? 

Thank you,

**Comment by mmatiasalt** [comment]
@nmarmelo1 checking to see if you're still having issues after testing latest eRSD V2 file or if we can close issue? Thank you.

**Comment by nmarmelo1** [comment]
@mmatiasalt Apologies, I haven't had a chance to confirm if we are still having issues with eRSD V2 file. I believe that we started using that prior to logging this issue. 
Unfortunately I have been roped in to an alternate (and urgent) project for the past week or so. I will try to get back to you with a solid answer within a few days.

**Comment by mmatiasalt** [comment]
@nmarmelo1 no worries! Thank you so much for responding.

**Comment by mmatiasalt** [comment]
@nmarmelo1 are you able to confirm if this issue was resolved? Thank you.

**Comment by mmatiasalt** [comment]
@nmarmelo1 can you confirm this issue is resolved? May we close this ticket?

**Comment by nmarmelo1** [comment]
I cannot confirm this issue is resolved. I don't have the exact date that we switched to using the eRSD V2 file, but can confirm that it is now in place and have begun re-testing this scenario for Jill Test.
