### ISSUE TITLE
Scenario Data Omission: No Observed Occupation Code/Text

### ISSUE THREAD

**Issue by nmarmelo1** [drajer-health/eCRNow#706]
We are sending Occupation Observation code and text to our FHIR server and it is getting picked up in the LoadingQueryBundle. However, the eICR is missing these elements. The definition for test scenario #3 says it is looking for plumber (code 6450).
In our occupation code system, the code for plumber is 47-2152. We are using the NIOCCS web api (https://wwwn.cdc.gov/nioccs/IOCode?o=plumber&c=2) to get NAICS and SOC codes. 

Could the difference on codes be causing an issue? If not, perhaps this is just a symptom of issue [#683](https://github.com/drajer-health/eCRNow/issues/683). Could these elements be missing from our test scenarios because the eCR Now app was not checking for the History of Occupation LOINC code, only the Occupation LOINC code?

Examples: 
[LoadingQueryBundle_JackTest.json](https://github.com/drajer-health/eCRNow/files/14839901/LoadingQueryBundle_JackTest.json)
[JackTest_eICR_2024-04-01.txt](https://github.com/drajer-health/eCRNow/files/14839909/JackTest_eICR_2024-04-01.txt)

**Comment by mmatiasalt** [comment]
@nmarmelo1 can you please advise what version of the app you are using to test? Thank you.

**Comment by nmarmelo1** [comment]
@mmatiasalt Currently we are using Branch-3.0

**Comment by nbashyam** [comment]
Please retest after 3.1.4 release.

**Comment by nbashyam** [comment]
Please retest with 3.1.5 and reopen defect if still persists.
