### ISSUE TITLE
Encompassing encounter code data element is nullFlavor

### ISSUE THREAD

**Issue by nmarmelo1** [drajer-health/eCRNow#707]
It's unclear to us what the Encompassing Encounter 'code' data element is looking for from the data we provide.

The FHIR definition for Encounter resource (https://build.fhir.org/encounter.html) does not contain an explicit definition of a 'code' element in the data structure.

Of the supported data elements in a FHIR Encounter, we are including a 'code' for the class, participant.type.coding and reasonCode.

See the attached files for an example of an Encounter Resource that is not producing an Encompassing Encounter code in the eICR for test scenario #3.
[LoadingQueryBundle_JackTest.json](https://github.com/drajer-health/eCRNow/files/14841657/LoadingQueryBundle_JackTest.json)
[TriggerQueryBundle_JackTest.json](https://github.com/drajer-health/eCRNow/files/14841660/TriggerQueryBundle_JackTest.json)
[JackTest_eICR_2024-04-01.txt](https://github.com/drajer-health/eCRNow/files/14841659/JackTest_eICR_2024-04-01.txt)

**Comment by nbashyam** [comment]
Encounter.class attribute is used to populate the encompassingEncounter.code element. This is only used when you have the right code system per the FHIR Spec.
If Encounter.class is not populated, then Encounter.type is used. In this case, ICD-10, ICD-9, CPT or SNOMED code systems are allowed.

**Comment by nmarmelo1** [comment]
This can be closed thank you!

**Comment by mmatiasalt** [comment]
Thank you!

**Comment by nmarmelo1** [comment]
@mmatiasalt actually, I do have a question. In the files I attached in the original post, we are including an encounter.class value, but it's not getting pulled in to the eICR. Would you guys be able to look into why that is?

**Comment by nbashyam** [comment]
The reason is because the code system to be used should be https://terminology.hl7.org/5.5.0/ValueSet-v3-ActEncounterCode.html
