### ISSUE TITLE
PHA eICR data need not observed: plannedObservation performer/author

### ISSUE THREAD

**Issue by nmarmelo1** [drajer-health/eCRNow#708]
These elements were missing in the eICR for test scenario #2 (Jane Test), but were present in our FHIR server, the LoadingQueryBundle and TriggerQueryBundle as a ServiceRequest resource.

The 'performer' data element is present in the FHIR object, LoadingQueryBundle, and TriggerQueryBundle as a contained reference to an Organization resource. Is this supported by the eCR Now App?

The 'author' data element is not defined in the FHIR definition for a Service Request resource (https://build.fhir.org/servicerequest.html),
but there is a 'requester' data element, which is present in all files except the eICR as a Reference resource which points to a Practitioner resource. Is this supported by the eCR Now App?

Files for reference:
[TriggerQueryBundle_JaneTest.json](https://github.com/drajer-health/eCRNow/files/14842623/TriggerQueryBundle_JaneTest.json)
[LoadingQueryBundle_JaneTest.json](https://github.com/drajer-health/eCRNow/files/14842624/LoadingQueryBundle_JaneTest.json)
[JaneTest_eICR_2024-04-02.txt](https://github.com/drajer-health/eCRNow/files/14842626/JaneTest_eICR_2024-04-02.txt)

Resource ID of resource in question: b21d345e-42ec-41c0-9699-db6c1670758e

**Comment by mmatiasalt** [comment]
Hi @nmarmelo1 , 
Can you please advise which PHA is reporting this issue? Thank you!

**Comment by nmarmelo1** [comment]
Our EHR is Picasso, under the Harris Ambulatory Niche group. Our testing was done with Andrew Gabbeitt and Deepshika Medapalli

**Comment by nbashyam** [comment]
Not sure a performer data element makes sense for the Planned Observation. Need to check.

**Comment by qtuan** [comment]
> Not sure a performer data element makes sense for the Planned Observation. Need to check.

Hi @nbashyam , how about the "author" element (which was also another part in the OP's question)? Thanks!
