### ISSUE TITLE
 eCR AIIMS validator gives schematron Fatal error for all eCR 3.0 CCDA's

### ISSUE THREAD

**Issue by rashmi1977** [drajer-health/eCRNow#711]
All generated eCR 3.0 CCDA's gave error with AIIMS validator when validated with eICR 3.1.3 Version. 
Fatal: SHALL contain exactly one [1..1] templateId (CONF:4482-96) such that it SHALL contain exactly one [1..1] @root="2.16.840.1.113883.10.20.15.2" eICR Initial Public Health Case Report Document (CONF:4482-95). SHALL contain exactly one [1..1] @extension="2022-05-01" (CONF:4482-96).
<img width="804" alt="image" src="https://github.com/drajer-health/eCRNow/assets/60920244/59859262-910c-4cc1-882d-f4a38dfb8417">

**Comment by nbashyam** [comment]
Fix in 3.1.5

**Comment by nbashyam** [comment]
Fixed in 3.1.6
