### ISSUE TITLE
resultObservation-author & resultOrganizer-author Not Included in eICR

### ISSUE THREAD

**Issue by VictoriaVaughn** [drajer-health/eCRNow#722]
In FHIR, our Observation resource references Practitioner as the performer and it is present in the Loading Query.

 "performer": [ {
        "reference": "Practitioner/1ec83b53cdb234febad3680ac05c48dafb665f3a"

The CdaResultGenerator does seem to be looking for the referenced performer to be able generate the Author xml, but it doesn't seem to be successful as it is not present in the eICR. Please advise.

Example:
[GreenwayHealth_Intergy_21.25_3.1.3_Round 1_Scenario 1_eICR.json](https://github.com/drajer-health/eCRNow/files/14935685/GreenwayHealth_Intergy_21.25_3.1.3_Round.1_Scenario.1_eICR.json)

[GreenwayHealth_Intergy_21.25_3.1.3_Round 1_Scenario 1_Loading Query.json](https://github.com/drajer-health/eCRNow/files/14935686/GreenwayHealth_Intergy_21.25_3.1.3_Round.1_Scenario.1_Loading.Query.json)

**Comment by bhargavchowdhary** [comment]
Which baseline are you using? @VictoriaVaughn

**Comment by VictoriaVaughn** [comment]
We are using v3.1.3 currently. Was support for resultOrganizer also added in 3.1.4?

**Comment by NaveenKoujalagi** [comment]
This ticket was raised to have include the resultObservation-author & resultOrganizer-author in the eICR.
Although it has been included in the eICR. But the "representedOrganization" in the Lab result has only "MMC" . And the expectation was it should have the complete detail that is present in the main document "representedOrganization"

Main document has representedOrganization like below:

![Image](https://github.com/user-attachments/assets/569f9876-25f3-4b78-bd58-b1beeb7ee5ad)

the Lab result has it:

![Image](https://github.com/user-attachments/assets/3046177c-9be8-47a6-a0f2-de2ec6ccbec3)
