### ISSUE TITLE
Lab Results Trigger Template Missing From eICR

### ISSUE THREAD

**Issue by VictoriaVaughn** [drajer-health/eCRNow#723]
May be similar to Issue #720 - though we have the ValueQuantity available in this example

[GreenwayHealth_Primesuite_21.23_3.1.3_Round 1_Scenario 3_eICR.json](https://github.com/drajer-health/eCRNow/files/14939020/GreenwayHealth_Primesuite_21.23_3.1.3_Round.1_Scenario.3_eICR.json)
[GreenwayHealth_Primesuite_21.23_3.1.3_Round 1_Scenario 3_Loading Query.json](https://github.com/drajer-health/eCRNow/files/14939021/GreenwayHealth_Primesuite_21.23_3.1.3_Round.1_Scenario.3_Loading.Query.json)
[GreenwayHealth_Primesuite_21.23_3.1.3_Round 1_Scenario 3_Trigger Query.json](https://github.com/drajer-health/eCRNow/files/14939022/GreenwayHealth_Primesuite_21.23_3.1.3_Round.1_Scenario.3_Trigger.Query.json)

**Comment by nbashyam** [comment]
Add to 3.1.5
