### ISSUE TITLE
ECRNOW App is crashing on Startup if jobs are getting queued up in DB before app startup 

### ISSUE THREAD

**Issue by lakshman301195** [drajer-health/eCRNow#727]
We have deployed the ECRNOW App in a docker container in ECS service and setup autoscaling for the docker containers based on CPU utilisation. We are facing an issue that during app startup, if there are more number of jobs queued up in the database and the job starts running, the app crashes. We are observing "Heap Memory Error" and docker containers are getting killed.

The CPU utilisation goes beyond 140% on app startup during this time. It takes around more than 20 minutes to settle down. Post which if jobs are running, there exist no issue. Issue exist only on startup.

Impact:
Because of this we are not able to effectively autoscale based on load.

Please investigate and fix this issue on Priority.

Screenshot of CPU Utilisation:
<img width="1565" alt="Screenshot 2024-04-12 at 5 05 22 PM" src="https://github.com/drajer-health/eCRNow/assets/121233760/2f67e55a-e5b1-4667-b8d9-3e8116200a5b">

**Comment by nbashyam** [comment]
Need to examine how/when this will happen and reproduce the issue.
