### ISSUE TITLE
Paragon FHIR changes for eCR - Author & Race 

### ISSUE THREAD

**Issue by Priteshchavan28** [drajer-health/eCRNow#728]
Hello Nagesh, 

We as Paragon EHR working with one of our client and CDC for eCR soft go-live. CDC has shared eCR Data Quality Monitoring Report which contain list of schematron errors/issues that needs to be corrected in order to pass the criteria. 

Below are two of the issues CDC has reported and our findings : 
Issue no. 1 : Data Quality: The author id data element has no @extension attribute - it means a CDA author must be uniquely identified, whether a Person or a Device. Such IDs must include both root and extension values to be complete. 
-> It seems eCR app is looking for author information (US Realm Header section) as assigned person from Practitioner resource. Currently we are sending our internal identifier of provider in Practitioner Resource response. 
-> To correct this, we will be sending NPI number and its codesystem as identifier for provider, **we would need a confirmation - can eCR app support this change and reflect the same in the eICR document ?** 

Issue no. 2 : raceCode @code values limited to 5 values: 1002-5, 2028-9, 2054-5, 2076-8, 2106-3 or OTH & Patient raceCode data element is not in ValueSet Race Category Excluding Nulls 
-> For Race selected as "Other", Paragon is sending LOINC code 2131-1 instead of "OTH" 
->To correct this, we will be sending OTH null flavor for Other Race. **We would need a confirmation - can eCR app support this change and reflect the same in the eICR document ?** 

Paragon is using FHIR version 1.0.2 DAF profile and for eCR - we are using addAuthParameters220 branch. 

Please let me know if you have questions or need additional information. 

Appreciate your help! Looking forward to hear back from you. 

Thank you, 
Pritesh Chavan

**Comment by nbashyam** [comment]
Yes, they are both supported in eCR App version 2.X

Is there a reason, you are on addAuthParameters branch instead of the master baseline, I would recommend moving to the master regardless of which version of the app you are using so that all your latest fixes are in place.

**Comment by Priteshchavan28** [comment]
Thank you Nagesh for your quick response! 
This was 2 years ago so I am trying to recollect but I think you have asked us to use this branch as we were the first customer for eCR using FHIR R2/DAF profile and that's why whatever issues we had observed during integration, you used to fixed in this branch only. Also TokenFilter class which we created, you had incorporated in this branch. 

As you have recommended to use Master branch, we are planning to take this branch but before that we would like to have a short meeting with you to discuss regarding the same. Can you please provide your availability is EST so that I can setup a meeting. 

Thank you
