### ISSUE TITLE
Medication Instruction is not appearing in eCR3.0 CCDA 

### ISSUE THREAD

**Issue by sumanathenahealth** [drajer-health/eCRNow#731]
We have an option to capture Medication Instruction , Please find the below screen shot 

![Medication](https://github.com/drajer-health/eCRNow/assets/106141686/4c49d335-8678-4db8-b584-af2be14e045d)

These medication instructions , we get as GET response of Medication Statement Resource , Find the below screen shot

![FHIR_Response](https://github.com/drajer-health/eCRNow/assets/106141686/d8c23a70-f47e-4e90-8a4d-54056de01e83)

But in the eCR3.0 CCDA we do not see the Medication Instruction . Please find attached 

[ecr_ccda.txt](https://github.com/drajer-health/eCRNow/files/15021058/ecr_ccda.txt)

**Comment by nbashyam** [comment]
Need to examine where this would go in the CDA eiCR.

**Comment by sumanathenahealth** [comment]
Can you please provide update on this ?

**Comment by ctobias84** [comment]
AIMS team noted these are unlinked templates in the EICR and the medication instructions should not be included.

**Comment by sumanathenahealth** [comment]
So , as per the above comment are we good to close with GIT-hub request?
