### ISSUE TITLE
eICR: Travel history omits  effectiveTime.end

### ISSUE THREAD

**Issue by kmarx** [drajer-health/eCRNow#735]
FHIR emits a travel history `effectivePeriod` with both `start` and `end`, but only `start` is present in the eICR xml.

*FHIR*
`"resource": {
      "resourceType": "Observation",
      "id": "4ec5de42-dffb-11ec-9d64-0242ac127030",
      "text": {
        "status": "generated",
        "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">Had been to Argentina early this month</div>"
      },
      "status": "final",
      "category": [ {
        "coding": [ {
          "system": "http://terminology.hl7.org/CodeSystem/observation-category",
          "code": "social-history",
          "display": "Social History"
        } ]
      } ],
      "code": {
        "coding": [ {
          "system": "http://snomed.info/sct",
          "code": "420008001",
          "display": "Travel History"
        } ]
      },
      "subject": {
        "reference": "Patient/DA22488E8BEC466EB7487C94E79BEA77",
        "display": "pt, ecrlabreport4"
      },
      "effectivePeriod": {
        "start": "2024-04-04T00:00:00-07:00",
        "end": "2024-04-12T00:00:00-07:00"
      },
      "component": [ {
        "code": {
          "coding": [ {
            "system": "http://terminology.hl7.org/CodeSystem/v3-ParticipationType",
            "code": "LOC",
            "display": "Location"
          } ]
        },
        "valueCodeableConcept": {
          "coding": [ {
            "system": "urn:iso:std:iso:3166",
            "code": "AR",
            "display": "Argentina"
          } ],
          "text": "Argentina"
        }
      } ]
    }`

*eICR*

`<entry>
<act classCode="ACT" moodCode="EVN">
<templateId root="2.16.840.1.113883.10.20.15.2.3.1" extension="2016-12-01"/>
<id root="30e42392-b91e-4423-81bf-48a7e3676fd3"/>
<code code="420008001" codeSystem="2.16.840.1.113883.6.96" codeSystemName="SNOMED-CT" displayName="Travel"/>
<text>Travel History Component 1 : Location |  Value : Argentina</text>
<statusCode code="completed"/>
<effectiveTime value="20240404000000-0700"/>
<participant typeCode="LOC">
<participantRole classCode="TERR">
</participantRole>
</participant>
</act>
</entry>`

**Comment by nbashyam** [comment]
Assign to 3.1.5 release
