### ISSUE TITLE
CDA: Immunization section - Date time is not populated correctly.

### ISSUE THREAD

**Issue by AnanthaKrishnaV** [drajer-health/eCRNow#74]
In immunization section, date/time field is populated as below with "DateTimeType" string instead of only date/time value (2014), in narrative text and effectiveDtTm fields.

<content ID="vaccinationDate1">**DateTimeType[2014]**</content>
<effectiveTime value=**"DateTimeType[2014]"**/>

**Comment by nbashyam** [comment]
Updates in the baseline.
