### ISSUE TITLE
Non-XML IMAP messages not deleted at HISP

### ISSUE THREAD

**Issue by kmarx** [drajer-health/eCRNow#740]
We find non-eicr/rr messages in the HISP direct inbox even when eCRNow thinks they're being deleted. E.g.,

```
...
30-04-2024 03:50:35.235 [db-scheduler-pool-2-thread-4] INFO  c.d.b.r.impl.DirectTransportImpl.readMailUsingImap -  Not an XML attachment, so ignoring the multipart file 
30-04-2024 03:50:35.235 [db-scheduler-pool-2-thread-4] INFO  c.d.b.r.impl.DirectTransportImpl.readMailUsingImap -  Not an XML attachment, so ignoring the multipart file 
30-04-2024 03:50:35.274 [db-scheduler-pool-2-thread-4] INFO  c.d.b.r.impl.DirectTransportImpl.deleteMailUsingImap - Deleting mail..
30-04-2024 03:50:35.275 [db-scheduler-pool-2-thread-4] INFO  c.d.b.r.impl.DirectTransportImpl.deleteMailUsingImap - Connecting to IMAP Inbox
...
30-04-2024 03:51:19.282 [db-scheduler-pool-2-thread-5] INFO  c.d.b.r.impl.DirectTransportImpl.deleteMailUsingImap -  Deleting message with id null
...
```

But logging into the HISP inbox shows MDN and other protocol related messages are not deleted. This will be a critical issue as we move to production and messages pile up. eCRNow will have to iterate this ever growing list each time it checks for new RR's.

Perhaps there's an issue getting the message id to delete from the HISP? 

_Note: We've created an inbox in our HISP's eval account for the Drajer team to use. It might allow them to debug this directly._

**Comment by nbashyam** [comment]
This is already fixed in 3.1.4 and above, so this will be closed.
