### ISSUE TITLE
Duplicate Observation while processing for CDA generation

### ISSUE THREAD

**Issue by linh-phan-vn** [drajer-health/eCRNow#746]
I noticed the output eICR having observations (Results, Travel history) duplicated.
I am not sure why additional resources were added while processing KAR data in the source code (line 110)
https://github.com/drajer-health/eCRNow/blob/6e485f89086f7dc7af6e236f76737dc2b233569a/src/main/java/com/drajer/bsa/utils/R3ToR2DataConverterUtils.java#L99-L110
https://github.com/drajer-health/eCRNow/blob/6e485f89086f7dc7af6e236f76737dc2b233569a/src/main/java/com/drajer/bsa/utils/R3ToR2DataConverterUtils.java#L121-L137

The Observation resources were added to `r4FhirData` once more time.
![image](https://github.com/drajer-health/eCRNow/assets/121847133/bdc9322e-7e7f-4522-99af-67a08e31016c)

**Comment by mmatiasalt** [comment]
Hello @linh-phan-vn , can you please advise which EHR you are representing and which version of the app you are using? Thank you.

**Comment by linh-phan-vn** [comment]
Hi @mmatiasalt 
I am working with SolidPractice and the app version is `3.1.4`
Thanks

**Comment by nbashyam** [comment]
This has been already addressed in 3.1.5
