### ISSUE TITLE
Encounter Resource Containing Trigger Code but Not Present in eICR

### ISSUE THREAD

**Issue by VictoriaVaughn** [drajer-health/eCRNow#747]
Should ecrnow be checking the encounter resource for trigger codes?

We ran into an issue where a reason code on an encounter resource, was a triggering code:

![image](https://github.com/drajer-health/eCRNow/assets/145029157/f94c813e-6754-46bf-a8c5-94624b8cea56)

However, when the case report was generated, this code was not present. Since it was the only triggering code, the eICR is invalid and would error if sent to AIMS.

**Comment by mmatiasalt** [comment]
@VictoriaVaughn are you able to include the log files/examples for our team to review? Thank you!

**Comment by VictoriaVaughn** [comment]
As this example was found on a production site, we are not able to share the example as it contains PHI.

**Comment by mmatiasalt** [comment]
@VictoriaVaughn are you able to de-identify that file to share with us?

**Comment by nbashyam** [comment]
This has been addressed with the 3.1.5 baseline.
