### ISSUE TITLE
Guardian Code always populates with OTH value

### ISSUE THREAD

**Issue by linh-phan-vn** [drajer-health/eCRNow#748]
Hi Teams, 
I am working with SolidPractice and the app version is 3.1.4.

I am facing an issue with Guardian Code. As described in the CDA specification
![image](https://github.com/drajer-health/eCRNow/assets/121847133/da80fa7f-47a1-416b-8ebc-91e1071161e9)
![image](https://github.com/drajer-health/eCRNow/assets/121847133/040be0eb-8247-4185-a6ef-73676fe0fada)

I am not sure how to fill this value into the FHIR resource to have it populated in the eICR. I looked through the source for more info, but it made me confused at 
https://github.com/drajer-health/eCRNow/blob/f7257c942e22b3b30bea4d7d052dff911d29ebb4/src/main/java/com/drajer/cdafromr4/CdaHeaderGenerator.java#L993-L1008

For generating `<code>`, it used the `coding `variable and filtered by the code system `CdaGeneratorConstants.FHIR_LOC_ROLE_CODE_TYPE_V3` while the `coding `variable was retrieved from another code system `CdaGeneratorConstants.FHIR_CONTACT_RELATIONSHIP_CODESYSTEM`. Therefore, the generated output was `OTH `all the time.
Could you please help me go through this case? Or show me an example of FHIR data that can populate `guardian.code` rather than `OTH`.
Thanks,

**Comment by nbashyam** [comment]
We have been previously using a different and an older code system for the relationship. We should look into using the US Core 7.0.0 Patient Relationship value set and see if it can be translated properly.

**Comment by nbashyam** [comment]
Please attach the loading query.

**Comment by linh-phan-vn** [comment]
Hi @nbashyam, 
Please see the attached file.
[LoadingQueryBundle.json](https://github.com/user-attachments/files/15911236/LoadingQueryBundle.json)

**Comment by nbashyam** [comment]
Fixed in 3.1.5
