### ISSUE TITLE
Detailed race not appearing in eCR3.0 CCDA * Bug for #651

### ISSUE THREAD

**Issue by mmatiasalt** [drajer-health/eCRNow#749]
Bug reported for: https://github.com/drajer-health/eCRNow/issues/651#top

We are still seeing the same issue with 3.1.4 build. We are not finding the detailed race in the eCR XML. Attaching XML for reference.
image

![image](https://github.com/drajer-health/eCRNow/assets/148487348/88318567-4844-4e0b-9a0e-bebf20773a00)

We are getting detailed ethnicity and not detailed race. Please refer the attached screenshot above.
@VenkatSaiReddyTeegala : I am unable to reopen the same for my end.
FYI: @nbashyam

_Originally posted by @rashmi1977 in https://github.com/drajer-health/eCRNow/issues/651#issuecomment-2128652353_

**Comment by mmatiasalt** [comment]
[@rashmi](https://github.com/rashmi1977)

**Comment by bhargavchowdhary** [comment]
@mmatiasalt  Could you please send me the loadingQuery.json file? It will help me debug the issue.

**Comment by sumanathenahealth** [comment]
Hi,
  Please find the attachments as requested.


Thanks & Regards,
Suman Alapati.


[LoadingQueryBundle_2032383736581630_2032383811582050.json](https://github.com/drajer-health/eCRNow/files/15464479/LoadingQueryBundle_2032383736581630_2032383811582050.json)
[TriggerQueryBundle_2032383736581630_2032383811582050.json](https://github.com/drajer-health/eCRNow/files/15464482/TriggerQueryBundle_2032383736581630_2032383811582050.json)
[eCRCCDA.txt](https://github.com/drajer-health/eCRNow/files/15464486/eCRCCDA.txt)

**Comment by bhargavchowdhary** [comment]
@sumanathenahealth  There is no detailed race extension in the given loading query, which is why detailed race does not display in eCR3.0 CCDA.
