### ISSUE TITLE
Observation Resource - Travel History is missing in eCR CCDA

### ISSUE THREAD

**Issue by sumanathenahealth** [drajer-health/eCRNow#750]
Hi Team,
   We have observed travel-history details are not populating in eCR CCDA.
   PFA for FHIR Travel-History response , TriggerQueryBundle_1991277747378180_2033007168461840.json , 
   LoadingQueryBundle_1991277747378180_2033007168461840.json
   Also we have observed some commented line in CdaSocialHistoryGenerator.java
   Please help with your inputs.

![CdaSocialHistoryGenerator](https://github.com/drajer-health/eCRNow/assets/106141686/761549ba-40a6-4818-ad37-99571cf07f80)

[FHIR_TravelHistory_Response.json](https://github.com/user-attachments/files/15546251/FHIR_TravelHistory_Response.json)

[LoadingQueryBundle_1991277747378180_2033007168461840.json](https://github.com/user-attachments/files/15546254/LoadingQueryBundle_1991277747378180_2033007168461840.json)

[TriggerQueryBundle_1991277747378180_2033007168461840.json](https://github.com/user-attachments/files/15546256/TriggerQueryBundle_1991277747378180_2033007168461840.json)

Thanks,
Suman Alapati.

**Comment by sumanathenahealth** [comment]
Hi,
  Can you please provide update on this ?

**Comment by bhargavchowdhary** [comment]
@sumanathenahealth 
There is no social history category code in all of the travel history observations provided. FHIR_TravelHistory_Response.json  

There is no social history category code in all of the travel history observations presented. FHIR_TravelHistory_Response.json  
Travel history observations must have the "category" element or the resource will be ignored.

"category": [
        {
            "coding": [
                {
                    "system": "http://terminology.hl7.org/CodeSystem/observation-category",
                    "code": "social-history",
                    "display": "Social History"
                }
            ],
            "text": "Social History"
        }
    ],

**Comment by sumanathenahealth** [comment]
Hi @bhargavchowdhary 
  This ticket is meant for Travel-History not Travel-Data , Please find the below HL7 specification for this 
    https://build.fhir.org/ig/HL7/case-reporting/StructureDefinition-us-ph-travel-history.html

Can you re-open the ticket as the query is not solved or Please let us know to log new ticket ?

@nbashyam @rdingwell @ahi-amccall

**Comment by sumanathenahealth** [comment]
Hi,
  Please provide update on this ?
