### ISSUE TITLE
500 server error for duplicate patient launch request

### ISSUE THREAD

**Issue by kmarx** [drajer-health/eCRNow#753]
We noticed that when a launch request is sent for the same encounter_id , patient_id and x_request_id, ecrnow service returns a ” 500 Internal Server Error “ due to a unique constraint in the database. 

Please return an appropriate status code and message.

**Comment by bhargavchowdhary** [comment]
We will return an OperationOutcome resource with a HTTP Status code of 422.

**Comment by VictoriaVaughn** [comment]
@bhargavchowdhary What version will this update be included in?

**Comment by nbashyam** [comment]
3.1.5
