### ISSUE TITLE
Create Encounter For Travel-History 

### ISSUE THREAD

**Issue by sumanathenahealth** [drajer-health/eCRNow#756]
Hi,

   As a part of Travel-History for eCR-now ,
   We want to highlight , that aP/aF doesn’t require to create encounter for recording Travel-history for patient.
  As travel-history is not the clinical item and belongs to patient details, hence patient details section for CCDA should populate these details .

 Want to understand are we in the same lines ?

**Comment by sumanathenahealth** [comment]
Hi,
  Can you please provide update on this ?

Thanks,
Suman Alapati

**Comment by nbashyam** [comment]
Not sure we understand the question, the Travel History is collected for the Patient not using an Encounter but using a Patient Id.

**Comment by sumanathenahealth** [comment]
Yes , you are right .
Travel history can collect at patient level only(Patient Id level) , it doesn't require to create encounter for collecting Travel-History data.
As  Travel-History  is not the clinical item , hence no need to create encounter for this.

**Comment by nbashyam** [comment]
ok, is there anything else you need from us on this ticket ?

**Comment by sumanathenahealth** [comment]
Want to understand are we in same lines  ? 
Also want to know how  currently travel-history is working in 3.1.4 version?

**Comment by nbashyam** [comment]
The travel history works at the Patient Level, there is no need to associate it with the encounter. This is how it works in the 3.1.4 version.
