### ISSUE TITLE
eICR Created Without Practitioner

### ISSUE THREAD

**Issue by VictoriaVaughn** [drajer-health/eCRNow#759]
Why are case reports still generated even when the Practitioner cannot be found? Is this valid?

"Data Quality: The author id data element has no @extension attribute"

Given that this is considered a data quality issue during CDC/AIMS review, it would appear that the Provider NPI should be required before creating a case report. Or confirmed present within the case report before submitting.

**Comment by nbashyam** [comment]
Victoria, 
We discussed this within the CDC eCR team. The consensus is that the vendors should populate the NPIs for the Practitioner who is associated with the encounter. So there is no code changes expected to be made for this.
