### ISSUE TITLE
Travel History Codeset

### ISSUE THREAD

**Issue by VictoriaVaughn** [drajer-health/eCRNow#761]
**Can the FHIR spec for travel history be shared** that was used to determine these specific codes were appropriate when querying for travel information during case report generation? 
There are many fixed values within the profile we have been reviewing internally and **not all of the codes below are present in the specifications**, so we would like to confirm we are using the correct version of the FHIR specs in reviewing.

ttp://snomed.info/sct|161085007,443846001,420008001,46521000175102,34831000175105,161086008 for dataReqId travelData-snomed

http://loinc.org|29762-2 for dataReqId travelData-loinc

**Comment by nbashyam** [comment]
The list was created based on the spec and codes provided by vendors to be in use in the real world. If you stick to the FHIR Specs, then you would be good. 

This is the latest FHIR Specification to be used. 
https://build.fhir.org/ig/HL7/case-reporting/

**Comment by nbashyam** [comment]
Fixed in 3.1.5
