### ISSUE TITLE
Travel History duplicate records in social history section In Ecr CCDA

### ISSUE THREAD

**Issue by sumanathenahealth** [drajer-health/eCRNow#762]
Travel History duplicate records in social history section In Ecr CCDA , Please find the attachments for create-report , loading query and trigger query

**ECR CCDA:**
![image](https://github.com/drajer-health/eCRNow/assets/106141686/ac494779-818c-42ff-b24a-7291e65f44c2)

[create-report_1807529796185360_498d0e80-d3a8-44cc-ac19-362e4d7a8a2c.txt](https://github.com/user-attachments/files/16157053/create-report_1807529796185360_498d0e80-d3a8-44cc-ac19-362e4d7a8a2c.txt)

[TriggerQueryBundle_1807529796185360_2036078061357680.json](https://github.com/user-attachments/files/16157032/TriggerQueryBundle_1807529796185360_2036078061357680.json)

[LoadingQueryBundle_1807529796185360_2036078061357680.json](https://github.com/user-attachments/files/16157034/LoadingQueryBundle_1807529796185360_2036078061357680.json)

**Comment by sumanathenahealth** [comment]
Can you give update on this ?

**Comment by sumanathenahealth** [comment]
Can you give update on this ?

**Comment by sumanathenahealth** [comment]
Any updates on this ?

**Comment by nbashyam** [comment]
Can you check wiht 3.1.5 branch, it is fixed but it would be good if you can confirm.
