### ISSUE TITLE
Chief Complaint not populated. data param is unused

### ISSUE THREAD

**Issue by markmaltbyoracle** [drajer-health/eCRNow#763]
https://github.com/drajer-health/eCRNow/blob/6e485f89086f7dc7af6e236f76737dc2b233569a/src/main/java/com/drajer/bsa/kar/action/EcrReportCreator.java#L948

3.1 spec notes the following "This section records the patient's chief complaint (the patient’s own description)". Why is this not being populated?

**Comment by nbashyam** [comment]
There is no specific FHIR Resource that provides this information explicitly for us to populate the eICR, hence it is not populated.
