### ISSUE TITLE
Country Code missing on all telecom

### ISSUE THREAD

**Issue by SG038146** [drajer-health/eCRNow#764]
Telephone format – missing the Universal Realm country “+1”
Oracle Health
Current display: </addr>
<telecom value="tel:(XXX)943-XXXX" use="WP"/>
<telecom value="tel:(XXX)654-XXXX" use="HP"/>

**Comment by mmatiasalt** [comment]
@SG038146  can you please provide screenshots and loading queries for us to review? Thank you.

**Comment by SG038146** [comment]
<img width="278" alt="telecom SS" src="https://github.com/user-attachments/assets/0c59d1f2-13b9-477e-87ff-394e0ae8467a">

**Comment by mmatiasalt** [comment]
Are you able to redact patient info on the query?

**Comment by mmatiasalt** [comment]
@SG038146 following up to see if you are able to redact patient info on the query so that we can review?

**Comment by SG038146** [comment]
I spoke to my SME, she was opposed to that, but I am getting a test patient from the facility for review.


[cid:d556a6d2-a63a-404c-af79-c5cc113e086d]

Shawnte George, MSPS, PMP

Senior Interoperability Project Manager| Interop Implementations

***@***.******@***.***> | 615-267-9919 mobile






________________________________
From: Maria Matias ***@***.***>
Sent: Tuesday, July 30, 2024 1:54 PM
To: drajer-health/eCRNow ***@***.***>
Cc: Shawnte George ***@***.***>; Mention ***@***.***>
Subject: [External] : Re: [drajer-health/eCRNow] Country Code missing on all telecom (Issue #764)


@SG038146<https://urldefense.com/v3/__https://github.com/SG038146__;!!ACWV5N9M2RV99hQ!O9lMkKe7dNQV6EYLZU-pTIJt3T-hIQv_1SFE-DSSHUikwPb3OSA1uDYXCeoc053OFbEWFFGHv4QmfwcTzTq6690L9lAl$> following up to see if you are able to redact patient info on the query so that we can review?

**Comment by SG038146** [comment]
Good Morning the issue has been resolved. Please close ticket


[cid:0130296f-e994-4250-8fd7-c16cfa24e12c]

Shawnte George, MSPS, PMP

Senior Interoperability Project Manager| Interop Implementations

***@***.******@***.***> | 615-267-9919 mobile






________________________________
