### ISSUE TITLE
Duplicate records of Travel History and Occupation Observations in social history section

### ISSUE THREAD

**Issue by FatimaCMD** [drajer-health/eCRNow#765]
Duplicates are being created for Travel History and Occupation Observation Resources in the eCR reports generated. I have cross-checked our FHIR server to confirm that duplicates do not exist there. Please see the attachments for the  eICR Report & Postman Query snippets and Loading Query for more details.

![image](https://github.com/drajer-health/eCRNow/assets/175307482/ce5653f2-3120-49a7-b56a-00409a1b7842)
![image](https://github.com/user-attachments/assets/bed5248b-218b-46fe-901b-65d566fb0ee1)
![image](https://github.com/user-attachments/assets/ab3d5fd4-8ff4-49a3-98ed-76279e5271ea)
![image](https://github.com/user-attachments/assets/a2c4ba6f-47ef-4443-8431-1db3750ea738)
![image](https://github.com/user-attachments/assets/468d716e-70be-4c97-a8ac-c8a2a8db8552)

[LoadingQueryBundle_26495_26503.json](https://github.com/user-attachments/files/16195193/LoadingQueryBundle_26495_26503.json)

**Comment by nbashyam** [comment]
Thanks, we will analyze and get back .

**Comment by FatimaCMD** [comment]
> Thanks, we will analyze and get back .

Any update on this?

**Comment by FatimaCMD** [comment]
Any update on this @nbashyam?
