### ISSUE TITLE
eICR Missing Trigger Template for Triggering Condition

### ISSUE THREAD

**Issue by VictoriaVaughn** [drajer-health/eCRNow#766]
ICD10 code W54.0XXA is present in the RCTC list. It is the only trigger code present in the Trigger Query file as an encounter diagnosis in the Encounter resource. The Condition referenced i the Encounter resource that contained the trigger ICD10 code, was present in the Loading Query file, and present in the eICR, but the trigger template was note added. This led to a fatal error when submitting the eICR as no Trigger template was present anywhere in the eICR.

See excerpt from the eICR below:

					<entry typeCode="DRIV">
						<act classCode="ACT" moodCode="EVN">
							<templateId root="2.16.840.1.113883.10.20.22.4.3"/>
							<templateId root="2.16.840.1.113883.10.20.22.4.3" extension="2015-08-01"/>
							<id root="b9e958bc-f6ed-4be1-84ae-d7f128bc7dad"/>
							<code code="CONC" codeSystem="2.16.840.1.113883.5.6" codeSystemName="HL7ActClass" displayName="Concern"/>
							<statusCode code="active"/>
							<effectiveTime>
								<low value="20240612092711-0500"/>
								<high nullFlavor="NI"/>
							</effectiveTime>
							<entryRelationship typeCode="SUBJ">
								<observation classCode="OBS" moodCode="EVN">
									<templateId root="2.16.840.1.113883.10.20.22.4.4"/>
									<templateId root="2.16.840.1.113883.10.20.22.4.4" extension="2015-08-01"/>
									<id root="2.16.840.1.113883.1.1.1.1" extension="43d2aaac8e929f84dd0e9d85cd7131883d1f9156"/>
									<code code="282291009" codeSystem="2.16.840.1.113883.6.96" codeSystemName="SNOMED-CT" displayName="Diagnosis">
										<translation code="29308-4" codeSystem="2.16.840.1.113883.6.1" codeSystemName="LOINC" displayName="Diagnosis"/>
									</code>
									<statusCode code="completed"/>
									<effectiveTime>
										<low value="20240612"/>
										<high nullFlavor="NI"/>
									</effectiveTime>
									<value xsi:type="CD" nullFlavor="OTH">
										<translation code="W54.0XXA" codeSystem="2.16.840.1.113883.6.90" codeSystemName="ICD-10-CM" displayName="Bitten by dog, initial encounter"/>
									</value>
								</observation>
							</entryRelationship>
						</act>
					</entry>

Note: I am not able to provide the eICR, Trigger Query, or Loading Query in full due to this being a Production example with a Live patient.

**Comment by nbashyam** [comment]
Not needed Victoria, we can try to reproduce.

**Comment by nbashyam** [comment]
Added in 3.1.5
