### ISSUE TITLE
Scheduled tasks don't happen on time. Skew of hours  or days.

### ISSUE THREAD

**Issue by kmarx** [drajer-health/eCRNow#767]
We see unexpected delays between when an encounter is launched with eCRNow and when it does it’s scheduled processing. For example, immediately reportable cases should be evaluated 1hr after the patient launch but we see it happening several hours later instead.

The speculation is that it’s due to eCRNow using GMT whereas our pods and EHR databases are in Pacific time. 

If so, perhaps eCRNow has to get the Postgres current database timezone and adjust for the offset. This is our preference and others might also benefit. Admittedly, we might be able to run our pods in GMT and accommodate for the shift in our own queries.

To wit:
- `SELECT * FROM pg_timezone_names WHERE name = current_setting('TIMEZONE');`
- `show timezone;`

**Comment by nbashyam** [comment]
This looks like it is due to the use of a local time zone rather than GMT. Need to analyze further to see what we can find.
