### ISSUE TITLE
Unable to reLaunchPatient the Patient Encounter 

### ISSUE THREAD

**Issue by SasidharKVN** [drajer-health/eCRNow#768]
we are using the latest v3.1.4 eCRNow App.
On reLaunchPatient the patient encounter,  we got the  `org.opencds.cqf.cql.engine.exception.CqlException: Translation of library expression failed with the following message: Could not resolve identifier %encounter in the current library.` error.

**reLaunch Request**
`{
	"patientId": "98466203-****-4b94-****-cfacc57e7293",
         "encounterId": "76692d71-****-4ea1-****-445da26fc329",
	"fhirServerURL": "https://****/fhir-server/api/v4",
	"validationMode": true,
	"ehrLaunchContext": {
		"X-FHIR-TENANT-ID": "testdb"
		}
}`
Attached the [ecrNow.log](https://github.com/user-attachments/files/16236534/ecrNow.log)

**Comment by nbashyam** [comment]
Can you please make sure you are using the right ERSDv2 file. What ERSD version and file are you using ?

**Comment by mmatiasalt** [comment]
@SasidharKVN - Following up to see if you were able to review Nagesh's suggestion and retested with the correct eRSD V2 file? Thank you.

**Comment by mmatiasalt** [comment]
@SasidharKVN following up to see if you retested without issue? Is this resolved?

**Comment by SasidharKVN** [comment]
I am using ERSDv2 file and reLaunchPatient working as expected. Thank you for your support.
