### ISSUE TITLE
CDA: EncompassingEncounter section - Code should use Encounter Class instead of Encounter Type.

### ISSUE THREAD

**Issue by AnanthaKrishnaV** [drajer-health/eCRNow#77]
In EncompassingEncounter section CODE is always nullflavour as it is using encounter.type instead of encounter.class[1]. As per spec Value Set: ActEncounterCode urn:oid:2.16.840.1.113883.1.11.13955 should be used for CODE. Valueset ActEncounterCode is used in Encounter.class as per [2].

[1] - https://github.com/drajer-health/eCRNow/blob/master/src/main/java/com/drajer/cdafromR4/CdaHeaderGenerator.java#L383
[2] - https://www.hl7.org/fhir/v3/ActEncounterCode/vs.html

**Comment by nbashyam** [comment]
Updated fixes to the baseline.
