### ISSUE TITLE
Include App Version and EHR Product 

### ISSUE THREAD

**Issue by mmatiasalt** [drajer-health/eCRNow#778]
- Requesting addition of exact eCR Now App Version (e.g. "3.1.4" instead of just "3.X" ) in document. 

- Requesting document include full EHR product information (e.g. "AthenaOne"  or "Athena Practice/Flow"instead of just "Athena"). 

This is essential for issue troubleshooting and distinguishing DQ differences in vendor products. 

Thank you!

**Comment by nbashyam** [comment]
Added the version 3.1.5 in the properties.

**Comment by nbashyam** [comment]
Also added the version to a fixed value in the code in the 3.1.5 baseline.

**Comment by nbashyam** [comment]
Added in 3.1.5
