### ISSUE TITLE
Enhancement Request - Handle US Core STU5+ OMB Race Category value (2131-1)

### ISSUE THREAD

**Issue by AGABB** [drajer-health/eCRNow#784]
**Situation** 
FHIR Version 4 is the version of FHIR that is compatible with the App. When it comes to the raceCode element, the app looks for the omb-race-category url extension and pulls the associated race code into the eICR. In both eICR 1.1 and 3.1, there are five allowed values that do not include 2131-1 (other race). This aligns with the omb-race-category value set in FHIR version 4, so everything works great. 
![image](https://github.com/user-attachments/assets/81ce7f85-e31e-4f28-b63c-2c075f8ce7d9)

In FHIR STU5 and up, the 2131-1 code is included as a valid value in the valueSet:
<img width="770" alt="image" src="https://github.com/user-attachments/assets/0bc2c5b0-bd8c-477b-a939-d8bffb8e834a">
For any vendors who have advanced their FHIR server to this version, a situation is now possible where their server can emit a valid value per the FHIR Spec, but result in an invalid value being included in the eICR. 

This will cause Schematron errors in the DQ Monitoring Report that is used for data quality validation by the onboarding team and PHAs. 

**Approach**
One solution, of course, is for the FHIR Server to revert back to the version 4 valueSet and not allow 2131-1. This does however feel like potentially a step in the wrong direction. FHIR R6 will eventually be required and this would have to be switched back. 

Another solution is to handle this in the app code - the app could, for instance, add a check in CdaHeaderGenerator.java such as:
```
    if (race != null && race.hasCode()) {
		if (race.getCode().equals(OTHER_RACE_code)) {
			patientDetails.append(
            CdaGeneratorUtils.getXmlForNullCD(
                CdaGeneratorConstants.RACE_CODE_EL_NAME, race.getCode()));
        else if (!isCodingNullFlavor(race)) {
        patientDetails.append(
            CdaGeneratorUtils.getXmlForCD(
                CdaGeneratorConstants.RACE_CODE_EL_NAME,
                race.getCode(),
                CdaGeneratorConstants.RACE_CODE_SYSTEM,
                CdaGeneratorConstants.RACE_CODE_SYSTEM_NAME,
                race.getDisplay()));
```

Submitting this request for eCR Now Team's input and review on behalf of McKesson Ontada

**Comment by nbashyam** [comment]
Make modification to allow OTHER Value as a mapping element to nullFLAVOR=OTH as shown below.

<raceCode nullFlavor="OTH">
.  <originalText>Other</originalText>
</raceCode>
<sdtc:raceCode ...../>

**Comment by nbashyam** [comment]
```<raceCode>
   <originalText>..
</raceCode> ```

**Comment by mmatiasalt** [comment]
@nbashyam as per Sarah, as per Chuck- they do sometimes get that code (2131-1 Other Race), so I think that the code change that you suggested would be fine.

**Comment by nbashyam** [comment]
It has been added to 3.1.6
