### ISSUE TITLE
eCR CCDA - Social History Section Occupiation#2 related Obsterm is not populating 

### ISSUE THREAD

**Issue by sumanathenahealth** [drajer-health/eCRNow#785]
eCR CCDA - Social History Section Occupiation#2 related Obsterm is not populating , 
The SNOMED code using for Occupiation#2  is 105421008 , As we have observed from eCR code base this SNOMED code is not considering for Occupiation#2 in eCR-CCDA,
PFA for eCR-Code base , eCR-CCDA.txt, LoadingQueryBundle.txt

![eCR_Code_Base](https://github.com/user-attachments/assets/99003aa4-6ee4-4c77-a34b-ab4328a0cc06)

[eICR-CCDA.txt](https://github.com/user-attachments/files/16727605/eICR-CCDA.txt)

[Bundle_cee32fa6-10c7-4c29-ae84-4a741fea0e17.txt](https://github.com/user-attachments/files/16727607/Bundle_cee32fa6-10c7-4c29-ae84-4a741fea0e17.txt)

[TriggerQueryBundle_2039940354155810_2040028206158630.txt](https://github.com/user-attachments/files/16727610/TriggerQueryBundle_2039940354155810_2040028206158630.txt)

[LoadingQueryBundle_2039940354155810_2040028206158630.txt](https://github.com/user-attachments/files/16727611/LoadingQueryBundle_2039940354155810_2040028206158630.txt)

**Comment by sumanathenahealth** [comment]
Any updates , on this ?

**Comment by mmatiasalt** [comment]
Hi @sumanathenahealth , this issue is still under review. We will update when possible. Thank you.

**Comment by sumanathenahealth** [comment]
Please provide update on this ?

**Comment by sumanathenahealth** [comment]
Please provide update on this ?

**Comment by mmatiasalt** [comment]
SNOMED code 105421008 represents “Educational achievement (observable entity)” which isn’t a code used for Occupation. We don’t collection education information in eCR, so I think this is not data we need in eCR.
