### ISSUE TITLE
Support new API hook for ph_message updates.

### ISSUE THREAD

**Issue by kmarx** [drajer-health/eCRNow#793]
Please consider supporting a new callback mechanism for when new entries or modifications are made to `ph_messages`. This would allow us to update our own state for launched encounters without having to poll via the `api/phMessages` endpoint to get status updates.

Note: we're considering doing this via AspecJ injection, but thought more formal support might be more generally useful. The payload of the callback could be the `PhMessageDaoImpl` or the like.

**Comment by kmarx** [comment]
We actually found a different approach for our use cases.

**Comment by nbashyam** [comment]
ok, so this is not needed anymore. closing the ticket.
