### ISSUE TITLE
Parameters swapped in NotificationContextController

### ISSUE THREAD

**Issue by AGABB** [drajer-health/eCRNow#807]
In the notification context controller , there is a bug concerning the parameter specification in the method. The third parameter should be notificationResourceId, and the fourth should be patientId, but they are swapped. [ Link to code block: https://github.com/drajer-health/eCRNow/blob/master/src/main/java/com/drajer/bsa/controller/NotificationContextController.java#L64-L66 ]

**Comment by nbashyam** [comment]
Include in 3.1.6

**Comment by nbashyam** [comment]
Add to 3.1.6

**Comment by nbashyam** [comment]
Fixed in 3.1.6
