### ISSUE TITLE
eRSD version is out of date

### ISSUE THREAD

**Issue by Lakshmanan301195** [drajer-health/eCRNow#814]
We have updated to the eRSD Version 1.2.4.0. But after this, multiple PHA's are sending us the following error.

**Error:**
The client submitted this case stating that for Electronic Case Reporting in the following states they were receiving an error stating "An initial report for a possible reportable condition was received on 20240916042310 with the file name. The eICR was processed with the warning of: outdated eRSD (RCTC) version.
The trigger code version your organization is using is out-of-date. Please have your EHR administrators install the current version for complete eCR functioning." Are there any additional steps that need to be taken by the client for these errors?

**Comment by mmatiasalt** [comment]
Hi @Lakshmanan301195, is this occurring still as of today's date? There was a fix implemented within the past week or so. If it is still occurring, can you please open a ticket with the AIMS service desk for this? https://aphlinformatics.atlassian.net/servicedesk/customer/portal/23/group/75/create/377 

if you can please provide examples for eCR Document ID for us to investigate that would be great. Thank you

**Comment by mmatiasalt** [comment]
@Lakshmanan301195 , Following up to see if you were still encountering this issue as of last week?

**Comment by nbashyam** [comment]
Not an app issue. Please reopen if anything is needed.
