### ISSUE TITLE
eICR is Adding Incomplete Section Information for Ignored Resources

### ISSUE THREAD

**Issue by VictoriaVaughn** [drajer-health/eCRNow#819]
During testing, we created two Observation resources that had a status of "unknown". As expected, these two resources were ignored (confirmed in the ecrnow logs), however a partial "RESULTS" section was still generated which led to a processing error as required fields (tbody) were missing data. 

Ignored resources:
![image](https://github.com/user-attachments/assets/85c9d040-45ae-444f-85d5-ebbcf590a3c4)

![image](https://github.com/user-attachments/assets/c9e7a743-309c-4456-9ec1-6be5aa339136)

Error received during validation:
![image](https://github.com/user-attachments/assets/43f4d975-26fc-4ee4-b89b-fa761add5464)

Results section in the problem eICR:
![image](https://github.com/user-attachments/assets/e96fffb8-c3a5-447c-95a5-18f7c6375665)

What the results section should look like when all observation resources have been ignored or not found:
![image](https://github.com/user-attachments/assets/ddb890cc-a0d4-4d00-b4ad-2a293d484e97)

Loading Query:
[2024-10-22T18_12_51,000000000+00_00_LoadingQueryBundle_28132a3b9e90b44123e4e8682cdd8e6fa1616141_2ada3ff309fcf1e0ae61cb9a22b2639686048a7e.json](https://github.com/user-attachments/files/17497029/2024-10-22T18_12_51.000000000%2B00_00_LoadingQueryBundle_28132a3b9e90b44123e4e8682cdd8e6fa1616141_2ada3ff309fcf1e0ae61cb9a22b2639686048a7e.json)
eICR:
[eICR Ignored Resource.txt](https://github.com/user-attachments/files/17497046/eICR.Ignored.Resource.txt)

We are currently using ecr now v3.1.3 with CDA R1.1

**Comment by nbashyam** [comment]
Will fix in 3.1.6

**Comment by nbashyam** [comment]
Fixed in 3.1.6
