### ISSUE TITLE
Java 17 and Release Branch Versions

### ISSUE THREAD

**Issue by medhost-chara** [drajer-health/eCRNow#837]
The documentation states to use master or java-17-master but if a vendor wants to use tested code that has been cutoff for a release, what branch should we use? 

See documentation:
https://github.com/drajer-health/eCRNow?tab=readme-ov-file#41-pre-requisites

If the latest Release is 3.1.6 it appears that this is java 8 only:
https://github.com/drajer-health/eCRNow/blob/3.1.6/pom.xml#L21

The java-17-master branch appears to be over a year old and does not contain the latest updates.

**Comment by nbashyam** [comment]
Please use the master branch. For e.g Release 3.1.6 or Release 3.1.7

The master branch has been verified to work with both Java 8 and Java 17. 

The default pom.xml is java 8, but it can easily be switched to java 17 and will work.
