### ISSUE TITLE
Minor: Documentation Not Updated to Mention ERSD V3

### ISSUE THREAD

**Issue by medhost-chara** [drajer-health/eCRNow#839]
Documentation is not updated to reference ERSD V3
https://github.com/drajer-health/eCRNow/blob/master/README.md#42-steps-to-build-and-run-the-app

<img width="1309" alt="image" src="https://github.com/user-attachments/assets/f70c207f-ddfb-47ab-9212-a0bb078c45d4">

Are there any other usage call outs for using ERSD V3 that should be mentioned?

**Comment by nbashyam** [comment]
Add to 3.1.7

**Comment by medhost-chara** [comment]
Thank you
