### ISSUE TITLE
SubscriptionUtilsTest class junit is failing

### ISSUE THREAD

**Issue by medhost-sonal** [drajer-health/eCRNow#840]
Test getNotificationContextTest() is failing in SubscriptionUtilsTest class because bund value is null. This value is calculated using `Bundle bund = ap.readBundleFromFile(absolutePath);`

In ApplicationUtils.readBundleFromFile method, jsonParser is throwing nullPointerException.

**Comment by medhost-sonal** [comment]
This test fails only when the test is ran independently. So this can be ignored.

**Comment by nbashyam** [comment]
Thanks, this ticket will be closed.
