### ISSUE TITLE
For Lab Result the trigger code observation should be sufficient 

### ISSUE THREAD

**Issue by nbashyam** [drajer-health/eCRNow#88]
When the specific lab test matches, the matching code should be in the code element of the observtaion and the other codes should be in the translation.

The observation value should be the value from the lab test, .

PAtient Id : 
Encounter Id: 

Observation with the matching LOINC code in the code element.

Value element should contain the value from the FHIR result value. If the value matches, then we should add the SDTC value set and value set version to the element.

**Comment by nbashyam** [comment]
Code matched so it should have the sdtc value set and version.

The eICR Trigger Result Observation would be created instead of the regular observation entry.

Matching code should always be in the code and other codes should be in the translation.

**Comment by nbashyam** [comment]
Retain the FHIR Id in the observation entry .id element . extension.

Create new GUID for organizers and any other location.

**Comment by nbashyam** [comment]
IF there are multiple components, add a sequential number to make it part of the extension..

**Comment by nbashyam** [comment]
The root is the AA OID configured.

**Comment by nbashyam** [comment]
Updates pushed to baseline.

**Comment by AnanthaKrishnaV** [comment]
Working as expected.
